// src/docs/DiceDoc.svelte
<script lang="ts">
  import DiceRoller from '../svelte/components/dice/DiceRoller.svelte'
  import { FACE_COUNT, type DiceKind } from '../core/dice/model'
  import DocPage from './svelte/DocPage.svelte'
  import type { ApiRow } from './svelte/types'

  const kinds: DiceKind[] = ['d6', 'd10', 'd20']
  let kind = $state<DiceKind>('d20')
  let value = $state(20)
  let rolling = $state(false)
  const api: ApiRow[] = [
    { prop: 'kind', type: "'d6' | 'd10' | 'd20'", description: 'Die face count and glyph.' },
    { prop: 'value', type: 'number', description: 'Authoritative settled result supplied by the host.' },
    { prop: 'rolling', type: 'boolean', description: 'Host-owned animation state while a roll is pending.' },
    { prop: 'onRoll', type: '() => void', description: 'Reports intent; the host computes the result.' },
    { prop: 'label', type: 'string', description: 'Visible roll button label.' },
    { prop: 'D10 / D20', type: 'LucideIcon', description: 'Custom glyphs that can also render through Tint Icon.' },
  ]
  const usage = `import { DiceRoller, D20 } from '@nebula/tint/dice'
import { Icon } from '@nebula/tint/icon'
let value = $state(1)
let rolling = $state(false)

async function roll() {
  rolling = true
  value = await api.roll('d20')
  rolling = false
}

<DiceRoller kind="d20" {value} {rolling} onRoll={roll} />

// The custom glyphs can also be used with Tint Icon.
<Icon icon={D20} size="xl" label="Twenty-sided die" />`

  function roll() {
    if (rolling) return
    rolling = true
    window.setTimeout(() => {
      value = 1 + Math.floor(Math.random() * FACE_COUNT[kind])
      rolling = false
    }, 650)
  }
</script>

<DocPage title="Dice" description="A controlled die that animates intent but never decides the authoritative result." importPath="@nebula/tint/dice" {usage} {api} accessibility="The roll control is a native button and is disabled while pending. The result is announced through a named status. Decorative animation stops for reduced-motion preferences; the host-supplied value still settles.">
  <div class="demo">
    <DiceRoller {kind} {value} {rolling} onRoll={roll} />
    <div role="group" aria-label="Die kind" class="kinds">
      {#each kinds as option}
        <button type="button" aria-pressed={kind === option} onclick={() => { kind = option; value = 1 }}>{option}</button>
      {/each}
    </div>
  </div>
</DocPage>

<style>
  .demo { display: grid; justify-items: center; gap: 1.25rem; }
  .kinds { display: flex; gap: .35rem; }
  button { border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); padding: .4rem .7rem; background: var(--tint-panel); color: var(--tint-muted); font: inherit; font-size: .8rem; cursor: pointer; }
  button[aria-pressed='true'] { background: var(--tint-accent-soft); color: var(--tint-accent); }
  button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); }
</style>

// src/docs/DiceDoc.tsx
import { useState } from 'react'
import { DiceRoller } from '../components/dice'
import type { DiceKind } from '../components/dice'
import { CodeBlock } from './components/CodeBlock'
import { DocsPage, DocsPreview, DocsSection } from './components/DocsPage'
import { PropsTable } from './components/PropsTable'

const usage = `import { DiceRoller } from 'tint/dice'

const [value, setValue] = useState(1)
const [rolling, setRolling] = useState(false)

async function roll() {
  setRolling(true)
  // The app owns the randomness — seeded, server-authoritative, whatever.
  const next = await api.roll('d20')
  setValue(next)
  setRolling(false)
}

<DiceRoller kind="d20" value={value} rolling={rolling} onRoll={roll} />`

const glyphUsage = `import { Icon } from 'tint/icon'
import { D20 } from 'tint/dice'

// lucide ships Dice1–Dice6 but no d10/d20, so those two faces are
// hand-authored glyphs rendered through the same Icon seam.
<Icon icon={D20} size="xl" />`

const props = [
  { name: 'value', type: 'number', required: true, description: 'The settled face. Rendered whenever `rolling` is false.' },
  { name: 'onRoll', type: '() => void', required: true, description: 'Reports intent only. The app produces the next value and clears `rolling`.' },
  { name: 'kind', type: "'d6' | 'd10' | 'd20'", defaultValue: "'d6'", description: 'Face count and which glyph renders. d6 uses lucide’s pips; d10/d20 use tint’s own outlines with a numeric face.' },
  { name: 'rolling', type: 'boolean', defaultValue: 'false', description: 'Animates the die and disables the button. Reduced motion skips the flicker but still lands on the result.' },
  { name: 'label', type: 'string', defaultValue: "'Roll'", description: 'Visible text on the roll button.' },
  { name: 'className', type: 'string', description: 'Extra classes for the wrapper.' },
]

const KINDS: DiceKind[] = ['d6', 'd10', 'd20']
const FACES: Record<DiceKind, number> = { d6: 6, d10: 10, d20: 20 }

export function DiceDoc() {
  const [kind, setKind] = useState<DiceKind>('d20')
  const [value, setValue] = useState(20)
  const [rolling, setRolling] = useState(false)

  const roll = () => {
    setRolling(true)
    window.setTimeout(() => {
      setValue(1 + Math.floor(Math.random() * FACES[kind]))
      setRolling(false)
    }, 700)
  }

  return (
    <DocsPage
      route="components/dice"
      title="Dice"
      intro="A controlled dice roller, and the library’s worked example of extending Icon past lucide’s catalog."
      note={
        <>
          Tint does not generate the number. <code>onRoll</code> reports intent; the app
          answers by setting <code>rolling</code> and then the new <code>value</code>,
          which is what lets a roll be seeded, replayed, or server-authoritative.
        </>
      }
    >
      <DocsSection id="preview" title="Preview">
        <DocsPreview className="flex flex-col items-center gap-5">
          <DiceRoller kind={kind} value={value} rolling={rolling} onRoll={roll} />
          <div role="group" aria-label="Die kind" className="flex gap-1">
            {KINDS.map((option) => (
              <button
                key={option}
                type="button"
                onClick={() => {
                  setKind(option)
                  setValue(1)
                }}
                aria-pressed={kind === option}
                className="rounded-md border border-tint-border px-3 py-1.5 text-xs font-medium text-tint-muted transition hover:bg-tint-surface aria-pressed:bg-tint-accent-soft aria-pressed:text-tint-accent focus-visible:outline-2 focus-visible:outline-tint-accent"
              >
                {option}
              </button>
            ))}
          </div>
        </DocsPreview>
      </DocsSection>

      <DocsSection id="usage" title="Usage">
        <CodeBlock code={usage} />
        <h3 className="mt-8 mb-3 text-base font-semibold text-tint-ink">
          The glyphs, on their own
        </h3>
        <CodeBlock code={glyphUsage} />
      </DocsSection>

      <DocsSection id="api" title="API">
        <PropsTable rows={props} />
      </DocsSection>
    </DocsPage>
  )
}
