// src/docs/feed/FeedDoc.tsx
import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import {
  DEMO_FEED,
  FeedLayout,
  NarrationTransport,
  ReaderPane,
  SourceHealthBadge,
  SplitPane,
  ViewModeToggle,
  type FeedEntry,
  type FeedLayoutVariant,
} from '../../components/feed'
import { Dialog } from '../../components/dialog'
import { Button } from '../../components/button'
import { ToastProvider, useToast } from '../../components/toast'
import { TreeView, type TreeNode } from '../../components/tree'
import { Badge } from '../../components/badge'
import { MAYA_TTS_SRC } from '../chat/demo/scenarios'
import { CodeBlock } from '../components/CodeBlock'
import { DocsPage, DocsPreview, DocsSection } from '../components/DocsPage'
import { PropsTable } from '../components/PropsTable'
import {
  getDemoFeedStore,
  subscribeDemoFeedStore,
} from './demoStore'

const usage = `import {
  FeedLayout,
  SplitPane,
  ReaderPane,
  ViewModeToggle,
  NarrationTransport,
  SourceHealthBadge,
} from 'tint/feed'`

type FilterId = 'all' | 'new' | 'unread' | 'matched'

function filterEntries(
  entries: readonly FeedEntry[],
  filter: FilterId,
  matchedIds: ReadonlySet<string>,
): FeedEntry[] {
  switch (filter) {
    case 'unread':
      return entries.filter((entry) => entry.readState === 'unread')
    case 'matched':
      return entries.filter((entry) => matchedIds.has(entry.id))
    case 'new':
      return [...entries].sort((a, b) => (a.publishedAt < b.publishedAt ? 1 : -1)).slice(0, 3)
    default:
      return [...entries]
  }
}

function Workbench() {
  const { feed } = useSyncExternalStore(subscribeDemoFeedStore, getDemoFeedStore, getDemoFeedStore)
  const { push } = useToast()
  const [variant, setVariant] = useState<FeedLayoutVariant>('feed')
  const [filter, setFilter] = useState<FilterId>('all')
  const [selectedSourceId, setSelectedSourceId] = useState<string | null>(feed.sources[0]?.id ?? null)
  const [selectedEntryId, setSelectedEntryId] = useState<string | null>(feed.entries[0]?.id ?? null)
  const [startWidth, setStartWidth] = useState('14rem')
  const [middleWidth, setMiddleWidth] = useState('1fr')
  const [askOpen, setAskOpen] = useState(false)
  const [expandedIds, setExpandedIds] = useState<string[]>(['sources'])

  const matchedIds = useMemo(
    () => new Set(feed.matches.map((match) => match.entryId)),
    [feed.matches],
  )

  const sourceLabels = useMemo(
    () => Object.fromEntries(feed.sources.map((source) => [source.id, source.handle])),
    [feed.sources],
  )

  const tree: TreeNode[] = useMemo(
    () => [
      {
        id: 'sources',
        label: 'Sources',
        children: feed.sources.map((source) => ({
          id: source.id,
          label: source.handle,
          trailing: (
            <span className="inline-flex items-center gap-1">
              {source.unreadCount > 0 ? (
                <Badge tone="accent">{source.unreadCount}</Badge>
              ) : null}
              <SourceHealthBadge health={source.health} />
            </span>
          ),
        })),
      },
    ],
    [feed.sources],
  )

  const scoped = selectedSourceId
    ? feed.entries.filter((entry) => entry.sourceId === selectedSourceId)
    : feed.entries
  const visible = filterEntries(scoped, filter, matchedIds)
  const selected = feed.entries.find((entry) => entry.id === selectedEntryId) ?? visible[0]

  useEffect(() => {
    const timer = window.setTimeout(() => {
      const match = DEMO_FEED.matches[0]
      if (!match) return
      const entry = DEMO_FEED.entries.find((item) => item.id === match.entryId)
      push({
        title: 'New policy match',
        description: entry?.title ?? match.entryId,
        tone: 'info',
      })
    }, 4500)
    return () => window.clearTimeout(timer)
  }, [push])

  return (
    <>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <ViewModeToggle value={variant} onChange={setVariant} />
        <div className="flex flex-wrap gap-1" role="group" aria-label="Entry filter">
          {(['all', 'new', 'unread', 'matched'] as const).map((id) => (
            <Button
              key={id}
              size="sm"
              variant={filter === id ? 'primary' : 'ghost'}
              onClick={() => setFilter(id)}
            >
              {id}
            </Button>
          ))}
        </div>
        <Button size="sm" variant="secondary" onClick={() => setAskOpen(true)}>
          Ask Maya
        </Button>
      </div>

      <SplitPane
        className="h-[36rem] rounded-xl border border-tint-border"
        startWidth={startWidth}
        middleWidth={middleWidth}
        endWidth="22rem"
        onStartWidthChange={(px) => setStartWidth(`${px}px`)}
        onMiddleWidthChange={(px) => setMiddleWidth(`${px}px`)}
        start={
          <TreeView
            className="p-2"
            nodes={tree}
            expandedIds={expandedIds}
            onExpandedChange={setExpandedIds}
            selectedIds={selectedSourceId ? [selectedSourceId] : []}
            onSelectedChange={(ids) => setSelectedSourceId(ids[0] ?? null)}
          />
        }
        middle={
          <div className="p-3">
            <FeedLayout
              entries={visible}
              variant={variant}
              sourceLabels={sourceLabels}
              selectedId={selected?.id ?? null}
              onSelect={setSelectedEntryId}
            />
          </div>
        }
        end={
          selected ? (
            <ReaderPane
              className="h-full rounded-none border-0"
              header={
                <div className="flex flex-col gap-2">
                  <div>
                    <h3 className="m-0 text-base font-semibold text-tint-ink">{selected.title}</h3>
                    <p className="m-0 mt-1 text-xs text-tint-muted">
                      {sourceLabels[selected.sourceId] ?? selected.sourceId}
                    </p>
                  </div>
                  <NarrationTransport src={MAYA_TTS_SRC} label="Cached narration" />
                </div>
              }
            >
              <p className="m-0 whitespace-pre-wrap">{selected.body ?? selected.excerpt}</p>
            </ReaderPane>
          ) : (
            <p className="p-4 text-sm text-tint-muted">Select an entry.</p>
          )
        }
      />

      <Dialog
        open={askOpen}
        onOpenChange={setAskOpen}
        title="Ask Maya to subscribe"
        description="Opens the Chat Subscriptions scenario — Maya confirms before writing Source + Policy."
        actions={
          <Button
            variant="primary"
            onClick={() => {
              setAskOpen(false)
              window.location.hash = '#/components/chat?scenario=subscriptions'
            }}
          >
            Open chat scenario
          </Button>
        }
      >
        <p className="m-0 text-sm text-tint-muted">
          Example: “subscribe to misskatie, notify, cache on release” or “watch domain for token,
          use k2s-unlock”.
        </p>
      </Dialog>
    </>
  )
}

export function FeedDoc() {
  return (
    <ToastProvider>
      <DocsPage
        route="components/feed"
        title="Feed"
        intro="Subscriptions workbench: sources tree, layout variants, and a reader pane. Host owns FeedDocument; Tint presents it."
        note="Demo toast fires once after a few seconds for a fixture policy match. Narration uses the cached Maya clip — no live TTS."
      >
        <DocsSection id="preview" title="Workbench">
          <DocsPreview className="p-3 sm:p-4">
            <Workbench />
          </DocsPreview>
        </DocsSection>

        <DocsSection id="usage" title="Usage">
          <CodeBlock code={usage} />
        </DocsSection>

        <DocsSection id="api" title="API">
          <PropsTable
            rows={[
              {
                name: 'entries',
                type: 'readonly FeedEntry[]',
                required: true,
                description: 'Host-owned feed rows for FeedLayout.',
              },
              {
                name: 'variant',
                type: "FeedLayoutVariant",
                description: 'wall | list | magazine | ticker | carousel | feed.',
              },
              {
                name: 'sourceLabels',
                type: 'Record<string, string>',
                description: 'sourceId → handle for attribution lines.',
              },
              {
                name: 'selectedId',
                type: 'string | null',
                description: 'Controlled selection for card/row highlight.',
              },
              {
                name: 'onSelect',
                type: '(entryId: string) => void',
                description: 'Selection intent; host updates selectedId.',
              },
              {
                name: 'renderActions',
                type: '(entry: FeedEntry) => ReactNode',
                description: 'Optional trailing actions per entry.',
              },
              {
                name: 'empty',
                type: 'ReactNode',
                description: 'Empty-state content when entries is empty.',
              },
              {
                name: 'start/middle/end',
                type: 'ReactNode',
                description: 'SplitPane columns; end is optional for two-column shells.',
              },
              {
                name: 'startWidth/middleWidth/endWidth',
                type: 'string',
                description: 'Host-owned CSS widths; drag reports pixels via callbacks.',
              },
              {
                name: 'onStartWidthChange/onMiddleWidthChange',
                type: '(widthPx: number) => void',
                description: 'Resize callbacks; host sets width props.',
              },
              {
                name: 'minPanePx',
                type: 'number',
                description: 'Minimum pane width while dragging.',
              },
              {
                name: 'header/highlightLayer/children',
                type: 'ReactNode',
                description: 'ReaderPane sticky header, highlight slot, and article body.',
              },
              {
                name: 'src',
                type: 'string',
                required: true,
                description: 'NarrationTransport host-owned audio URL.',
              },
              {
                name: 'label/rates/onEnded',
                type: 'string | number[] | () => void',
                description: 'NarrationTransport chrome and speed options.',
              },
              {
                name: 'health',
                type: 'SourceHealth',
                required: true,
                description: 'SourceHealthBadge crawl state.',
              },
              {
                name: 'value/onChange/options',
                type: 'FeedLayoutVariant',
                description: 'ViewModeToggle controlled variant picker.',
              },
              {
                name: 'text/highlights/activeId/onHighlightClick',
                type: 'string | TextHighlight[]',
                description: 'HighlightLayer precomputed spans over plain text.',
              },
              {
                name: 'position/open/actions/onAction',
                type: 'SelectionToolbar props',
                description: 'Floating selection actions; host measures position.',
              },
              {
                name: 'entry/sourceLabel/selected/onSelect/actions',
                type: 'FeedEntryCard / FeedEntryRow',
                description: 'Card and row presentational props.',
              },
              { name: 'className', type: 'string', description: 'Appended to the root element.' },
              { name: 'disabled', type: 'boolean', description: 'Disables ViewModeToggle controls.' },
            ]}
          />
        </DocsSection>
      </DocsPage>
    </ToastProvider>
  )
}

// src/docs/FeedDoc.svelte
<script lang="ts">
  import { FeedLayout, ReaderPane, SourceHealthBadge, ViewModeToggle, type FeedEntry, type FeedLayoutVariant } from '../svelte'
  import DocPage from './svelte/DocPage.svelte'
  import type { ApiRow } from './svelte/types'

  const entries: FeedEntry[] = [
    { id: 'first', sourceId: 'updates', title: 'Night Drive mix is ready', url: '#night-drive', publishedAt: '2026-09-30T10:00:00Z', excerpt: 'A new mix and track notes are available for review.', body: 'The Night Drive mix is ready. Listen through the transition into the closing track and share your notes.', tags: ['music', 'mix'], readState: 'unread', contentKind: 'article', artifactStatus: 'ready' },
    { id: 'second', sourceId: 'updates', title: 'October release schedule', url: '#october', publishedAt: '2026-09-29T14:00:00Z', excerpt: 'Five releases are planned for next month.', body: 'The October schedule includes five releases. Review the dates before publishing the calendar.', tags: ['release'], readState: 'read', contentKind: 'article' },
    { id: 'third', sourceId: 'forum', title: 'Production notes from the forum', url: '#notes', publishedAt: '2026-09-28T08:00:00Z', excerpt: 'The community shared feedback on the latest arrangement.', body: 'Forum members suggested a shorter intro and a clearer vocal entrance.', tags: ['discussion'], readState: 'read', contentKind: 'thread' },
  ]
  let variant = $state<FeedLayoutVariant>('feed')
  let selectedId = $state<string | null>('first')
  let selectedEntry = $derived(entries.find((entry) => entry.id === selectedId))
  const api: ApiRow[] = [
    { prop: 'entries / variant', type: 'FeedEntry[] / FeedLayoutVariant', description: 'Host-owned entries and responsive feed, list, ticker, magazine, carousel, or wall layout.' },
    { prop: 'selectedId / onSelect', type: 'string | null / (id) => void', description: 'Controlled entry selection; the host updates its own document.' },
    { prop: 'renderActions / sourceLabels', type: 'Snippet / Record<string, string>', description: 'Optional entry actions and readable source attribution.' },
    { prop: 'ReaderPane header / children', type: 'string | Snippet / Snippet', description: 'Scrollable article reading surface.' },
    { prop: 'ViewModeToggle value / onChange', type: 'FeedLayoutVariant / callback', description: 'Controlled layout choice with pressed state.' },
    { prop: 'FeedEntryCard / FeedEntryRow entry', type: 'FeedEntry', description: 'The entry rendered by a standalone card or row.' },
    { prop: 'FeedEntryCard / FeedEntryRow sourceLabel', type: 'string', description: 'Readable source name shown beside the published time.' },
    { prop: 'FeedEntryCard / FeedEntryRow selected', type: 'boolean', description: 'Host-owned selected state for a standalone entry view.' },
    { prop: 'FeedEntryCard / FeedEntryRow actions', type: 'Snippet', description: 'Optional controls rendered independently of entry selection.' },
    { prop: 'FeedLayout empty', type: 'string | Snippet', description: 'Custom message or content when no entries are supplied.' },
    { prop: 'ReaderPane highlightLayer', type: 'Snippet', description: 'Optional overlay for host-provided text highlights.' },
    { prop: 'SelectionToolbar position', type: '{ x: number; y: number } | null', description: 'Viewport coordinates for the floating toolbar; null hides it.' },
    { prop: 'SelectionToolbar open', type: 'boolean', description: 'Host-controlled visibility; a position is also required.' },
    { prop: 'SelectionToolbar actions', type: 'readonly SelectionToolbarAction[]', description: 'Ordered actions with labels, optional icons, disabled state, and danger styling.' },
    { prop: 'SelectionToolbar onAction', type: '(actionId: string) => void', description: 'Emits the activated action ID for the host to handle.' },
    { prop: 'ViewModeToggle options', type: 'readonly FeedLayoutVariant[]', description: 'Restricts the layout choices displayed by the toggle.' },
    { prop: 'ViewModeToggle disabled', type: 'boolean', description: 'Disables layout choice buttons.' },
    { prop: 'SourceHealthBadge health', type: 'SourceHealth', description: 'Text and tone for healthy, unreachable, inactive, or dormant sources.' },
    { prop: 'SplitPane start / middle / end', type: 'Snippet / Snippet / Snippet?', description: 'Required first and middle panes, with an optional third pane.' },
    { prop: 'SplitPane startWidth / middleWidth / endWidth', type: 'string', description: 'Host-provided CSS grid sizes; defaults are 14rem, 1fr, and 22rem.' },
    { prop: 'SplitPane onStartWidthChange', type: '(widthPx: number) => void', description: 'Emits pointer or keyboard resize intent for the first pane.' },
    { prop: 'SplitPane onMiddleWidthChange', type: '(widthPx: number) => void', description: 'Emits resize intent for the middle pane when a third pane exists.' },
    { prop: 'SplitPane minPanePx', type: 'number', description: 'Minimum pane width used to clamp resize intents; defaults to 120 pixels.' },
    { prop: 'HighlightLayer text', type: 'string', description: 'Source text aligned with the reading surface.' },
    { prop: 'HighlightLayer highlights', type: 'readonly TextHighlight[]', description: 'Ranges and tones to mark over the source text.' },
    { prop: 'HighlightLayer activeId', type: 'string | null', description: 'Highlight ID receiving the active outline.' },
    { prop: 'HighlightLayer onHighlightClick', type: '(id: string) => void', description: 'Makes marked ranges actionable and emits their IDs.' },
    { prop: 'NarrationTransport src', type: 'string', description: 'Audio source URL; changing it resets transport progress.' },
    { prop: 'NarrationTransport label', type: 'string', description: 'Readable name for the narration control; defaults to Narration.' },
    { prop: 'NarrationTransport rates', type: 'readonly number[]', description: 'Playback speed choices shown by the transport.' },
    { prop: 'NarrationTransport onEnded', type: '() => void', description: 'Notifies the host when audio playback finishes.' },
    { prop: 'class', type: 'string', description: 'Optional CSS class forwarded to the relevant feed component root.' },
  ]
  const usage = `import { FeedLayout, ReaderPane, ViewModeToggle } from '@nebula/tint/feed'

let variant = $state<FeedLayoutVariant>('feed')
let selectedId = $state<string | null>(null)
<ViewModeToggle value={variant} onChange={(next) => variant = next} />
<FeedLayout {entries} {variant} {selectedId}
  onSelect={(id) => selectedId = id} />
<ReaderPane header={selectedEntry?.title ?? 'Choose an entry'}>
  <p>{selectedEntry?.body}</p>
</ReaderPane>`
</script>

<DocPage title="Feed and Reader" description="Host-controlled entries, layout, and selection over a plain TypeScript feed document. Switch layouts and choose an entry to update the reader pane." importPath="@nebula/tint/feed" {usage} {api} accessibility="Card and row titles are native selection buttons with visible focus and pressed state. Nested actions remain independent, and unread entries have a text label. Layout buttons expose their selected state in text and ARIA. Source health uses a text badge; the reader remains a semantic article.">
  <div class="feed-demo">
    <div class="toolbar"><ViewModeToggle value={variant} onChange={(next) => variant = next} /><span>Source <SourceHealthBadge health="healthy" /></span></div>
    <div class="columns">
      <FeedLayout {entries} {variant} {selectedId} onSelect={(id) => selectedId = id} sourceLabels={{ updates: 'Studio updates · rss', forum: 'Community · forum' }} />
      <div class="reader"><ReaderPane header={selectedEntry?.title ?? 'Choose an entry'}><p>{selectedEntry?.body ?? 'Choose an entry from the feed.'}</p></ReaderPane></div>
    </div>
    <p aria-live="polite">Selected entry: {selectedEntry?.title ?? 'none'}</p>
  </div>
</DocPage>

<style>
  .feed-demo { display: grid; gap: 1rem; }
  .toolbar { display: flex; align-items: center; justify-content: space-between; gap: .75rem; flex-wrap: wrap; }
  .toolbar > span { display: inline-flex; align-items: center; gap: .4rem; color: var(--tint-muted); font-size: .8rem; }
  .columns { display: grid; gap: 1rem; min-width: 0; }
  .reader { min-height: 18rem; }
  p { margin: 0; color: var(--tint-muted); font-size: .84rem; }
  @container (min-width: 800px) { .columns { grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); } }
</style>
