// src/docs/ShellDoc.tsx
import { useState } from "react";
import { Home, Search, Settings } from "lucide-react";
import { Icon } from "../components/icon";
import {
  AppShell,
  WorkspaceTabs,
  WorkspaceSplit,
  MetadataPanel,
  DetailSheet,
  FilterBar,
  CommandPalette,
  EmptyState,
  NavRail,
  StatusBar,
  TopNav,
  WorkspaceHeader,
  type CommandPaletteItem,
  type NavGroup,
  type StatusItem,
} from "../components/shell";
import {
  DocsDemo,
  DocsFooter,
  DocsPage,
  DocsSection,
} from "./components/DocsPage";

const commands: CommandPaletteItem[] = [
  {
    id: "search",
    label: "Search workspace",
    description: "Find files and projects",
    shortcut: "⌘F",
  },
  { id: "settings", label: "Open settings", keywords: ["preferences"] },
];
const groups: NavGroup[] = [
  {
    id: "workspace",
    label: "Workspace",
    items: [
      { id: "home", label: "Home", href: "#home", icon: <Icon icon={Home} /> },
      {
        id: "settings",
        label: "Settings",
        href: "#settings",
        icon: <Icon icon={Settings} />,
      },
    ],
  },
];
const statusItems: StatusItem[] = [
  { id: "saved", label: "All changes saved", tone: "success" },
];
const example = `import { AppShell, NavRail, WorkspaceHeader, StatusBar } from '@nebula/tint/shell'

<AppShell
  nav={<NavRail groups={groups} activeId="home" onNavigate={navigate} />}
  header={<WorkspaceHeader breadcrumbs={breadcrumbs} title="Workspace" />}
  aside={<Inspector />}
  status={<StatusBar items={statusItems} connection={{ state: 'connected', label: 'Connected' }} />}
>
  <YourWorkspace />
</AppShell>`;
const topExample = `import { AppShell, TopNav, WorkspaceHeader, StatusBar } from '@nebula/tint/shell'

<AppShell
  navPosition="top"
  nav={<TopNav brand={<a href="/">Acme</a>} groups={groups} activeId="home" onNavigate={navigate} actions={<UserMenu />} />}
  header={<WorkspaceHeader breadcrumbs={breadcrumbs} title="Workspace" />}
  status={<StatusBar items={statusItems} connection={{ state: 'connected', label: 'Connected' }} />}
>
  <YourWorkspace />
</AppShell>`;

export function ShellDoc() {
  const [paletteOpen, setPaletteOpen] = useState(false);
  const [tab, setTab] = useState("info"),
    [detailOpen, setDetailOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [toolsWidth, setToolsWidth] = useState(200);
  return (
    <DocsPage
      route="components/shell"
      title="Application shell"
      intro="Controlled, composable workspace chrome with responsive container-query tiers, grouped navigation, headers, commands, status, and generic states."
    >
      <DocsSection id="preview" title="Workspace shell">
        <DocsDemo code={example} className="[&>div:first-child]:p-0">
          <div className="h-[28rem] overflow-hidden rounded-lg">
            <AppShell
              nav={
                <NavRail
                  aria-label="Demo navigation"
                  groups={groups}
                  activeId="home"
                />
              }
              header={
                <WorkspaceHeader
                  breadcrumbs={[
                    { label: "Projects", href: "#projects" },
                    { label: "Tint" },
                  ]}
                  title="Tint workspace"
                  subtitle="Phase 1 shell"
                  actions={
                    <button
                      type="button"
                      onClick={() => setPaletteOpen(true)}
                      aria-label="Open commands"
                    >
                      <Icon icon={Search} />
                    </button>
                  }
                />
              }
              aside={
                <div className="p-4 text-sm text-tint-muted">Inspector</div>
              }
              status={
                <StatusBar
                  items={statusItems}
                  connection={{ state: "connected", label: "Connected" }}
                />
              }
            >
              <EmptyState
                title="Choose a project"
                description="The host owns data and routing."
              />
            </AppShell>
            <CommandPalette
              open={paletteOpen}
              onOpenChange={setPaletteOpen}
              query={query}
              onQueryChange={setQuery}
              items={commands}
            />
          </div>
        </DocsDemo>
      </DocsSection>
      <DocsSection
        id="top-nav"
        title="Top navigation"
        description='TopNav renders the same NavGroup[] data as a horizontal bar, with brand and action slots and a More overflow menu via maxVisibleItems. Pair it with AppShell navPosition="top" to place the nav above the header instead of the left rail.'
      >
        <DocsDemo code={topExample} className="[&>div:first-child]:p-0">
          <div className="h-[24rem] overflow-hidden rounded-lg">
            <AppShell
              navPosition="top"
              nav={
                <TopNav
                  aria-label="Demo top navigation"
                  brand={<span className="text-sm font-semibold">Tint</span>}
                  groups={groups}
                  activeId="home"
                  actions={
                    <span className="text-xs text-tint-muted">user@acme</span>
                  }
                />
              }
              header={
                <WorkspaceHeader
                  breadcrumbs={[
                    { label: "Projects", href: "#projects" },
                    { label: "Tint" },
                  ]}
                  title="Tint workspace"
                />
              }
              status={
                <StatusBar
                  items={statusItems}
                  connection={{ state: "connected", label: "Connected" }}
                />
              }
            >
              <EmptyState
                title="Choose a project"
                description="The host owns data and routing."
              />
            </AppShell>
          </div>
        </DocsDemo>
      </DocsSection>
      <DocsSection
        id="usage"
        title="Usage"
        description="Every stateful seam is controlled. Tint performs no routing or fetching."
      >
        <pre className="overflow-auto rounded-xl bg-tint-surface p-4 text-sm">
          {example}
        </pre>
      </DocsSection>
      <DocsSection
        id="api"
        title="API"
        description="AppShell exposes nav, header, children, aside, and status slots, plus navPosition ('rail' default, or 'top'). NavRail and TopNav consume NavGroup[] and emit onNavigate(id, href); TopNav adds brand, actions, overflowLabel, and maxVisibleItems. WorkspaceHeader supports breadcrumbs, title, subtitle, and actions. StatusItem tone reuses BadgeTone; ErrorBanner exposes detail, actions, dismissal, and diagnostics."
      >
        <p className="text-sm text-tint-muted">
          Use <code>data-tint-*</code> attributes as stable host styling and
          test seams.
        </p>
      </DocsSection>
      <DocsSection id="workspace" title="Workspace content">
        <DocsDemo
          code={
            "import { WorkspaceTabs, MetadataPanel, FilterBar, DetailSheet } from '@nebula/tint/shell'"
          }
        >
          <FilterBar
            actions={
              <button onClick={() => setDetailOpen(true)}>Inspect</button>
            }
          >
            <label>
              Filter <input placeholder="Type a label" />
            </label>
          </FilterBar>
          <WorkspaceTabs
            label="Example workspace"
            value={tab}
            onChange={setTab}
            tabs={[
              {
                id: "info",
                label: "Information",
                content: (
                  <MetadataPanel
                    title="Example item"
                    eyebrow="METADATA"
                    description="Display fields supplied by the host."
                    fields={[{ label: "Year", value: 2026 }]}
                  />
                ),
              },
              {
                id: "notes",
                label: "Notes",
                content: (
                  <textarea
                    aria-label="Notes"
                    defaultValue="Draft state survives tab switches"
                  />
                ),
              },
            ]}
          />
          <DetailSheet
            title="Details"
            open={detailOpen}
            onOpenChange={setDetailOpen}
          >
            The host owns selection and content.
          </DetailSheet>
        </DocsDemo>
        <p>
          WorkspaceTabs uses arrow, Home and End keys. DetailSheet shares
          Dialog’s focus and Escape contract. ResponsiveNavRail takes mobileOpen
          and onMobileOpenChange, showing a navigation drawer below 768px.
        </p>
      </DocsSection>
      <DocsSection id="split-layout" title="Resizable workspace layout">
        <DocsDemo code={`import { WorkspaceSplit } from '@nebula/tint/shell'

<WorkspaceSplit size={toolsWidth} onSizeChange={setToolsWidth}
  minSize={120} maxSize={320} label="Resize tools"
  first={<Tools />} second={<Canvas />} />`}>
          <WorkspaceSplit size={toolsWidth} onSizeChange={setToolsWidth}
            minSize={120} maxSize={320} label="Resize tools" style={{height: 220}}
            first={<div className="bg-tint-panel p-4">Domain tools</div>}
            second={<div className="bg-tint-surface p-4">Workspace canvas</div>} />
        </DocsDemo>
        <p>
          Nest WorkspaceSplit to compose sidebars, inspectors and bottom docks.
          The host owns sizes, workspace identity, storage and domain content.
          Set direction="vertical" for stacked panes and primary="second" for
          a fixed bottom or right pane. Size, minSize and maxSize are pixels;
          give the container enough room for its fixed pane and a 5px separator.
          Each pane scrolls when its content exceeds the available space.
        </p>
        <p>
          Drag a separator or focus it and use the arrow keys (10px), Shift with
          arrows (50px), Home (minimum), or End (maximum). Layout restoration
          updates controlled sizes without remounting pane content.
        </p>
      </DocsSection>
      <DocsFooter />
    </DocsPage>
  );
}

// src/docs/ShellDoc.svelte
<script lang="ts">
  import {
    CommandPalette, StatusBar, WorkspaceHeader, WorkspaceSplit, WorkspaceTabs,
    type CommandPaletteItem, type WorkspaceTab,
  } from '../svelte'
  import DocPage from './svelte/DocPage.svelte'
  import type { ApiRow } from './svelte/types'

  const tabs: WorkspaceTab[] = [
    { id: 'overview', label: 'Overview' },
    { id: 'history', label: 'History' },
  ]
  const commands: CommandPaletteItem[] = [
    { id: 'open', label: 'Open collection', description: 'View the current collection' },
    { id: 'share', label: 'Share collection', description: 'Copy an invitation' },
  ]
  let tab = $state('overview')
  let splitSize = $state(230)
  let paletteOpen = $state(false)
  let query = $state('')
  let action = $state('none')
  const api: ApiRow[] = [
    { prop: 'AppShell', type: 'nav / header / aside / status / children', description: 'Container-aware application frame with rail or top navigation.' },
    { prop: 'NavRail / ResponsiveNavRail / TopNav', type: 'groups / activeId / callbacks', description: 'Host-supplied navigation with compact and drawer presentations.' },
    { prop: 'WorkspaceHeader', type: 'title / subtitle / breadcrumbs / actions', description: 'Workspace heading and action slot.' },
    { prop: 'WorkspaceTabs', type: 'tabs / value / onChange / label', description: 'Controlled tab navigation with arrow, Home, and End keys.' },
    { prop: 'WorkspaceSplit', type: 'size / onSizeChange / first / second', description: 'Host-owned pane size with keyboard and pointer resizing.' },
    { prop: 'CommandPalette', type: 'open / query / items / onSelect', description: 'Controlled searchable command dialog.' },
    { prop: 'StatusBar', type: 'items / connection', description: 'Readable application state and connection copy.' },
  ]
  const usage = `import { WorkspaceHeader, WorkspaceSplit, WorkspaceTabs } from '@nebula/tint/shell'

let selected = $state('overview')
let inspectorWidth = $state(240)

<WorkspaceHeader title="Collection" subtitle="12 tracks" />
<WorkspaceTabs tabs={tabs} value={selected}
  onChange={(id) => selected = id} label="Collection views" />

{#snippet main()}<p>Collection rows</p>{/snippet}
{#snippet inspector()}<p>Inspector</p>{/snippet}
<WorkspaceSplit size={inspectorWidth}
  onSizeChange={(size) => inspectorWidth = size}
  first={main} second={inspector} label="Resize inspector" />`
</script>

{#snippet first()}
  <div class="pane"><strong>{tab === 'overview' ? 'Collection overview' : 'Recent activity'}</strong><p>Move the separator with arrow keys.</p></div>
{/snippet}

{#snippet second()}
  <div class="pane"><strong>Inspector</strong><p>Width: {splitSize}px</p></div>
{/snippet}

<DocPage title="Shell and Workspace" description="Responsive app chrome, controlled workspace navigation, pane sizing, and command search. State stays with the host." importPath="@nebula/tint/shell" {usage} {api} accessibility="Workspace tabs use tablist, tab, and tabpanel roles. The split separator reports its value and responds to keyboard arrows, Home, and End. CommandPalette is a labelled modal dialog with focus handling, listbox navigation, and Escape dismissal. Status copy remains readable without color.">
  <div class="shell-demo">
    <WorkspaceHeader title="Collection" subtitle="12 tracks" breadcrumbs={[{ label: 'Library', href: '#/components/table' }, { label: 'Collection' }]} />
    <WorkspaceTabs {tabs} value={tab} onChange={(next) => tab = next} label="Collection views" />
    <WorkspaceSplit size={splitSize} minSize={140} maxSize={350} onSizeChange={(next) => splitSize = next} label="Resize inspector" {first} {second} />
    <StatusBar items={[{ id: 'saved', label: 'Saved', tone: 'success' }]} connection={{ state: 'connected', label: 'Connected' }} />
  </div>
  <div class="command-demo">
    <button type="button" onclick={() => paletteOpen = true}>Open command palette</button>
    <span aria-live="polite">Selected command: {action}</span>
  </div>
  <CommandPalette open={paletteOpen} onOpenChange={(next) => paletteOpen = next} {query} onQueryChange={(next) => query = next} items={commands} onSelect={(id) => action = id} />
</DocPage>

<style>
  .shell-demo { display: grid; grid-template-rows: auto auto minmax(13rem, 1fr) auto; height: 24rem; overflow: hidden; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); }
  .pane { padding: 1rem; color: var(--tint-ink); }
  .pane p { color: var(--tint-muted); font-size: .8rem; }
  .command-demo { display: flex; align-items: center; flex-wrap: wrap; gap: 1rem; margin-top: 1rem; color: var(--tint-muted); font-size: .84rem; }
  .command-demo button { min-height: 2.5rem; border: 1px solid var(--tint-border-strong); border-radius: var(--tint-radius-sm); padding: .5rem .8rem; background: var(--tint-panel); color: var(--tint-ink); cursor: pointer; font: inherit; }
  .command-demo button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
</style>
