// src/components/surface/Surface.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { cn } from '../../lib/utils'

export type SurfaceTone = 'default' | 'subtle' | 'accent' | 'danger'
export type SurfaceElevation = 'none' | 'sm' | 'md' | 'lg'

export type SurfaceProps = HTMLAttributes<HTMLElement> & {
  as?: 'div' | 'section' | 'article' | 'aside'
  tone?: SurfaceTone
  elevation?: SurfaceElevation
  interactive?: boolean
  selected?: boolean
}

const TONE: Record<SurfaceTone, string> = {
  default: 'border-tint-border bg-tint-panel text-tint-ink',
  subtle: 'border-tint-border bg-tint-surface text-tint-ink',
  accent: 'border-tint-accent/40 bg-tint-accent-soft text-tint-ink',
  danger: 'border-tint-danger/40 bg-tint-danger-soft text-tint-danger-ink',
}

const ELEVATION: Record<SurfaceElevation, string> = {
  none: '', sm: 'shadow-sm', md: 'shadow-md', lg: 'shadow-lg',
}

export function Surface({
  as: Component = 'div',
  tone = 'default',
  elevation = 'none',
  interactive = false,
  selected = false,
  className,
  ...props
}: SurfaceProps) {
  return (
    <Component
      data-tint-surface=""
      data-tone={tone}
      data-elevation={elevation}
      data-interactive={interactive || undefined}
      data-selected={selected || undefined}
      className={cn(
        'rounded-xl border', TONE[tone], ELEVATION[elevation],
        interactive && 'transition hover:bg-tint-surface focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent',
        selected && 'ring-2 ring-tint-accent', className,
      )}
      {...props}
    />
  )
}

export type CardProps = SurfaceProps & {
  header?: ReactNode
  footer?: ReactNode
  actions?: ReactNode
  bodyClassName?: string
}

export function Card({ header, footer, actions, children, bodyClassName, ...props }: CardProps) {
  return (
    <Surface as="article" data-tint-card="" {...props}>
      {header || actions ? (
        <header className="flex items-start justify-between gap-3 border-b border-tint-border px-4 py-3">
          <div className="min-w-0 flex-1">{header}</div>
          {actions ? <div className="shrink-0">{actions}</div> : null}
        </header>
      ) : null}
      <div className={cn('px-4 py-3', bodyClassName)}>{children}</div>
      {footer ? <footer className="border-t border-tint-border px-4 py-3">{footer}</footer> : null}
    </Surface>
  )
}

// src/svelte/components/surface/Surface.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import type { SurfaceTone, SurfaceElevation, SurfaceDensity } from './types'

  type Props = Omit<HTMLAttributes<HTMLElement>, 'children'> & {
    as?: 'div' | 'section' | 'article' | 'aside'
    tone?: SurfaceTone
    elevation?: SurfaceElevation
    density?: SurfaceDensity
    interactive?: boolean
    selected?: boolean
    /** Clip children to the rounded border (used by Panel). */
    clip?: boolean
    children?: Snippet
  }

  let {
    as = 'div',
    tone = 'default',
    elevation = 'none',
    density = 'default',
    interactive = false,
    selected = false,
    clip = false,
    children,
    class: className,
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={as}
  {...rest}
  class={['tint-surface', className]}
  data-tint-surface=""
  data-tone={tone}
  data-elevation={elevation}
  data-density={density}
  data-interactive={interactive || undefined}
  data-selected={selected || undefined}
  data-clip={clip || undefined}
>
  {@render children?.()}
</svelte:element>

<style>
  .tint-surface {
    border: 1px solid var(--tint-border);
    border-radius: var(--tint-radius-lg);
    background: var(--tint-panel);
    color: var(--tint-ink);
  }
  .tint-surface[data-tone='subtle'] {
    background: var(--tint-surface);
  }
  .tint-surface[data-tone='accent'] {
    border-color: color-mix(in srgb, var(--tint-accent) 40%, transparent);
    background: var(--tint-accent-soft);
  }
  .tint-surface[data-tone='danger'] {
    border-color: color-mix(in srgb, var(--tint-danger) 40%, transparent);
    background: var(--tint-danger-soft);
    color: var(--tint-danger-ink);
  }
  .tint-surface[data-elevation='sm'] {
    box-shadow: 0 1px 2px var(--tint-shadow-color);
  }
  .tint-surface[data-elevation='md'] {
    box-shadow: 0 4px 10px -2px var(--tint-shadow-color);
  }
  .tint-surface[data-elevation='lg'] {
    box-shadow: 0 12px 24px -6px var(--tint-shadow-color);
  }
  .tint-surface[data-clip] {
    overflow: hidden;
  }
  .tint-surface[data-interactive] {
    transition: background-color var(--tint-motion-fast) var(--tint-ease);
  }
  .tint-surface[data-interactive]:hover {
    background: var(--tint-surface);
  }
  .tint-surface[data-interactive]:focus-visible {
    outline: var(--tint-focus-width) solid var(--tint-focus);
    outline-offset: var(--tint-focus-offset);
  }
  .tint-surface[data-selected] {
    box-shadow: 0 0 0 2px var(--tint-focus);
  }
</style>
