// src/components/audio-player/AudioPlayer.tsx
import { Music2, Pause, Play, SkipBack, SkipForward } from 'lucide-react'
import { motion } from 'motion/react'
import { useEffect, useRef, useState } from 'react'
import { cn } from '../../lib/utils'
import { Icon, Spinner } from '../icon'
import { formatTime, Slider, VolumeControl } from '../media'

export type AudioPlayerProps = {
  /** Audio source URL. An object URL from a recording works as well as a remote file. */
  src: string
  /** Accessible name and fallback track title. */
  label: string
  /** Track title. Falls back to `label`. */
  title?: string
  /** Optional artist, speaker, or source shown above the title. */
  artist?: string
  /** Optional square artwork URL. A themed placeholder is rendered when omitted. */
  artwork?: string
  /** Artwork alternative text. Keep empty when the image only repeats the track metadata. */
  artworkAlt?: string
  /** Known duration, shown before metadata loads so the row does not jump. */
  duration?: number
  /** Decorative amplitude samples, drawn behind the scrubber. */
  waveform?: readonly number[]
  /** Enables the reference design's offset shadow. Disabled by default. */
  shadow?: boolean
  className?: string
  onPlay?: () => void
  onPause?: () => void
  /** Adds a previous-track control. Omit the callback to omit the control. */
  onPrevious?: () => void
  /** Adds a next-track control. Omit the callback to omit the control. */
  onNext?: () => void
}

/**
 * A compact, container-responsive audio player.
 *
 * Playback state lives here rather than in props, matching `VideoPlayer`: it is
 * media-element state the host has no reason to drive. The component responds
 * to the width of its own slot, so the same instance can live in a full-width
 * media rail or a narrow chat bubble without viewport-specific JavaScript.
 */
export function AudioPlayer({
  src,
  label,
  title = label,
  artist,
  artwork,
  artworkAlt = '',
  duration: durationHint,
  waveform,
  shadow = false,
  className,
  onPlay,
  onPause,
  onPrevious,
  onNext,
}: AudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement>(null)
  const [playing, setPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(durationHint ?? 0)
  const [volume, setVolume] = useState(1)
  const [muted, setMuted] = useState(false)
  const [buffering, setBuffering] = useState(false)
  const [failed, setFailed] = useState(false)

  // A new source is a new clip: drop the old clip's progress and error state.
  useEffect(() => {
    setPlaying(false)
    setCurrentTime(0)
    setDuration(durationHint ?? 0)
    setBuffering(false)
    setFailed(false)
  }, [src, durationHint])

  const seek = (percentage: number) => {
    const audio = audioRef.current
    if (!audio || !Number.isFinite(duration) || duration <= 0) return
    const next = (percentage / 100) * duration
    audio.currentTime = next
    setCurrentTime(next)
  }

  const toggle = () => {
    const audio = audioRef.current
    if (!audio || failed) return
    if (!audio.paused) {
      audio.pause()
      return
    }
    // `play()` rejects on autoplay policy or a bad source; either way the UI
    // must not be left claiming it is playing.
    void Promise.resolve(audio.play()).catch(() => {
      setBuffering(false)
      setFailed(true)
    })
  }

  const progress = duration > 0 ? Math.min((currentTime / duration) * 100, 100) : 0
  const remaining = duration > 0 ? Math.max(duration - currentTime, 0) : 0

  const changeVolume = (next: number) => {
    const level = next / 100
    setVolume(level)
    setMuted(level === 0)
    if (audioRef.current) {
      audioRef.current.volume = level
      audioRef.current.muted = level === 0
    }
  }

  const toggleMute = () => {
    const next = !muted
    setMuted(next)
    if (audioRef.current) audioRef.current.muted = next
  }

  return (
    <div
      data-tint-audio-player=""
      data-shadow={shadow ? 'offset' : undefined}
      className={cn('w-full max-w-[42.5rem]', className)}
    >
      <audio
        ref={audioRef}
        src={src}
        preload="metadata"
        aria-label={label}
        onLoadedMetadata={(event) => {
          const next = event.currentTarget.duration
          if (Number.isFinite(next)) setDuration(next)
        }}
        onDurationChange={(event) => {
          const next = event.currentTarget.duration
          if (Number.isFinite(next)) setDuration(next)
        }}
        onTimeUpdate={(event) => setCurrentTime(event.currentTarget.currentTime)}
        onPlay={() => {
          setPlaying(true)
          setBuffering(false)
          onPlay?.()
        }}
        onPause={() => {
          setPlaying(false)
          setBuffering(false)
          onPause?.()
        }}
        onEnded={() => {
          setPlaying(false)
          setCurrentTime(0)
        }}
        onWaiting={() => setBuffering(true)}
        onPlaying={() => setBuffering(false)}
        onCanPlay={() => setBuffering(false)}
        onError={() => {
          setBuffering(false)
          setFailed(true)
          setPlaying(false)
        }}
      />

      <div
        data-audio-surface=""
        className="relative flex min-h-[5.25rem] min-w-0 items-center gap-5 rounded-lg border border-tint-border-strong px-4 py-3 text-tint-ink backdrop-blur-xl"
      >
        <div
          data-audio-artwork=""
          className="grid size-14 shrink-0 place-items-center overflow-hidden rounded-sm border border-tint-border-strong bg-tint-surface"
        >
          {artwork ? (
            <img src={artwork} alt={artworkAlt} className="size-full object-cover" />
          ) : (
            <div className="grid size-full place-items-center bg-[linear-gradient(145deg,var(--tint-accent-soft),var(--tint-surface))] text-tint-accent">
              <Icon icon={Music2} size="xl" />
            </div>
          )}
        </div>

        <div data-audio-transport="" className="flex shrink-0 items-center gap-2.5">
          {onPrevious ? (
            <motion.button
              type="button"
              data-audio-previous=""
              whileHover={{ scale: 1.08 }}
              whileTap={{ scale: 0.94 }}
              onClick={onPrevious}
              aria-label={`Previous track before ${title}`}
              className="inline-flex size-8 items-center justify-center rounded-sm text-tint-ink transition-colors hover:bg-tint-accent-soft hover:text-tint-accent focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
            >
              <Icon icon={SkipBack} size="lg" />
            </motion.button>
          ) : null}

          <motion.button
            type="button"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={toggle}
            disabled={failed}
            aria-label={playing ? `Pause ${label}` : `Play ${label}`}
            className="inline-flex size-9 shrink-0 items-center justify-center rounded-sm border border-tint-border-strong bg-tint-panel text-tint-ink transition-colors hover:border-tint-ink hover:bg-tint-ink hover:text-tint-panel focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent disabled:cursor-not-allowed disabled:opacity-40"
          >
            {buffering ? (
              <Spinner size="sm" />
            ) : (
              <Icon
                icon={playing ? Pause : Play}
                size="sm"
                className={playing ? undefined : 'translate-x-px'}
              />
            )}
          </motion.button>

          {onNext ? (
            <motion.button
              type="button"
              data-audio-next=""
              whileHover={{ scale: 1.08 }}
              whileTap={{ scale: 0.94 }}
              onClick={onNext}
              aria-label={`Next track after ${title}`}
              className="inline-flex size-8 items-center justify-center rounded-sm text-tint-ink transition-colors hover:bg-tint-accent-soft hover:text-tint-accent focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
            >
              <Icon icon={SkipForward} size="lg" />
            </motion.button>
          ) : null}
        </div>

        <span
          data-audio-divider=""
          aria-hidden="true"
          className="h-12 w-px shrink-0 bg-tint-border-strong"
        />

        <div data-audio-content="" className="flex min-w-0 flex-1 flex-col justify-center gap-2">
          {failed ? (
            <p role="alert" className="m-0 truncate text-xs text-tint-danger-ink">
              This audio could not be played.
            </p>
          ) : (
            <>
              <div data-audio-meta="" className="flex min-w-0 items-baseline gap-2">
                {artist ? (
                  <span
                    data-audio-artist=""
                    className="max-w-[45%] shrink-0 truncate text-[10px] font-medium tracking-[0.14em] text-tint-muted uppercase"
                  >
                    {artist}
                  </span>
                ) : null}
                <span className="min-w-0 truncate font-serif text-base leading-none italic tracking-tight text-tint-ink">
                  {title}
                </span>
              </div>

              <div className="flex min-w-0 items-center gap-3">
                <span
                  data-audio-time="elapsed"
                  className="w-8 shrink-0 font-mono text-[11px] tracking-wide tabular-nums text-tint-muted"
                >
                  {formatTime(currentTime)}
                </span>

                <div className="relative min-w-12 flex-1 py-2">
                  {waveform?.length ? <Waveform samples={waveform} progress={progress} /> : null}
                  <Slider
                    value={progress}
                    onChange={seek}
                    aria-label={`Seek ${label}`}
                    showThumb
                    fillClassName="bg-tint-accent"
                    thumbClassName="bg-tint-ink"
                    className="h-px text-tint-ink"
                  />
                </div>

                <span
                  data-audio-time="remaining"
                  className="w-10 shrink-0 text-right font-mono text-[11px] tracking-wide tabular-nums text-tint-muted"
                >
                  {duration > 0 ? `-${formatTime(remaining)}` : '0:00'}
                </span>
              </div>
            </>
          )}
        </div>

        <span
          data-audio-divider=""
          aria-hidden="true"
          className="h-12 w-px shrink-0 bg-tint-border-strong"
        />

        <div data-audio-volume="" className="shrink-0">
          <VolumeControl
            volume={muted ? 0 : volume}
            isMuted={muted}
            onVolumeChange={changeVolume}
            onToggleMute={toggleMute}
            tone="surface"
          />
        </div>
      </div>
    </div>
  )
}

/** Decorative amplitude bars behind the real slider control. */
function Waveform({ samples, progress }: { samples: readonly number[]; progress: number }) {
  const peak = Math.max(...samples, 1)

  return (
    <div
      aria-hidden="true"
      className="pointer-events-none absolute inset-x-0 top-1/2 flex h-4 -translate-y-1/2 items-center gap-px opacity-45"
    >
      {samples.map((amplitude, index) => {
        const played = (index / samples.length) * 100 <= progress
        return (
          <span
            key={index}
            className={cn(
              'min-h-px flex-1 rounded-full',
              played ? 'bg-tint-accent' : 'bg-tint-border-strong',
            )}
            style={{ height: `${Math.max(0, Math.min(amplitude / peak, 1)) * 100}%` }}
          />
        )
      })}
    </div>
  )
}

// src/svelte/components/media/AudioPlayer.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Pause, Play, SkipBack, SkipForward } from '@lucide/svelte'
  import { clampUnit, formatTime, playbackProgress, remainingTime } from '../../../core/media/model'
  import { MediaTransport, type MediaTransportSnapshot } from '../../../core/media/transport'
  import Icon from '../icon/Icon.svelte'
  import Spinner from '../icon/Spinner.svelte'
  import MediaPlaceholder from './MediaPlaceholder.svelte'
  import MediaScrubber from './MediaScrubber.svelte'
  import VolumeControl from './VolumeControl.svelte'
  import type { MediaPlayerAudioProps } from './playerTypes'

  let {
    src, label, title, duration: durationHint, waveform, shadow = false, size,
    class: className, onPlay, onPause, onPrevious, onNext,
    artist, artwork, artworkAlt = '', playing: playingOverride, playbackNonce,
    remote, onEnded,
  }: MediaPlayerAudioProps = $props()
  const transport = new MediaTransport()
  let root = $state<HTMLDivElement>(null!)
  let audio = $state<HTMLAudioElement>(null!)
  let mounted = $state(false)
  let snapshot: MediaTransportSnapshot = $state(transport.snapshot)
  let failedArtwork = $state<{ src: string; artwork: string }>()
  let accentColor = $state('#0f6e56')
  let lastAudibleVolume = 1
  let previous: { src: string; durationHint?: number; playing?: boolean; nonce?: number } | undefined
  let previouslyRemote = false
  let remotePlaying: boolean | undefined
  let remoteVolume: number | undefined

  let playing = $derived(remote?.playing ?? snapshot.playing)
  let currentTime = $derived(remote?.currentTime ?? snapshot.currentTime)
  let duration = $derived(remote?.duration ?? snapshot.duration)
  let volume = $derived(remote?.volume ?? snapshot.volume)
  let muted = $derived(remote?.muted ?? snapshot.muted)
  let progress = $derived(playbackProgress(currentTime, duration))
  let remaining = $derived(remainingTime(currentTime, duration))

  $effect(() => { transport.setCallbacks({ onPlay, onPause, onEnded }) })

  $effect(() => {
    if (!mounted) return
    if (remote) { previouslyRemote = true; return }
    const changed = previouslyRemote || !previous || previous.src !== src || previous.durationHint !== durationHint
    if (changed) transport.reset(durationHint)
    const newNonce = playbackNonce !== undefined && playbackNonce !== 0 && playbackNonce !== previous?.nonce
    if (newNonce || (playingOverride === true && (changed || previous?.playing !== playingOverride))) transport.playFromStart()
    else if (playingOverride === false && (changed || previous?.playing !== playingOverride)) transport.pause()
    previous = { src, durationHint, playing: playingOverride, nonce: playbackNonce }
    previouslyRemote = false
  })

  $effect(() => {
    if (!mounted || !remote) { remotePlaying = undefined; remoteVolume = undefined; return }
    const level = clampUnit(remote.volume)
    if (level !== remoteVolume) {
      audio.volume = level
      if (level > 0) lastAudibleVolume = level
      remoteVolume = level
    }
    if (remote.playing !== remotePlaying) {
      if (remote.playing) startNetworkSink()
      else if (!audio.paused) audio.pause()
      remotePlaying = remote.playing
    }
  })

  function startNetworkSink() {
    try { void Promise.resolve(audio.play()).catch(() => undefined) } catch { /* User gesture can unlock it later. */ }
  }

  function toggle() {
    if (!remote) { transport.toggle(); return }
    if (remote.playing) { audio.pause(); remote.onPause() }
    else { startNetworkSink(); remote.onPlay() }
  }

  function seek(percentage: number) {
    if (remote) { if (remote.duration > 0) remote.onSeek(percentage / 100 * remote.duration) }
    else transport.seek(percentage)
  }

  function changeVolume(percentage: number) {
    if (!remote) { transport.changeVolume(percentage); return }
    const level = clampUnit(percentage / 100)
    audio.volume = level
    if (level > 0) lastAudibleVolume = level
    remote.onVolumeChange(level)
  }

  function toggleMute() {
    if (!remote) { transport.toggleMute(); return }
    remote.onVolumeChange(muted || volume === 0 ? lastAudibleVolume : 0)
  }

  onMount(() => {
    const unsubscribe = transport.subscribe((next) => { snapshot = next })
    const detach = transport.attach(audio)
    mounted = true
    const resolveAccent = () => {
      const value = getComputedStyle(root).getPropertyValue('--tint-accent').trim()
      if (value) accentColor = value
    }
    resolveAccent()
    const observer = new MutationObserver(resolveAccent)
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme', 'data-scheme'] })
    const scheme = typeof matchMedia === 'function' ? matchMedia('(prefers-color-scheme: dark)') : undefined
    scheme?.addEventListener('change', resolveAccent)
    return () => { mounted = false; scheme?.removeEventListener('change', resolveAccent); observer.disconnect(); detach(); unsubscribe() }
  })
</script>

<div
  bind:this={root}
  data-tint-media-player=""
  data-kind="audio"
  data-size={size}
  data-shadow={shadow ? 'offset' : undefined}
  class={['tint-audio-player', className].filter(Boolean).join(' ')}
>
  <audio bind:this={audio} {src} preload="metadata" aria-label={label}></audio>
  <div data-media-surface-wrap="" class="surface-wrap">
    <div data-media-surface="" class="artwork">
      {#if artwork && !(failedArtwork?.src === src && failedArtwork?.artwork === artwork)}
        <img src={artwork} alt={artworkAlt} onerror={() => failedArtwork = { src, artwork }} />
      {:else}
        <MediaPlaceholder />
      {/if}
    </div>
    <div data-media-bar="" class="bar">
      {#if snapshot.failed && !remote}
        <p role="alert" class="error">This audio could not be played.</p>
      {:else}
        <div data-media-transport="" class="transport">
          {#if onPrevious}
            <button type="button" data-media-previous="" aria-label={`Previous track before ${title ?? label}`} onclick={onPrevious}><Icon icon={SkipBack} size="lg" /></button>
          {/if}
          <button type="button" class="play" aria-label={playing ? `Pause ${title ?? label}` : `Play ${title ?? label}`} onclick={toggle} disabled={snapshot.failed && !remote}>
            {#if snapshot.buffering && !remote}<Spinner size="sm" />{:else}<Icon icon={playing ? Pause : Play} size="sm" />{/if}
          </button>
          {#if onNext}
            <button type="button" data-media-next="" aria-label={`Next track after ${title ?? label}`} onclick={onNext}><Icon icon={SkipForward} size="lg" /></button>
          {/if}
        </div>
        <span data-media-divider="" class="divider" aria-hidden="true"></span>
        <div data-media-content="" class="content">
          <div class="meta">
            {#if artist}<span data-media-artist="" class="artist">{artist}</span>{/if}
            <span class="title">{title ?? label}</span>
          </div>
          <div class="timeline">
            <span data-media-time="elapsed" class="time">{formatTime(currentTime)}</span>
            <MediaScrubber {progress} onSeek={seek} {waveform} color={accentColor} {label} tone="surface" />
            <span data-media-time="remaining" class="time remaining">{duration > 0 ? `-${formatTime(remaining)}` : '0:00'}</span>
          </div>
        </div>
        <span data-media-divider="" class="divider" aria-hidden="true"></span>
        <div data-media-volume="" class="volume"><VolumeControl {volume} isMuted={muted} onVolumeChange={changeVolume} onToggleMute={toggleMute} tone="surface" /></div>
      {/if}
    </div>
  </div>
</div>

<style>
  .tint-audio-player { width: 100%; max-width: 56rem; }
  .surface-wrap { position: relative; display: flex; min-width: 0; flex-direction: column; gap: .75rem; padding: .75rem; border: 1px solid var(--tint-border-strong); border-radius: var(--tint-radius-lg); background: var(--tint-panel); color: var(--tint-ink); }
  .artwork { position: relative; width: 100%; flex: none; overflow: hidden; border-radius: var(--tint-radius-sm); background: var(--tint-surface); }
  .artwork img { width: 100%; height: 100%; object-fit: cover; }
  .bar { display: flex; min-width: 0; align-items: center; gap: 1.25rem; }
  .transport { display: flex; flex: none; align-items: center; gap: .625rem; }
  button { display: inline-grid; width: 2rem; height: 2rem; flex: none; place-items: center; border: 0; border-radius: var(--tint-radius-sm); background: transparent; color: var(--tint-ink); cursor: pointer; }
  button:hover { background: var(--tint-accent-soft); color: var(--tint-accent); }
  button:focus-visible { outline: 2px solid var(--tint-accent); outline-offset: 2px; }
  button:disabled { cursor: not-allowed; opacity: .4; }
  .play { width: 2.25rem; height: 2.25rem; border: 1px solid var(--tint-border-strong); background: var(--tint-panel); }
  .play:hover { border-color: var(--tint-ink); background: var(--tint-ink); color: var(--tint-panel); }
  .divider { width: 1px; height: 3rem; flex: none; background: var(--tint-border-strong); }
  .content { display: flex; min-width: 0; flex: 1; flex-direction: column; justify-content: center; gap: .5rem; }
  .meta { display: flex; min-width: 0; align-items: baseline; gap: .5rem; }
  .artist { max-width: 45%; flex: none; overflow: hidden; color: var(--tint-muted); font-size: .625rem; font-weight: 500; letter-spacing: .14em; text-overflow: ellipsis; text-transform: uppercase; white-space: nowrap; }
  .title { min-width: 0; overflow: hidden; color: var(--tint-ink); font-size: 1rem; font-weight: 500; letter-spacing: -.02em; line-height: 1; text-overflow: ellipsis; white-space: nowrap; }
  .timeline { display: flex; min-width: 0; align-items: center; gap: .75rem; }
  .time { width: 2rem; flex: none; color: var(--tint-muted); font-family: var(--font-mono); font-size: .6875rem; font-variant-numeric: tabular-nums; }
  .remaining { width: 2.5rem; text-align: right; }
  .volume { flex: none; }
  .error { margin: 0; overflow: hidden; color: var(--tint-danger-ink); font-size: var(--tint-font-size-xs); text-overflow: ellipsis; white-space: nowrap; }
</style>
