// src/components/media-player/MediaScrubber.tsx
import { useMemo, useState, type PointerEvent } from 'react'
import { cn } from '../../lib/utils'
import { Slider, Waveform } from '../media'

export type MediaScrubberProps = {
  /** Playback position, `0..100` — matches `Slider`. */
  progress: number
  /** Called with the seek target, `0..100`. */
  onSeek: (percentage: number) => void
  /** Raw amplitude samples, any scale. Normalized to `0..1` internally. */
  waveform?: readonly number[]
  /** A literal, canvas-parseable color for the waveform's played region. */
  color: string
  /** Feeds `Slider`'s `aria-label` as `Seek {label}`. */
  label: string
  className?: string
  /** Height class for the waveform band. Defaults to the `md`/`lg` size. */
  waveformClassName?: string
  tone?: 'surface' | 'chrome'
}

/**
 * Internal composition of `Waveform` behind `Slider`, used at every size
 * tier. `Slider` stays the sole keyboard-accessible seek control; the canvas
 * is a pointer-only enhancement that shares the same `onSeek` callback, so
 * both stay in sync. Not exported from the package — `MediaPlayer` is the
 * only consumer.
 */
export function MediaScrubber({
  progress,
  onSeek,
  waveform,
  color,
  label,
  className,
  waveformClassName,
  tone = 'surface',
}: MediaScrubberProps) {
  const [hoverProgress, setHoverProgress] = useState<number | null>(null)

  const peaks = useMemo(() => {
    if (!waveform?.length) return undefined
    const peak = Math.max(...waveform, 1)
    return waveform.map((amplitude) => Math.min(Math.max(amplitude / peak, 0), 1))
  }, [waveform])

  const handlePointerMove = (event: PointerEvent<HTMLDivElement>) => {
    const rect = event.currentTarget.getBoundingClientRect()
    if (rect.width === 0) return
    setHoverProgress(Math.min(Math.max((event.clientX - rect.left) / rect.width, 0), 1))
  }

  return (
    <div className={cn('relative min-w-12 flex-1 py-2', className)}>
      {peaks ? (
        <div
          className={cn('absolute inset-x-0 top-1/2 h-4 -translate-y-1/2', waveformClassName)}
          onPointerMove={handlePointerMove}
          onPointerLeave={() => setHoverProgress(null)}
        >
          <Waveform
            peaks={peaks}
            progress={progress / 100}
            hoverProgress={hoverProgress}
            color={color}
            onSeek={(p) => onSeek(p * 100)}
          />
        </div>
      ) : null}
      <Slider
        value={progress}
        onChange={onSeek}
        aria-label={`Seek ${label}`}
        showThumb
        fillClassName={tone === 'chrome' ? 'bg-tint-chrome-ink' : 'bg-tint-accent'}
        thumbClassName={tone === 'chrome' ? 'bg-tint-chrome-ink' : 'bg-tint-ink'}
        className={cn('h-px', tone === 'chrome' ? 'text-tint-chrome-ink' : 'text-tint-ink')}
      />
    </div>
  )
}

// src/svelte/components/media/MediaScrubber.svelte
<script lang="ts">
  import { clampUnit, normalizePeaks } from '../../../core/media/model'
  import Slider from './Slider.svelte'
  import Waveform from './Waveform.svelte'

  type Props = {
    progress: number
    onSeek: (percentage: number) => void
    waveform?: readonly number[]
    /** Canvas-parseable, resolved color. */
    color: string
    label: string
    tone?: 'surface' | 'chrome'
    class?: string
  }
  let { progress, onSeek, waveform, color, label, tone = 'surface', class: className }: Props = $props()
  let peaks = $derived(waveform?.length ? normalizePeaks(waveform) : undefined)
  let hoverProgress = $state<number | null>(null)

  function move(event: PointerEvent) {
    const rect = (event.currentTarget as HTMLDivElement).getBoundingClientRect()
    if (rect.width > 0) hoverProgress = clampUnit((event.clientX - rect.left) / rect.width)
  }
</script>

<div class={['tint-media-scrubber', className].filter(Boolean).join(' ')} data-tone={tone}>
  {#if peaks}
    <!-- The canvas adds pointer seeking without a second keyboard stop. -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <div class="waveform" role="presentation" onpointermove={move} onpointerleave={() => hoverProgress = null}>
      <Waveform {peaks} progress={progress / 100} {hoverProgress} {color} onSeek={(p) => onSeek(p * 100)} />
    </div>
  {/if}
  <Slider value={progress} onChange={onSeek} aria-label={`Seek ${label}`} showThumb class="slider" />
</div>

<style>
  .tint-media-scrubber { position: relative; min-width: 3rem; flex: 1; padding: .5rem 0; color: var(--tint-ink); }
  .tint-media-scrubber[data-tone='chrome'] { color: var(--tint-chrome-ink); }
  .waveform { position: absolute; top: 50%; right: 0; left: 0; height: 1rem; transform: translateY(-50%); }
  :global(.tint-media-scrubber .slider) { height: 1px; }
</style>
