// src/components/video-player/Slider.tsx
import { useRef, type PointerEvent } from 'react'
import { motion } from 'motion/react'
import { cn } from '@/lib/utils'

export type SliderProps = {
  value: number
  onChange: (value: number) => void
  className?: string
  orientation?: 'horizontal' | 'vertical'
  'aria-label': string
}

export function Slider({
  value,
  onChange,
  className,
  orientation = 'horizontal',
  'aria-label': ariaLabel,
}: SliderProps) {
  const trackRef = useRef<HTMLDivElement>(null)
  const isVertical = orientation === 'vertical'

  const updateFromPointer = (clientX: number, clientY: number) => {
    const rect = trackRef.current?.getBoundingClientRect()
    if (!rect) return

    if (isVertical) {
      if (rect.height === 0) return
      const percentage = ((rect.bottom - clientY) / rect.height) * 100
      onChange(Math.min(Math.max(percentage, 0), 100))
      return
    }

    if (rect.width === 0) return
    const percentage = ((clientX - rect.left) / rect.width) * 100
    onChange(Math.min(Math.max(percentage, 0), 100))
  }

  const handlePointerDown = (event: PointerEvent<HTMLDivElement>) => {
    event.preventDefault()
    event.currentTarget.setPointerCapture(event.pointerId)
    updateFromPointer(event.clientX, event.clientY)
  }

  const handlePointerMove = (event: PointerEvent<HTMLDivElement>) => {
    if (!event.currentTarget.hasPointerCapture(event.pointerId)) return
    updateFromPointer(event.clientX, event.clientY)
  }

  return (
    <div
      ref={trackRef}
      role="slider"
      tabIndex={0}
      aria-label={ariaLabel}
      aria-orientation={orientation}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-valuenow={Math.round(value)}
      className={cn(
        'relative cursor-pointer rounded-full bg-tint-chrome-ink/20 outline-none focus-visible:ring-2 focus-visible:ring-tint-chrome-ink/60',
        isVertical ? 'h-full w-1' : 'h-1 w-full',
        className,
      )}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={(event) => event.currentTarget.releasePointerCapture(event.pointerId)}
      onKeyDown={(event) => {
        const increase =
          event.key === 'ArrowRight' ||
          event.key === 'ArrowUp' ||
          event.key === 'PageUp'
        const decrease =
          event.key === 'ArrowLeft' ||
          event.key === 'ArrowDown' ||
          event.key === 'PageDown'

        if (increase) {
          event.preventDefault()
          onChange(Math.min(value + 5, 100))
        }
        if (decrease) {
          event.preventDefault()
          onChange(Math.max(value - 5, 0))
        }
        if (event.key === 'Home') {
          event.preventDefault()
          onChange(0)
        }
        if (event.key === 'End') {
          event.preventDefault()
          onChange(100)
        }
      }}
    >
      <motion.div
        className={cn(
          'absolute rounded-full bg-tint-chrome-ink',
          isVertical ? 'right-0 bottom-0 left-0 w-full' : 'top-0 left-0 h-full',
        )}
        initial={false}
        animate={isVertical ? { height: `${value}%` } : { width: `${value}%` }}
        transition={{ type: 'spring', stiffness: 300, damping: 30 }}
      />
    </div>
  )
}

// src/svelte/components/media/Slider.svelte
<script lang="ts">
  import { clampPercent, pointerPercent } from '../../../core/media/model'

  type Props = {
    value: number
    onChange: (value: number) => void
    'aria-label': string
    orientation?: 'horizontal' | 'vertical'
    showThumb?: boolean
    class?: string
    fillClassName?: string
    thumbClassName?: string
  }

  let {
    value, onChange, 'aria-label': ariaLabel, orientation = 'horizontal',
    showThumb = false, class: className, fillClassName, thumbClassName,
  }: Props = $props()
  let track = $state<HTMLDivElement>(null!)
  let safeValue = $derived(clampPercent(value))

  function updateFromPointer(event: PointerEvent) {
    const rect = track.getBoundingClientRect()
    onChange(orientation === 'vertical'
      ? pointerPercent(event.clientY, rect.top, rect.height, 'vertical')
      : pointerPercent(event.clientX, rect.left, rect.width))
  }

  function onPointerDown(event: PointerEvent) {
    event.preventDefault()
    track.focus()
    track.setPointerCapture(event.pointerId)
    updateFromPointer(event)
  }

  function onPointerMove(event: PointerEvent) {
    if (track.hasPointerCapture(event.pointerId)) updateFromPointer(event)
  }

  function onKeydown(event: KeyboardEvent) {
    const delta = event.key === 'ArrowRight' || event.key === 'ArrowUp' ? 5
      : event.key === 'ArrowLeft' || event.key === 'ArrowDown' ? -5
      : event.key === 'PageUp' ? 5 : event.key === 'PageDown' ? -5 : 0
    if (delta) {
      event.preventDefault()
      onChange(clampPercent(safeValue + delta))
    } else if (event.key === 'Home' || event.key === 'End') {
      event.preventDefault()
      onChange(event.key === 'Home' ? 0 : 100)
    }
  }
</script>

<div
  bind:this={track}
  role="slider"
  tabindex="0"
  aria-label={ariaLabel}
  aria-orientation={orientation}
  aria-valuemin="0"
  aria-valuemax="100"
  aria-valuenow={Math.round(safeValue)}
  data-orientation={orientation}
  class={['tint-media-slider', className].filter(Boolean).join(' ')}
  onpointerdown={onPointerDown}
  onpointermove={onPointerMove}
  onpointerup={(event) => { if (track.hasPointerCapture(event.pointerId)) track.releasePointerCapture(event.pointerId) }}
  onpointercancel={(event) => { if (track.hasPointerCapture(event.pointerId)) track.releasePointerCapture(event.pointerId) }}
  onkeydown={onKeydown}
>
  <span class={['fill', fillClassName].filter(Boolean).join(' ')} style={orientation === 'vertical' ? `height:${safeValue}%` : `width:${safeValue}%`}></span>
  {#if showThumb}
    <span aria-hidden="true" class={['thumb', thumbClassName].filter(Boolean).join(' ')} style={orientation === 'vertical' ? `bottom:${safeValue}%` : `left:${safeValue}%`}></span>
  {/if}
</div>

<style>
  .tint-media-slider { position: relative; width: 100%; height: .25rem; border-radius: var(--tint-radius-full); background: color-mix(in srgb, currentColor 20%, transparent); color: var(--tint-ink); cursor: pointer; outline: none; touch-action: none; }
  .tint-media-slider[data-orientation='vertical'] { width: .25rem; height: 100%; }
  .tint-media-slider:focus-visible { outline: 2px solid var(--tint-accent); outline-offset: 4px; }
  .fill { position: absolute; top: 0; left: 0; height: 100%; border-radius: inherit; background: currentColor; transition: width var(--tint-motion-base) var(--tint-ease), height var(--tint-motion-base) var(--tint-ease); }
  [data-orientation='vertical'] .fill { top: auto; bottom: 0; width: 100%; }
  .thumb { position: absolute; top: 50%; width: .375rem; height: .75rem; border-radius: var(--tint-radius-sm); background: currentColor; transform: translate(-50%, -50%); transition: left var(--tint-motion-base) var(--tint-ease), bottom var(--tint-motion-base) var(--tint-ease); pointer-events: none; }
  [data-orientation='vertical'] .thumb { top: auto; left: 50%; width: .75rem; height: .375rem; transform: translate(-50%, 50%); }
  @media (prefers-reduced-motion: reduce) { .fill, .thumb { transition: none; } }
</style>
