// src/components/video-player/VideoPlayer.tsx
import { useEffect, useMemo, useRef, useState, type VideoHTMLAttributes } from 'react'
import { Maximize, Minimize, Pause, Play, Settings } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { cn } from '../../lib/utils'
import { Icon } from '../icon'
import { SettingsPopout, type SettingsPopoutItem } from '../settings-popout'
import { Slider, VolumeControl, formatTime } from '../media'

const DEFAULT_PLAYBACK_SPEEDS = [0.5, 1, 1.5, 2] as const

export type VideoPlayerProps = {
  src: string
  poster?: string
  className?: string
  autoHideControls?: boolean
  label?: string
  /** Visible title, shown above the timeline. Falls back to `label`. */
  title?: string
  duration?: number
  playbackSpeeds?: readonly number[]
  size?: 'sm' | 'md' | 'lg'
  shadow?: boolean
  onPlay?: () => void
  onPause?: () => void
} & Omit<VideoHTMLAttributes<HTMLVideoElement>, 'src' | 'poster' | 'className' | 'controls' | 'onPlay' | 'onPause'>

export function VideoPlayer({
  src,
  poster,
  className,
  autoHideControls = true,
  label = 'Video',
  title = label,
  duration: durationHint,
  playbackSpeeds = DEFAULT_PLAYBACK_SPEEDS,
  size,
  shadow = false,
  onPlay,
  onPause,
  ...videoProps
}: VideoPlayerProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const videoRef = useRef<HTMLVideoElement>(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const [volume, setVolume] = useState(1)
  const [progress, setProgress] = useState(0)
  const [isMuted, setIsMuted] = useState(false)
  const [playbackSpeed, setPlaybackSpeed] = useState(1)
  const [showControls, setShowControls] = useState(!autoHideControls)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [volumeOpen, setVolumeOpen] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(durationHint ?? 0)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const [failed, setFailed] = useState(false)

  useEffect(() => {
    const onFullscreenChange = () => {
      setIsFullscreen(document.fullscreenElement === containerRef.current)
    }
    document.addEventListener('fullscreenchange', onFullscreenChange)
    return () => document.removeEventListener('fullscreenchange', onFullscreenChange)
  }, [])

  const toggleFullscreen = () => {
    if (document.fullscreenElement) {
      void document.exitFullscreen()
      return
    }
    // Fullscreening the container (not the raw <video>) keeps the custom
    // control bar working — the browser's native fullscreen video UI would
    // otherwise replace it.
    void containerRef.current?.requestFullscreen()
  }

  const settingsItems = useMemo<SettingsPopoutItem[]>(
    () => playbackSpeeds.map((speed) => ({
      id: `speed-${speed}`,
      label: `${speed}x`,
      group: 'Playback speed',
      description: `Play at ${speed} times normal speed`,
    })),
    [playbackSpeeds],
  )

  useEffect(() => {
    setShowControls(!autoHideControls)
  }, [autoHideControls])

  useEffect(() => {
    setCurrentTime(0)
    setProgress(0)
    setDuration(durationHint ?? 0)
    setIsPlaying(false)
    setFailed(false)
  }, [src, durationHint])

  const updateTime = () => {
    const video = videoRef.current
    if (!video) return
    const nextDuration = Number.isFinite(video.duration) ? video.duration : duration
    if (nextDuration > 0) {
      setDuration(nextDuration)
      setProgress(Math.min((video.currentTime / nextDuration) * 100, 100))
    }
    setCurrentTime(video.currentTime)
  }

  // `play()` rejects on autoplay policy or a bad source. Left unhandled it became
  // an unhandled rejection and the chrome kept claiming the video was playing.
  const togglePlay = () => {
    const video = videoRef.current
    if (!video) return
    if (!video.paused) {
      video.pause()
      return
    }
    void Promise.resolve(video.play()).catch(() => {
      setIsPlaying(false)
      setFailed(true)
    })
  }

  const handleVolumeChange = (value: number) => {
    const video = videoRef.current
    if (!video) return
    const nextVolume = value / 100
    video.volume = nextVolume
    video.muted = nextVolume === 0
    setVolume(nextVolume)
    setIsMuted(nextVolume === 0)
  }

  const toggleMute = () => {
    const video = videoRef.current
    if (!video) return
    if (isMuted || volume === 0) {
      const restored = volume === 0 ? 1 : volume
      video.muted = false
      video.volume = restored
      setVolume(restored)
      setIsMuted(false)
    } else {
      video.muted = true
      setIsMuted(true)
    }
  }

  const handleSeek = (value: number) => {
    const video = videoRef.current
    if (!video || !Number.isFinite(video.duration) || video.duration <= 0) return
    video.currentTime = (value / 100) * video.duration
    setProgress(value)
  }

  const setSpeed = (speed: number) => {
    const video = videoRef.current
    if (!video) return
    video.playbackRate = speed
    setPlaybackSpeed(speed)
  }

  const overlayOpen = settingsOpen || volumeOpen
  const revealControls = () => { if (autoHideControls) setShowControls(true) }
  const maybeHideControls = () => { if (autoHideControls && !overlayOpen) setShowControls(false) }

  return (
    <motion.div
      ref={containerRef}
      data-tint-video-player=""
      data-size={size}
      className={cn(
        'relative mx-auto w-full rounded-lg bg-tint-chrome shadow-[0_0_20px_var(--tint-shadow-color)] backdrop-blur-sm',
        size === 'sm' ? 'max-w-xl' : size === 'md' ? 'max-w-3xl' : 'max-w-4xl',
        shadow && 'shadow-[6px_6px_0_var(--tint-shadow-color)]',
        className,
      )}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      onMouseEnter={revealControls}
      onMouseLeave={maybeHideControls}
      onFocusCapture={revealControls}
      onBlurCapture={(event) => {
        if (autoHideControls && !overlayOpen && !event.currentTarget.contains(event.relatedTarget as Node | null)) {
          setShowControls(false)
        }
      }}
    >
      {/*
        The label names the media, not an action. It used to read "Play {label}" /
        "Pause {label}", which announced the video element itself as a button —
        while the only actual way to start playback was clicking it, with no
        keyboard equivalent anywhere. The transport button in the control bar is
        now the real control; this click handler is a mouse convenience on top.
      */}
      <video
        ref={videoRef}
        className="w-full cursor-pointer rounded-lg bg-black"
        src={src}
        poster={poster}
        {...videoProps}
        aria-label={label}
        onClick={togglePlay}
        onTimeUpdate={updateTime}
        onLoadedMetadata={updateTime}
        onPlay={() => { setIsPlaying(true); onPlay?.() }}
        onPause={() => { setIsPlaying(false); onPause?.() }}
        onEnded={() => setIsPlaying(false)}
        onError={() => { setIsPlaying(false); setFailed(true) }}
      />

      <AnimatePresence>
        {showControls ? (
          <motion.div
            className="absolute bottom-3 left-1/2 z-20 flex w-2/3 max-w-xl -translate-x-1/2 flex-col gap-2 rounded-xl bg-tint-chrome px-3 pt-2.5 pb-2.5 backdrop-blur-md"
            initial={{ y: 20, opacity: 0, filter: 'blur(10px)' }}
            animate={{ y: 0, opacity: 1, filter: 'blur(0px)' }}
            exit={{ y: 20, opacity: 0, filter: 'blur(10px)' }}
            transition={{ duration: 0.45, ease: 'circInOut', type: 'spring' }}
          >
            <p className="m-0 truncate text-xs font-medium text-tint-chrome-ink/85">{title}</p>
            {failed ? (
              <p role="alert" className="m-0 truncate text-xs text-tint-danger-ink">
                This video could not be played.
              </p>
            ) : null}

            <div className="flex items-center gap-2 text-tint-chrome-ink">
              <motion.button
                type="button"
                data-video-transport=""
                whileHover={{ scale: 1.08 }}
                whileTap={{ scale: 0.94 }}
                onClick={togglePlay}
                disabled={failed}
                aria-label={isPlaying ? `Pause ${label}` : `Play ${label}`}
                className="inline-flex size-8 shrink-0 items-center justify-center rounded-md text-tint-chrome-ink transition-colors hover:bg-tint-chrome-ink/12 disabled:cursor-not-allowed disabled:opacity-40"
              >
                <Icon
                  icon={isPlaying ? Pause : Play}
                  size="sm"
                  className={isPlaying ? undefined : 'translate-x-px'}
                />
              </motion.button>
              <span className="min-w-9 text-xs tabular-nums">{formatTime(currentTime)}</span>
              <Slider value={progress} onChange={handleSeek} className="flex-1 text-tint-chrome-ink" aria-label={`Seek ${label}`} />
              <span className="min-w-9 text-right text-xs tabular-nums">{formatTime(duration)}</span>
              <div className="flex items-center gap-0.5">
                <VolumeControl
                  volume={volume}
                  isMuted={isMuted}
                  onVolumeChange={handleVolumeChange}
                  onToggleMute={toggleMute}
                  onOpenChange={(open) => { if (open) setSettingsOpen(false); setVolumeOpen(open) }}
                />
                <div className="relative">
                  <motion.button
                    type="button"
                    whileHover={{ scale: 1.08 }}
                    whileTap={{ scale: 0.94 }}
                    onClick={() => { setVolumeOpen(false); setSettingsOpen((open) => !open) }}
                    aria-label="Settings"
                    aria-haspopup="dialog"
                    aria-expanded={settingsOpen}
                    className={cn('inline-flex size-8 items-center justify-center rounded-md text-tint-chrome-ink transition-colors hover:bg-tint-chrome-ink/12', settingsOpen && 'bg-tint-chrome-ink/12')}
                  >
                    <Icon icon={Settings} size="sm" />
                  </motion.button>
                  <SettingsPopout
                    isOpen={settingsOpen}
                    onOpenChange={setSettingsOpen}
                    items={settingsItems}
                    value={`speed-${playbackSpeed}`}
                    onSelect={(id) => { const speed = Number(id.replace('speed-', '')); if (Number.isFinite(speed)) setSpeed(speed) }}
                    label="Player settings"
                    placeholder="Search settings…"
                  />
                </div>
                <motion.button
                  type="button"
                  whileHover={{ scale: 1.08 }}
                  whileTap={{ scale: 0.94 }}
                  onClick={toggleFullscreen}
                  aria-label={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
                  className="inline-flex size-8 items-center justify-center rounded-md text-tint-chrome-ink transition-colors hover:bg-tint-chrome-ink/12"
                >
                  <Icon icon={isFullscreen ? Minimize : Maximize} size="sm" />
                </motion.button>
              </div>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </motion.div>
  )
}

export default VideoPlayer

// src/svelte/components/media/VideoPlayer.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte'
  import { Maximize, Minimize, Pause, Play, Settings } from '@lucide/svelte'
  import { formatTime, playbackProgress } from '../../../core/media/model'
  import { MediaTransport, type MediaTransportSnapshot } from '../../../core/media/transport'
  import Icon from '../icon/Icon.svelte'
  import Slider from './Slider.svelte'
  import SettingsPopout from './SettingsPopout.svelte'
  import VolumeControl from './VolumeControl.svelte'
  import type { MediaPlayerVideoProps } from './playerTypes'

  type Props = Omit<MediaPlayerVideoProps, 'kind' | 'label'> & { kind?: 'video'; label?: string }
  let {
    kind: _kind, src, label = 'Video', title, poster, tracks = [], duration: durationHint,
    playbackSpeeds = [0.5, 1, 1.5, 2], autoHideControls = true,
    size, shadow = false, class: className, onPlay, onPause,
    waveform: _waveform, onPrevious: _onPrevious, onNext: _onNext,
    ...videoAttrs
  }: Props = $props()
  const transport = new MediaTransport()
  let root = $state<HTMLDivElement>(null!)
  let video = $state<HTMLVideoElement>(null!)
  let mounted = $state(false)
  let snapshot: MediaTransportSnapshot = $state(transport.snapshot)
  let showControls = $state(true)
  let settingsOpen = $state(false)
  let volumeOpen = $state(false)
  let playbackSpeed = $state(1)
  let fullscreen = $state(false)
  let theater = $state(false)
  let previousSource: { src: string; durationHint?: number } | undefined

  let playerTitle = $derived(title ?? label)
  let progress = $derived(playbackProgress(snapshot.currentTime, snapshot.duration))
  let speedItems = $derived(playbackSpeeds.map((speed) => ({
    id: `speed-${speed}`, label: `${speed}x`, group: 'Playback speed',
    description: `Play at ${speed} times normal speed`,
  })))

  $effect(() => { transport.setCallbacks({ onPlay, onPause }) })
  $effect(() => { showControls = !autoHideControls })
  $effect(() => {
    if (!mounted) return
    if (previousSource?.src !== src || previousSource.durationHint !== durationHint) {
      transport.reset(durationHint)
      previousSource = { src, durationHint }
    }
  })

  function setSpeed(speed: number) {
    video.playbackRate = speed
    playbackSpeed = speed
  }

  function revealControls() { if (autoHideControls) showControls = true }
  function maybeHideControls() { if (autoHideControls && !settingsOpen && !volumeOpen) showControls = false }

  async function toggleFullscreen() {
    if (fullscreen) {
      try { await document.exitFullscreen() } catch { /* Keep current surface. */ }
    } else if (theater) theater = false
    else {
      try {
        if (!root.requestFullscreen) throw new Error('Element fullscreen unavailable')
        await root.requestFullscreen()
      } catch { theater = true }
    }
  }

  $effect(() => {
    if (!theater || !root) return
    const restore = document.activeElement instanceof HTMLElement ? document.activeElement : null
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    void tick().then(() => { if (theater) root.focus() })
    const onKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !settingsOpen && !volumeOpen) { event.preventDefault(); theater = false; return }
      if (event.key !== 'Tab') return
      const focusable = Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled), [tabindex="0"], input:not(:disabled)'))
      const first = focusable[0]
      const last = focusable.at(-1)
      if (!first || !last) { event.preventDefault(); return }
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() }
    }
    document.addEventListener('keydown', onKeydown)
    return () => { document.removeEventListener('keydown', onKeydown); document.body.style.overflow = previousOverflow; restore?.focus() }
  })

  onMount(() => {
    const unsubscribe = transport.subscribe((next) => { snapshot = next })
    const detach = transport.attach(video)
    const onFullscreenChange = () => { fullscreen = document.fullscreenElement === root }
    document.addEventListener('fullscreenchange', onFullscreenChange)
    mounted = true
    return () => { mounted = false; document.removeEventListener('fullscreenchange', onFullscreenChange); detach(); unsubscribe() }
  })
</script>

<!-- The focusable group reveals controls when the keyboard reaches the player. -->
<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
<div
  bind:this={root}
  data-tint-video-player=""
  data-size={size}
  data-shadow={shadow ? 'offset' : undefined}
  data-fullscreen={fullscreen ? 'true' : undefined}
  data-theater={theater ? 'true' : undefined}
  role={theater ? 'dialog' : 'group'}
  aria-modal={theater ? 'true' : undefined}
  aria-label={theater ? playerTitle : `${playerTitle} player`}
  tabindex={theater ? -1 : 0}
  class={['tint-video-player', className].filter(Boolean).join(' ')}
  onpointerenter={revealControls}
  onpointerleave={maybeHideControls}
  onfocusin={revealControls}
  onfocusout={(event) => { if (!root.contains(event.relatedTarget as Node | null)) maybeHideControls() }}
>
  <video
    bind:this={video}
    {...videoAttrs}
    {src}
    {poster}
    aria-label={label}
    class="video"
    onclick={() => transport.toggle()}
  >
    {#each tracks as track (`${track.kind}:${track.srcLang}:${track.src}`)}
      <track src={track.src} kind={track.kind} srclang={track.srcLang} label={track.label} default={track.default} />
    {/each}
  </video>

  {#if showControls}
    <div class="chrome">
      <p class="title">{playerTitle}</p>
      {#if snapshot.failed}<p role="alert" class="error">This video could not be played.</p>{/if}
      <div class="controls">
        <button type="button" data-video-transport="" aria-label={snapshot.playing ? `Pause ${label}` : `Play ${label}`} onclick={() => transport.toggle()} disabled={snapshot.failed}><Icon icon={snapshot.playing ? Pause : Play} size="sm" /></button>
        <span class="time">{formatTime(snapshot.currentTime)}</span>
        <Slider value={progress} onChange={(value) => transport.seek(value)} aria-label={`Seek ${label}`} class="seek" />
        <span class="time">{formatTime(snapshot.duration)}</span>
        <VolumeControl volume={snapshot.volume} isMuted={snapshot.muted} onVolumeChange={(value) => transport.changeVolume(value)} onToggleMute={() => transport.toggleMute()} open={volumeOpen} onOpenChange={(open) => { if (open) settingsOpen = false; volumeOpen = open }} />
        <SettingsPopout isOpen={settingsOpen} onOpenChange={(open) => { if (open) volumeOpen = false; settingsOpen = open }} items={speedItems} value={`speed-${playbackSpeed}`} onSelect={(id) => { const speed = Number(id.replace('speed-', '')); if (Number.isFinite(speed)) setSpeed(speed) }} label="Player settings">
          {#snippet trigger(triggerProps)}
            <button
              id={triggerProps.id}
              type="button"
              aria-label="Settings"
              aria-haspopup={triggerProps['aria-haspopup']}
              aria-expanded={triggerProps['aria-expanded']}
              aria-controls={triggerProps['aria-controls']}
              data-tint-trigger=""
              onclick={triggerProps.onclick}
            ><Icon icon={Settings} size="sm" /></button>
          {/snippet}
        </SettingsPopout>
        <button type="button" aria-label={fullscreen || theater ? 'Exit fullscreen' : 'Enter fullscreen'} onclick={() => void toggleFullscreen()}><Icon icon={fullscreen || theater ? Minimize : Maximize} size="sm" /></button>
      </div>
    </div>
  {/if}
</div>

<style>
  .tint-video-player { position: relative; width: 100%; max-width: 56rem; margin-inline: auto; border-radius: var(--tint-radius-lg); background: var(--tint-chrome); box-shadow: 0 0 20px var(--tint-shadow-color); container-type: inline-size; }
  .tint-video-player[data-size='sm'] { max-width: 36rem; }
  .tint-video-player[data-size='md'] { max-width: 48rem; }
  .tint-video-player[data-shadow='offset'] { box-shadow: 6px 6px 0 var(--tint-shadow-color); }
  .tint-video-player:focus-visible { outline: 2px solid var(--tint-accent); outline-offset: 2px; }
  .video { display: block; width: 100%; border-radius: inherit; background: black; cursor: pointer; }
  .chrome { position: absolute; right: 17%; bottom: .75rem; left: 17%; z-index: 20; display: flex; flex-direction: column; gap: .5rem; padding: .625rem .75rem; border-radius: var(--tint-radius-lg); background: var(--tint-chrome); color: var(--tint-chrome-ink); }
  .title { margin: 0; overflow: hidden; font-size: var(--tint-font-size-xs); font-weight: 500; text-overflow: ellipsis; white-space: nowrap; }
  .error { margin: 0; color: var(--tint-danger-ink); font-size: var(--tint-font-size-xs); }
  .controls { display: flex; align-items: center; gap: .5rem; }
  .controls button { display: inline-grid; width: 2rem; height: 2rem; flex: none; place-items: center; border: 0; border-radius: var(--tint-radius-sm); background: transparent; color: inherit; cursor: pointer; }
  .controls button:hover { background: color-mix(in srgb, currentColor 12%, transparent); }
  .controls button:focus-visible { outline: 2px solid var(--tint-chrome-ink); outline-offset: 2px; }
  .controls button:disabled { cursor: not-allowed; opacity: .4; }
  .time { min-width: 2.25rem; flex: none; font-size: var(--tint-font-size-xs); font-variant-numeric: tabular-nums; }
  .time:nth-of-type(2) { text-align: right; }
  :global(.tint-video-player .seek) { min-width: 1rem; flex: 1; color: var(--tint-chrome-ink); }
  @container (max-width: 40rem) { .chrome { right: .5rem; left: .5rem; } }
</style>
