// src/components/form/FormLayout.tsx
import React, { useEffect, useId, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react'
import type { FormField, FormSchema, FormSection } from './contracts'
import {
  FormAbortError,
  appendAtPath,
  createFormSubmitEnvelope,
  defaultItemForField,
  getAtPath,
  isFormError,
  isFormFileValue,
  removeAtIndex,
  setAtPath,
  validateForm,
  type FormFileValue,
  type FormIssue,
  type FormSubmitEnvelope,
  type FormTransport,
  type FormValues,
} from './contracts'
import { FormControl } from './FormControl'
import {
  FileField,
  NumberField,
  PasswordField,
  SelectField,
  SliderField,
  TagsField,
  TextAreaField,
  TextField,
  ToggleField,
} from './inputs'

void React

export type FormLayoutProps = {
  schema: FormSchema
  values: FormValues
  onValuesChange: (values: FormValues) => void
  issues?: readonly FormIssue[]
  busy?: boolean
  disabled?: boolean
  readonly?: boolean
  error?: ReactNode
  density?: 'compact' | 'comfortable'
  columns?: 1 | 2
  submitLabel?: string
  submittingLabel?: string
  hideSubmit?: boolean
  className?: string
  transport?: FormTransport<FormValues, unknown>
  onSubmit?: (envelope: FormSubmitEnvelope<FormValues>) => void | Promise<void>
  onValidation?: (issues: readonly FormIssue[]) => void
  onSubmitError?: (error: unknown) => void
}

/**
 * Schema in, labelled fields out. The host owns `values`; this owns the
 * mapping from `FormField.kind` onto the input primitives.
 *
 * Submit builds a `FormSubmitEnvelope` and, when a `transport` is supplied,
 * runs `validate` then `submit`. Field issues resolve — they do not reject.
 */
export function FormLayout({
  schema,
  values,
  onValuesChange,
  issues: issueProp,
  busy = false,
  disabled = false,
  readonly = false,
  error,
  density = 'comfortable',
  columns = 1,
  submitLabel = 'Submit',
  submittingLabel = 'Submitting…',
  hideSubmit = false,
  className,
  transport,
  onSubmit,
  onValidation,
  onSubmitError,
}: FormLayoutProps) {
  const prefix = useId()
  const [localIssues, setLocalIssues] = useState<readonly FormIssue[]>([])
  const [submitError, setSubmitError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const submittingRef = useRef(false)
  const abortRef = useRef<AbortController | null>(null)
  const mountedRef = useRef(true)
  const issues = issueProp ?? localIssues
  const locked = busy || disabled || readonly || submitting

  useEffect(() => {
    mountedRef.current = true
    return () => {
      mountedRef.current = false
      abortRef.current?.abort()
    }
  }, [])

  const issuesByPath = useMemo(() => {
    const map = new Map<string, string>()
    for (const issue of issues) {
      if (issue.path && issue.severity === 'error' && !map.has(issue.path)) {
        map.set(issue.path, issue.message)
      }
    }
    return map
  }, [issues])

  function setPath(path: string, value: unknown) {
    onValuesChange(setAtPath(values, path, value))
  }

  function failSubmit(cause: unknown) {
    if (cause instanceof FormAbortError) return
    onSubmitError?.(cause)
    if (!mountedRef.current) return
    setSubmitError(
      isFormError(cause) || cause instanceof Error
        ? cause.message
        : 'The form could not be submitted.',
    )
  }

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (locked || submittingRef.current) return
    const result = validateForm(schema, values)
    setLocalIssues(result.issues)
    setSubmitError(null)
    onValidation?.(result.issues)
    if (!result.ok) return

    const envelope = createFormSubmitEnvelope(schema, values)
    submittingRef.current = true
    setSubmitting(true)
    void settleSubmit(envelope)
  }

  async function settleSubmit(envelope: FormSubmitEnvelope<FormValues>) {
    const controller = new AbortController()
    abortRef.current = controller
    try {
      if (transport) {
        const remote = await transport.validate(envelope, { signal: controller.signal })
        if (!remote.ok) {
          setLocalIssues(remote.issues)
          onValidation?.(remote.issues)
          return
        }
        await transport.submit(envelope, { signal: controller.signal })
      }
      await onSubmit?.(envelope)
    } catch (cause) {
      failSubmit(cause)
    } finally {
      submittingRef.current = false
      if (mountedRef.current) setSubmitting(false)
    }
  }

  const banner = error ?? submitError

  return (
    <form
      className={['tint-form', className].filter(Boolean).join(' ')}
      data-density={density}
      data-columns={columns}
      aria-busy={busy || submitting || undefined}
      onSubmit={(event) => submit(event)}
      noValidate
    >
      {schema.title ? <h2 className="tint-form-title">{schema.title}</h2> : null}
      {schema.description ? <p className="tint-form-lede">{schema.description}</p> : null}
      {banner ? (
        <div className="tint-form-banner" role="alert" aria-live="polite">
          {banner}
        </div>
      ) : null}
      {schema.sections.map((section) => (
        <FormSectionView
          key={section.id}
          section={section}
          prefix={prefix}
          values={values}
          issuesByPath={issuesByPath}
          locked={locked}
          onSetPath={setPath}
          onValuesChange={onValuesChange}
        />
      ))}
      {hideSubmit ? null : (
        <button className="tint-form-submit" type="submit" disabled={locked}>
          {busy || submitting ? submittingLabel : submitLabel}
        </button>
      )}
    </form>
  )
}

function FormSectionView({
  section,
  prefix,
  values,
  issuesByPath,
  locked,
  onSetPath,
  onValuesChange,
  pathPrefix = '',
}: {
  section: FormSection
  prefix: string
  values: FormValues
  issuesByPath: Map<string, string>
  locked: boolean
  onSetPath: (path: string, value: unknown) => void
  onValuesChange: (values: FormValues) => void
  pathPrefix?: string
}) {
  return (
    <fieldset className="tint-form-section" disabled={locked}>
      {section.title ? <legend className="tint-form-section__title">{section.title}</legend> : null}
      {section.description ? <p className="tint-form-section__description">{section.description}</p> : null}
      <div className="tint-form-fields">
        {section.fields.map((field) => {
          const path = joinPath(pathPrefix, field.name)
          return (
            <FieldView
              key={path || field.label}
              field={field}
              path={path}
              prefix={prefix}
              values={values}
              issuesByPath={issuesByPath}
              locked={locked}
              onSetPath={onSetPath}
              onValuesChange={onValuesChange}
            />
          )
        })}
      </div>
    </fieldset>
  )
}

function FieldView({
  field,
  path,
  prefix,
  values,
  issuesByPath,
  locked,
  onSetPath,
  onValuesChange,
}: {
  field: FormField
  path: string
  prefix: string
  values: FormValues
  issuesByPath: Map<string, string>
  locked: boolean
  onSetPath: (path: string, value: unknown) => void
  onValuesChange: (values: FormValues) => void
}) {
  const id = `${prefix}-${path || field.label}`.replace(/[^A-Za-z0-9_-]/g, '-')
  const error = issuesByPath.get(path)
  const raw = getAtPath(values, path)
  const shared = {
    id,
    description: field.description,
    error,
    disabled: locked,
  }

  if (field.kind === 'repeatable') {
    const items = Array.isArray(raw) ? raw : []
    return (
      <div className="tint-form-repeatable">
        <div className="tint-form-repeatable__header">
          <p className="tint-form-label">{field.label}</p>
          <button
            type="button"
            className="tint-form-repeatable__add"
            disabled={locked}
            onClick={() => onValuesChange(appendAtPath(values, path, defaultItemForField(field)))}
          >
            {field.addLabel ?? `Add ${field.label}`}
          </button>
        </div>
        {field.description ? <p className="tint-form-description">{field.description}</p> : null}
        {error ? (
          <p className="tint-form-error" role="alert">
            {error}
          </p>
        ) : null}
        <ol className="tint-form-repeatable__list">
          {items.map((item, index) => {
            const itemPath = `${path}.${index}`
            return (
              <li key={itemPath} className="tint-form-repeatable__item">
                <div className="tint-form-repeatable__item-bar">
                  <span>
                    {field.label} {index + 1}
                  </span>
                  <button
                    type="button"
                    className="tint-form-repeatable__remove"
                    disabled={locked}
                    onClick={() => onValuesChange(removeAtIndex(values, path, index))}
                  >
                    {field.removeLabel ?? 'Remove'}
                  </button>
                </div>
                {field.itemSchema ? (
                  <FormSectionView
                    section={field.itemSchema}
                    prefix={`${prefix}-${index}`}
                    values={values}
                    issuesByPath={issuesByPath}
                    locked={locked}
                    onSetPath={onSetPath}
                    onValuesChange={onValuesChange}
                    pathPrefix={itemPath}
                  />
                ) : (
                  <PrimitiveItem
                    kind={field.itemKind ?? 'textarea'}
                    id={`${id}-${index}`}
                    value={item}
                    locked={locked}
                    error={issuesByPath.get(itemPath)}
                    onChange={(next) => onSetPath(itemPath, next)}
                  />
                )}
              </li>
            )
          })}
        </ol>
      </div>
    )
  }

  return (
    <FormControl
      id={id}
      label={field.label}
      description={field.description}
      error={error}
      required={field.required}
      disabled={locked}
    >
      <KindInput
        field={field}
        shared={shared}
        raw={raw}
        locked={locked}
        onSetPath={onSetPath}
        path={path}
      />
    </FormControl>
  )
}

function KindInput({
  field,
  shared,
  raw,
  locked,
  onSetPath,
  path,
}: {
  field: FormField
  shared: { id: string; description?: string; error?: string; disabled?: boolean }
  raw: unknown
  locked: boolean
  onSetPath: (path: string, value: unknown) => void
  path: string
}) {
  switch (field.kind) {
    case 'textarea':
      return (
        <TextAreaField
          {...shared}
          value={asString(raw)}
          placeholder={field.placeholder}
          required={field.required}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'password':
      return (
        <PasswordField
          {...shared}
          value={asString(raw)}
          placeholder={field.placeholder}
          required={field.required}
          autoComplete="current-password"
          showPasswordLabel={field.showPasswordLabel}
          hidePasswordLabel={field.hidePasswordLabel}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'email':
      return (
        <TextField
          {...shared}
          type="email"
          value={asString(raw)}
          placeholder={field.placeholder}
          required={field.required}
          autoComplete="email"
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'number':
      return (
        <NumberField
          {...shared}
          value={raw === '' || raw == null ? '' : Number(raw)}
          min={field.min}
          max={field.max}
          step={field.step}
          required={field.required}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'slider':
      return (
        <SliderField
          {...shared}
          value={typeof raw === 'number' ? raw : Number(raw) || field.min || 0}
          min={field.min}
          max={field.max}
          step={field.step}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'select':
      return (
        <SelectField
          {...shared}
          value={asString(raw)}
          options={field.options ?? []}
          required={field.required}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'toggle':
      return (
        <ToggleField
          {...shared}
          checked={Boolean(raw)}
          onChange={(checked) => onSetPath(path, checked)}
        />
      )
    case 'tags':
      return (
        <TagsField
          {...shared}
          value={Array.isArray(raw) ? raw.map(String) : []}
          placeholder={field.placeholder}
          label={field.label}
          onChange={(value) => onSetPath(path, value)}
        />
      )
    case 'file':
      return (
        <FileField
          {...shared}
          value={isFormFileValue(raw) ? raw : null}
          accept={field.accept}
          onChange={(value: FormFileValue | null) => onSetPath(path, value)}
        />
      )
    default:
      return (
        <TextField
          {...shared}
          value={asString(raw)}
          placeholder={field.placeholder}
          required={field.required}
          disabled={locked}
          onChange={(value) => onSetPath(path, value)}
        />
      )
  }
}

function PrimitiveItem({
  kind,
  id,
  value,
  locked,
  error,
  onChange,
}: {
  kind: FormField['kind']
  id: string
  value: unknown
  locked: boolean
  error?: string
  onChange: (value: unknown) => void
}) {
  if (kind === 'textarea') {
    return (
      <TextAreaField
        id={id}
        value={asString(value)}
        disabled={locked}
        error={error}
        onChange={onChange}
      />
    )
  }
  if (kind === 'number') {
    return (
      <NumberField
        id={id}
        value={value === '' || value == null ? '' : Number(value)}
        disabled={locked}
        error={error}
        onChange={onChange}
      />
    )
  }
  return (
    <TextField
      id={id}
      value={asString(value)}
      disabled={locked}
      error={error}
      onChange={(next) => onChange(next)}
    />
  )
}

function joinPath(prefix: string, name: string): string {
  if (!prefix) return name
  if (!name) return prefix
  return `${prefix}.${name}`
}

function asString(value: unknown): string {
  if (value == null) return ''
  return String(value)
}

// src/svelte/form/FormLayout.svelte
<script lang="ts">
  import { onDestroy, tick } from 'svelte'
  import type { FormIssue, FormSchema } from '../../core/form/contracts'
  import {
    FormAbortError,
    createFormSubmitEnvelope,
    isFormError,
    setAtPath,
    validateForm,
    type FormSubmitEnvelope,
    type FormTransport,
    type FormValues,
  } from '../../core/form/contracts'
  import { firstFormErrorsByPath } from '../../core/form/render'
  import FormSectionView from './FormSectionView.svelte'
  import TintFluidForm from './TintFluidForm.svelte'
  import './styles.css'

  type Props = {
    schema: FormSchema
    values: FormValues
    onValuesChange: (values: FormValues) => void
    issues?: readonly FormIssue[]
    busy?: boolean
    disabled?: boolean
    readOnly?: boolean
    error?: string
    density?: 'compact' | 'comfortable'
    columns?: 1 | 2
    submitLabel?: string
    submittingLabel?: string
    hideSubmit?: boolean
    className?: string
    transport?: FormTransport<FormValues, unknown>
    onSubmit?: (envelope: FormSubmitEnvelope<FormValues>) => void | Promise<void>
    onValidation?: (issues: readonly FormIssue[]) => void
    onSubmitError?: (error: unknown) => void
  }

  let {
    schema, values, onValuesChange, issues: issueProp,
    busy = false, disabled = false, readOnly = false, error,
    density = 'comfortable', columns = 1,
    submitLabel = 'Submit', submittingLabel = 'Submitting…',
    hideSubmit = false, className,
    transport, onSubmit, onValidation, onSubmitError,
  }: Props = $props()

  const prefix = $props.id()
  let localIssues = $state<readonly FormIssue[]>([])
  let submitError = $state<string | null>(null)
  let submitting = $state(false)
  let inFlight = false
  let abortController: AbortController | null = null
  let mounted = true

  let issues = $derived(issueProp ?? localIssues)
  let issuesByPath = $derived(firstFormErrorsByPath(issues))
  let locked = $derived(busy || disabled || readOnly || submitting)
  let banner = $derived(error ?? submitError ?? undefined)

  onDestroy(() => {
    mounted = false
    abortController?.abort()
  })

  function setPath(path: string, value: unknown) {
    onValuesChange(setAtPath(values, path, value))
  }

  function failSubmit(cause: unknown) {
    if (cause instanceof FormAbortError) return
    onSubmitError?.(cause)
    if (!mounted) return
    submitError = isFormError(cause) || cause instanceof Error
      ? cause.message
      : 'The form could not be submitted.'
  }

  async function focusFirstInvalid(form: HTMLFormElement) {
    await tick()
    if (mounted) form.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus()
  }

  function submit(event: SubmitEvent) {
    event.preventDefault()
    if (locked || inFlight) return
    const result = validateForm(schema, values)
    localIssues = result.issues
    submitError = null
    onValidation?.(result.issues)
    if (!result.ok) {
      void focusFirstInvalid(event.currentTarget as HTMLFormElement)
      return
    }

    const envelope = createFormSubmitEnvelope(schema, values)
    inFlight = true
    submitting = true
    void settleSubmit(envelope, event.currentTarget as HTMLFormElement)
  }

  async function settleSubmit(envelope: FormSubmitEnvelope<FormValues>, form: HTMLFormElement) {
    const controller = new AbortController()
    abortController = controller
    let focusInvalid = false
    try {
      if (transport) {
        const remote = await transport.validate(envelope, { signal: controller.signal })
        if (controller.signal.aborted) return
        if (!remote.ok) {
          if (mounted) {
            localIssues = remote.issues
            focusInvalid = true
          }
          onValidation?.(remote.issues)
          return
        }
        await transport.submit(envelope, { signal: controller.signal })
        if (controller.signal.aborted) return
      }
      await onSubmit?.(envelope)
    } catch (cause) {
      failSubmit(cause)
    } finally {
      inFlight = false
      abortController = null
      if (mounted) {
        submitting = false
        if (focusInvalid) void focusFirstInvalid(form)
      }
    }
  }
</script>

<TintFluidForm
  title={schema.title || undefined}
  description={schema.description}
  error={banner}
  {density}
  columns={1}
  busy={busy || submitting}
  noValidate
  {className}
  onsubmit={submit}
>
  {#each schema.sections as section (section.id)}
    <FormSectionView
      {section}
      {prefix}
      {values}
      {issuesByPath}
      {locked}
      {columns}
      onSetPath={setPath}
      {onValuesChange}
    />
  {/each}
  {#if !hideSubmit}
    <button type="submit" class="tint-svelte-form-submit" disabled={locked}>
      {busy || submitting ? submittingLabel : submitLabel}
    </button>
  {/if}
</TintFluidForm>
