// src/components/form/FormControl.tsx
import React, { type ReactNode } from 'react'

void React

export type FormControlProps = {
  id: string
  label: string
  description?: string
  error?: string
  required?: boolean
  disabled?: boolean
  children: ReactNode
  className?: string
}

/**
 * Label, description, and error around one control. Owns the `id` relationship
 * so inputs do not each re-invent `htmlFor` / `aria-describedby`.
 */
export function FormControl({
  id,
  label,
  description,
  error,
  required = false,
  disabled = false,
  children,
  className,
}: FormControlProps) {
  const descriptionId = description ? `${id}-description` : undefined
  const errorId = error ? `${id}-error` : undefined
  const describedBy = [descriptionId, errorId].filter(Boolean).join(' ') || undefined

  return (
    <div
      className={['tint-form-control', className].filter(Boolean).join(' ')}
      data-invalid={error ? 'true' : undefined}
      data-disabled={disabled ? 'true' : undefined}
    >
      <label className="tint-form-label" htmlFor={id}>
        {label}
        {required ? (
          <span className="tint-form-required" aria-hidden="true">
            *
          </span>
        ) : null}
      </label>
      {description ? (
        <p className="tint-form-description" id={descriptionId}>
          {description}
        </p>
      ) : null}
      <div className="tint-form-control__input" data-describedby={describedBy}>
        {children}
      </div>
      {error ? (
        <p className="tint-form-error" id={errorId} role="alert">
          {error}
        </p>
      ) : null}
    </div>
  )
}

export function describedByFor(id: string, description?: string, error?: string): string | undefined {
  const ids = [description ? `${id}-description` : undefined, error ? `${id}-error` : undefined].filter(
    Boolean,
  )
  return ids.length ? ids.join(' ') : undefined
}

// src/svelte/form/FormControl.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import './styles.css'

  type Props = {
    id: string
    label: string
    description?: string
    error?: string
    required?: boolean
    disabled?: boolean
    className?: string
    children?: Snippet
  }

  let {
    id,
    label,
    description,
    error,
    required = false,
    disabled = false,
    className,
    children,
  }: Props = $props()
</script>

<div
  class={['tint-svelte-form-control', className].filter(Boolean).join(' ')}
  data-invalid={Boolean(error)}
  data-disabled={disabled}
>
  <label class="tint-field-label" for={id}>
    {label}{#if required}<span class="tint-field-required" aria-hidden="true"> *</span>{/if}
  </label>
  {#if description}<p id={`${id}-description`} class="tint-field-description">{description}</p>{/if}
  <div class="tint-svelte-form-control__input">{@render children?.()}</div>
  {#if error}<p id={`${id}-error`} class="tint-field-error" role="alert">{error}</p>{/if}
</div>
