// src/svelte/components/feed/FeedEntryRow.svelte
<script lang="ts">
  import { artifactBadge } from '../../../core/feed'
  import Badge from '../badge/Badge.svelte'
  import type { FeedEntryRowProps } from './types'

  let { entry, sourceLabel, selected = false, onSelect, actions, class: className, ...rest }: FeedEntryRowProps = $props()
  let artifact = $derived(artifactBadge(entry.artifactStatus))

  function selectClick(event: MouseEvent) {
    if (!onSelect) return
    const target = event.target
    const current = event.currentTarget
    if (target instanceof Element && current instanceof Element && target !== current) {
      const control = target.closest('button, a[href], input, select, textarea, [role="button"]')
      if (control && control !== current && current.contains(control)) return
    }
    onSelect(entry.id)
  }

</script>

<!-- Pointer selection covers the row; the title is a native keyboard selection button. -->
<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
<article
  {...rest}
  data-tint-feed-entry="" data-tint-feed-variant="row"
  data-unread={entry.readState === 'unread' || undefined} data-selected={selected || undefined}
  class={['feed-row', className].filter(Boolean).join(' ')} class:interactive={Boolean(onSelect)}
  onclick={selectClick}
>
  <span class="unread-dot" aria-hidden="true"></span>
  <div class="content">
    <div class="title-row"><h3>{#if onSelect}<button type="button" class="select" aria-pressed={selected} onclick={() => onSelect?.(entry.id)}>{entry.title}</button>{:else}{entry.title}{/if}</h3>{#if entry.readState === 'unread'}<span class="read-label">Unread</span>{/if}{#if artifact}<Badge tone={artifact.tone}>{artifact.label}</Badge>{/if}</div>
    <p class="meta">{#if sourceLabel}{sourceLabel}<span aria-hidden="true"> · </span>{/if}<time datetime={entry.publishedAt}>{new Date(entry.publishedAt).toLocaleString()}</time><span aria-hidden="true"> · </span>{entry.excerpt}</p>
  </div>
  {#if actions}<div class="actions">{@render actions()}</div>{/if}
</article>

<style>
  .feed-row { display: flex; min-width: 0; align-items: flex-start; gap: var(--tint-space-3); border-bottom: 1px solid var(--tint-border); padding: var(--tint-space-2); text-align: left; }
  .feed-row:last-child { border-bottom: 0; }
  .feed-row[data-unread] { background: var(--tint-accent-soft); }
  .feed-row[data-selected] { box-shadow: inset 0 0 0 1px var(--tint-accent); }
  .feed-row.interactive { cursor: pointer; }
  .feed-row.interactive:hover { background: var(--tint-surface); }
  .select { border: 0; background: none; padding: 0; color: inherit; cursor: pointer; font: inherit; text-align: inherit; }
  .select:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .unread-dot { width: 0.375rem; height: 0.375rem; flex: none; margin-top: 0.375rem; border-radius: 50%; }
  .feed-row[data-unread] .unread-dot { background: var(--tint-accent); }
  .content { min-width: 0; flex: 1; }
  .title-row { display: flex; flex-wrap: wrap; align-items: baseline; gap: var(--tint-space-2); }
  h3 { min-width: 0; margin: 0; overflow: hidden; color: var(--tint-ink); font-size: var(--tint-font-size-sm); font-weight: 500; text-overflow: ellipsis; white-space: nowrap; }
  .read-label { color: var(--tint-accent); font-size: var(--tint-font-size-xs); font-weight: 600; }
  .meta { margin: 0.125rem 0 0; overflow: hidden; color: var(--tint-muted); font-size: var(--tint-font-size-xs); text-overflow: ellipsis; white-space: nowrap; }
  .actions { display: flex; flex: none; align-items: center; gap: var(--tint-space-1); }
</style>

// src/components/feed/FeedEntryRow.tsx
import type { HTMLAttributes, ReactNode } from 'react'
import { Badge } from '../badge'
import { cn } from '../../lib/utils'
import type { ArtifactStatus, FeedEntry } from './contracts'

export type FeedEntryRowProps = Omit<HTMLAttributes<HTMLElement>, 'onSelect'> & {
  entry: FeedEntry
  sourceLabel?: string
  selected?: boolean
  onSelect?: (entryId: string) => void
  actions?: ReactNode
}

const ARTIFACT_LABEL: Record<Exclude<ArtifactStatus, 'none'>, string> = {
  queued: 'queued',
  downloading: 'downloading',
  ready: 'ready',
}

/** Compact list/ticker row — denser than FeedEntryCard, same entry contract. */
export function FeedEntryRow({
  entry,
  sourceLabel,
  selected = false,
  onSelect,
  actions,
  className,
  ...props
}: FeedEntryRowProps) {
  const unread = entry.readState === 'unread'
  const artifact =
    entry.artifactStatus && entry.artifactStatus !== 'none'
      ? ARTIFACT_LABEL[entry.artifactStatus]
      : null

  return (
    <article
      data-tint-feed-entry=""
      data-tint-feed-variant="row"
      data-unread={unread || undefined}
      data-selected={selected || undefined}
      className={cn(
        'flex items-start gap-3 border-b border-tint-border px-2 py-2.5 text-left transition last:border-b-0',
        unread && 'bg-tint-accent-soft/40',
        selected && 'bg-tint-surface ring-1 ring-inset ring-tint-accent',
        onSelect && 'cursor-pointer hover:bg-tint-surface',
        className,
      )}
      onClick={onSelect ? () => onSelect(entry.id) : undefined}
      onKeyDown={
        onSelect
          ? (event) => {
              if (event.key === 'Enter' || event.key === ' ') {
                event.preventDefault()
                onSelect(entry.id)
              }
            }
          : undefined
      }
      role={onSelect ? 'button' : undefined}
      tabIndex={onSelect ? 0 : undefined}
      {...props}
    >
      <span
        className={cn(
          'mt-1.5 size-1.5 shrink-0 rounded-full',
          unread ? 'bg-tint-accent' : 'bg-transparent',
        )}
        aria-hidden
      />
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5">
          <h3 className="m-0 truncate text-sm font-medium text-tint-ink">{entry.title}</h3>
          {artifact ? (
            <Badge tone={artifact === 'ready' ? 'success' : 'info'}>{artifact}</Badge>
          ) : null}
        </div>
        <p className="m-0 mt-0.5 truncate text-xs text-tint-muted">
          {sourceLabel ? (
            <>
              {sourceLabel}
              <span className="mx-1">·</span>
            </>
          ) : null}
          <time dateTime={entry.publishedAt}>
            {new Date(entry.publishedAt).toLocaleString()}
          </time>
          <span className="mx-1">·</span>
          {entry.excerpt}
        </p>
      </div>
      {actions ? <div className="flex shrink-0 items-center gap-1">{actions}</div> : null}
    </article>
  )
}
