// src/components/audio-react/TrackImportController.tsx
import { useSyncExternalStore } from 'react'
import { AnalysisQueue } from '../dj/AnalysisQueue'
import { ImportTracksDialog } from '../dj/ImportTracksDialog'
import type { TrackImportStore } from '../audio-engine/trackImportStore'

export type TrackImportControllerProps = {
  open: boolean
  store: TrackImportStore
  onClose: () => void
}

export function TrackImportController({ open, store, onClose }: TrackImportControllerProps) {
  const snapshot = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getSnapshot)
  return (
    <div className="space-y-4">
      <ImportTracksDialog
        open={open}
        selectedFiles={snapshot.selectedFiles}
        busy={snapshot.state === 'importing'}
        error={snapshot.error}
        onFilesSelected={store.selectFiles}
        onImport={() => { void store.importSelected() }}
        onClose={onClose}
      />
      {snapshot.items.length > 0 && (
        <AnalysisQueue
          items={snapshot.items}
          onRetry={() => { void store.importSelected() }}
        />
      )}
    </div>
  )
}

// src/svelte/components/audio-workspace/TrackImportController.svelte
<script lang="ts">
  import { observeAudioStore } from '../audio-engine/bindings'
  import AnalysisQueue from '../dj/AnalysisQueue.svelte'
  import ImportTracksDialog from '../dj/ImportTracksDialog.svelte'
  import type { TrackImportControllerProps } from './types'

  let { open, store, onClose }: TrackImportControllerProps = $props()
  let observed = $derived(observeAudioStore(store))
  let snapshot = $derived(observed.snapshot)

  async function importTracks() {
    await store.importSelected()
    if (store.getSnapshot().state === 'ready') onClose()
  }
</script>

<div class="space-y-4">
  <ImportTracksDialog {open} selectedFiles={snapshot.selectedFiles} busy={snapshot.state === 'importing'} error={snapshot.error}
    onFilesSelected={store.selectFiles} onImport={() => { void importTracks() }} {onClose} />
  {#if snapshot.items.length}
    <AnalysisQueue items={snapshot.items} onRetry={() => { void store.importSelected() }} />
  {/if}
</div>
