// src/components/timeline/BeatGridOverlay.tsx
import type { TimelineViewport } from './contracts'
import { beatToPixel, timelineVisibleRange } from './viewport'

export type BeatGridOverlayProps = {
  viewport: TimelineViewport
  beatsPerBar: number
  className?: string
}

export function BeatGridOverlay({
  viewport,
  beatsPerBar,
  className,
}: BeatGridOverlayProps) {
  if (!Number.isFinite(beatsPerBar) || beatsPerBar <= 0) {
    throw new RangeError('Beat grid beats per bar must be a positive finite number')
  }

  const visible = timelineVisibleRange(viewport)
  const firstBeat = Math.ceil(visible.startBeat)
  const lastBeat = Math.floor(visible.endBeat)
  const beats = Array.from(
    { length: Math.max(0, lastBeat - firstBeat + 1) },
    (_, index) => firstBeat + index,
  )

  return (
    <div
      aria-hidden="true"
      className={className}
      data-tint-beat-grid=""
    >
      {beats.map((beat) => {
        const isBar = beat % beatsPerBar === 0
        return (
          <span
            key={beat}
            data-beat={beat}
            data-bar-line={String(isBar)}
            className={isBar ? 'absolute inset-y-0 border-l border-current/45' : 'absolute inset-y-0 border-l border-current/15'}
            style={{ left: `${beatToPixel(viewport, beat)}px` }}
          />
        )
      })}
    </div>
  )
}

// src/svelte/components/timeline/BeatGridOverlay.svelte
<script lang="ts">
  import { beatToPixel, timelineVisibleRange } from '../../../core/timeline/viewport'
  import type { BeatGridOverlayProps } from './types'

  let { viewport, beatsPerBar, class: className }: BeatGridOverlayProps = $props()
  let beats = $derived.by(() => {
    if (!Number.isFinite(beatsPerBar) || beatsPerBar <= 0) throw new RangeError('Beat grid beats per bar must be a positive finite number')
    const visible = timelineVisibleRange(viewport)
    const first = Math.ceil(visible.startBeat)
    const last = Math.floor(visible.endBeat)
    return Array.from({ length: Math.max(0, last - first + 1) }, (_, index) => first + index)
  })
</script>

<div aria-hidden="true" data-tint-beat-grid="" class={className}>
  {#each beats as beat (beat)}
    <span data-beat={beat} data-bar-line={String(beat % beatsPerBar === 0)}
      class={beat % beatsPerBar === 0 ? 'absolute inset-y-0 border-l border-current/45' : 'absolute inset-y-0 border-l border-current/15'}
      style:left={`${beatToPixel(viewport, beat)}px`}></span>
  {/each}
</div>
