// src/svelte/components/chat/ChatMessageEditor.svelte
<script lang="ts">
  import type { ChatMessageEditorProps } from './types'

  let { value, onValueChange, onSave, onCancel, busy = false, error,
    label = 'Edit message', maxLength, class: className }: ChatMessageEditorProps = $props()
  const id = $props.id()
  const button = 'rounded border border-tint-border px-3 py-1.5 text-sm hover:bg-tint-surface focus-visible:outline-2 focus-visible:outline-tint-accent disabled:opacity-40'

  function save() { if (!busy && value.trim()) onSave() }
  function keydown(event: KeyboardEvent) {
    if (event.key === 'Escape' && !busy) { event.preventDefault(); onCancel() }
    if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) { event.preventDefault(); save() }
  }
</script>

<form class={['flex min-w-0 flex-col gap-2 py-2', className]} aria-busy={busy}
  onsubmit={(event) => { event.preventDefault(); save() }}>
  <label for={id} class="text-xs font-medium">{label}</label>
  <textarea {id} {value} maxlength={maxLength} disabled={busy} rows="5"
    aria-describedby={error ? `${id}-error` : undefined} aria-invalid={Boolean(error)}
    class="w-full min-w-0 resize-y rounded border border-tint-border bg-tint-panel p-2 text-sm text-tint-ink focus-visible:outline-2 focus-visible:outline-tint-accent"
    oninput={(event) => onValueChange(event.currentTarget.value)} onkeydown={keydown}></textarea>
  {#if error}<p id={`${id}-error`} role="alert" class="text-sm text-tint-danger">{error}</p>{/if}
  <div class="flex flex-wrap gap-2">
    <button type="submit" class={button} disabled={busy || !value.trim()}>{busy ? 'Saving…' : 'Save message'}</button>
    <button type="button" class={button} disabled={busy} onclick={onCancel}>Cancel</button>
  </div>
</form>

// src/components/chat/ChatMessageEditor.tsx
import { useId } from 'react'
import { cn } from '../../lib/utils'

export type ChatMessageEditorProps = {
  value: string
  onValueChange: (value: string) => void
  onSave: () => void
  onCancel: () => void
  busy?: boolean
  error?: string
  label?: string
  maxLength?: number
  className?: string
}

/** Controlled inline edit form. The host owns persistence and conflict handling. */
export function ChatMessageEditor({ value, onValueChange, onSave, onCancel,
  busy = false, error, label = 'Edit message', maxLength, className }: ChatMessageEditorProps) {
  const id = useId()
  const button = 'rounded border border-tint-border px-3 py-1.5 text-sm hover:bg-tint-surface focus-visible:outline-2 focus-visible:outline-tint-accent disabled:opacity-40'
  return (
    <form className={cn('flex min-w-0 flex-col gap-2 py-2', className)} aria-busy={busy}
      onSubmit={(event) => { event.preventDefault(); if (!busy && value.trim()) onSave() }}>
      <label htmlFor={id} className="text-xs font-medium">{label}</label>
      <textarea id={id} value={value} maxLength={maxLength} disabled={busy} rows={5}
        aria-describedby={error ? `${id}-error` : undefined} aria-invalid={Boolean(error)}
        className="w-full min-w-0 resize-y rounded border border-tint-border bg-tint-panel p-2 text-sm text-tint-ink focus-visible:outline-2 focus-visible:outline-tint-accent"
        onChange={(event) => onValueChange(event.target.value)}
        onKeyDown={(event) => {
          if (event.key === 'Escape' && !busy) { event.preventDefault(); onCancel() }
          if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) { event.preventDefault(); if (!busy && value.trim()) onSave() }
        }} />
      {error ? <p id={`${id}-error`} role="alert" className="text-sm text-tint-danger">{error}</p> : null}
      <div className="flex flex-wrap gap-2">
        <button type="submit" className={button} disabled={busy || !value.trim()}>{busy ? 'Saving…' : 'Save message'}</button>
        <button type="button" className={button} disabled={busy} onClick={onCancel}>Cancel</button>
      </div>
    </form>
  )
}
