// src/svelte/components/media/SettingsPopout.svelte
<script lang="ts">
  import { tick, type Snippet } from 'svelte'
  import { Check, Search } from '@lucide/svelte'
  import { filterSettings, groupSettings, type SettingsItem } from '../../../core/media/settings'
  import Icon from '../icon/Icon.svelte'
  import Popover from '../popover/Popover.svelte'
  import type { PopoverTriggerProps } from '../popover/types'

  type Props = {
    isOpen: boolean
    onOpenChange: (open: boolean) => void
    items: readonly SettingsItem[]
    value?: string
    onSelect?: (id: string) => void
    label?: string
    placeholder?: string
    footer?: string | Snippet
    emptySearchText?: string | Snippet
    onQueryChange?: (query: string) => void
    trigger?: Snippet<[PopoverTriggerProps]>
    class?: string
  }
  let {
    isOpen, onOpenChange, items, value, onSelect,
    label = 'Settings', placeholder = 'Search settings…', footer,
    emptySearchText = 'No results', onQueryChange, trigger, class: className,
  }: Props = $props()
  const listId = $props.id()
  let triggerHolder = $state<HTMLSpanElement>()
  let query = $state('')
  let activeIndex = $state(0)
  let wasOpen = false
  let filtered = $derived(filterSettings(items, query))
  let groups = $derived(groupSettings(filtered))
  let flat = $derived(groups.flatMap((group) => group.items))

  $effect(() => {
    if (isOpen && !wasOpen) {
      query = ''
      activeIndex = Math.max(0, flat.findIndex((item) => item.id === value))
      wasOpen = true
    } else if (!isOpen) {
      wasOpen = false
      query = ''
      activeIndex = 0
    }
  })

  function closeAndFocus() {
    onOpenChange(false)
    void tick().then(() => triggerHolder?.querySelector<HTMLElement>('[data-tint-trigger]')?.focus())
  }

  function select(id: string) {
    onSelect?.(id)
    closeAndFocus()
  }

  function onKeydown(event: KeyboardEvent) {
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      activeIndex = flat.length ? (activeIndex + (event.key === 'ArrowDown' ? 1 : -1) + flat.length) % flat.length : 0
    } else if (event.key === 'Home' || event.key === 'End') {
      event.preventDefault()
      activeIndex = event.key === 'Home' ? 0 : Math.max(flat.length - 1, 0)
    } else if (event.key === 'Enter') {
      event.preventDefault()
      const item = flat[activeIndex]
      if (item) select(item.id)
    }
  }
</script>

{#snippet forwardedTrigger(triggerProps: PopoverTriggerProps)}
  <span bind:this={triggerHolder} class="trigger-holder">
    {#if trigger}
      {@render trigger(triggerProps)}
    {:else}
      <button id={triggerProps.id} type="button" data-tint-trigger="" aria-haspopup={triggerProps['aria-haspopup']} aria-expanded={triggerProps['aria-expanded']} aria-controls={triggerProps['aria-controls']} onclick={triggerProps.onclick}>{label}</button>
    {/if}
  </span>
{/snippet}

<Popover open={isOpen} {onOpenChange} trigger={forwardedTrigger} {label} side="top" class={['tint-settings-popout', className].filter(Boolean).join(' ')}>
  <div class="search-row"><Icon icon={Search} size="sm" /><input
    role="combobox"
    aria-label={`Search ${label}`}
    aria-expanded="true"
    aria-controls={listId}
    aria-autocomplete="list"
    aria-activedescendant={flat[activeIndex] ? `${listId}-${flat[activeIndex].id}` : undefined}
    {placeholder}
    value={query}
    oninput={(event) => { query = event.currentTarget.value; activeIndex = 0; onQueryChange?.(query) }}
    onkeydown={onKeydown}
  /></div>
  <div id={listId} role="listbox" aria-label={label} class="list">
    {#if flat.length === 0}
      <div class="empty">{#if typeof emptySearchText === 'string'}{emptySearchText}{:else}{@render emptySearchText()}{/if}</div>
    {:else}
      {#each groups as group (group.heading ?? 'ungrouped')}
        <div class="group">
          {#if group.heading}<div class="heading">{group.heading}</div>{/if}
          {#each group.items as item (item.id)}
            {@const index = flat.findIndex((candidate) => candidate.id === item.id)}
            <button
              id={`${listId}-${item.id}`}
              type="button"
              role="option"
              aria-selected={item.id === value}
              data-active={index === activeIndex}
              onpointerenter={() => activeIndex = index}
              onclick={() => select(item.id)}
            >
              <span class="item-label">{item.label}</span>
              {#if item.shortcut}<kbd>{item.shortcut}</kbd>{/if}
              {#if item.id === value}<Icon icon={Check} size="sm" />{/if}
            </button>
          {/each}
        </div>
      {/each}
    {/if}
  </div>
  <div class="footer">{#if footer}{#if typeof footer === 'string'}{footer}{:else}{@render footer()}{/if}{:else}↑ ↓ navigate · ↵ select · esc close{/if}</div>
</Popover>

<style>
  .trigger-holder { display: inline-flex; }
  .trigger-holder button { border: 0; border-radius: var(--tint-radius-sm); padding: var(--tint-space-2); background: transparent; color: var(--tint-chrome-ink); cursor: pointer; }
  :global(.tint-settings-popout) { width: 18rem !important; max-width: min(20rem, calc(100vw - 1rem)) !important; padding: 0 !important; border-color: var(--tint-chrome-border) !important; background: var(--tint-chrome) !important; color: var(--tint-chrome-ink) !important; }
  .search-row { display: flex; align-items: center; gap: .5rem; padding: .625rem .75rem; border-bottom: 1px solid var(--tint-chrome-border); }
  .search-row:focus-within { outline: 2px solid var(--tint-accent); outline-offset: -2px; }
  input { min-width: 0; width: 100%; border: 0; background: transparent; color: inherit; font: inherit; font-size: var(--tint-font-size-sm); outline: none; }
  input::placeholder { color: color-mix(in srgb, var(--tint-chrome-ink) 40%, transparent); }
  .list { max-height: 16rem; overflow: auto; padding: .375rem; }
  .group + .group { margin-top: .25rem; }
  .heading { padding: .375rem .625rem .25rem; color: color-mix(in srgb, var(--tint-chrome-ink) 55%, transparent); font-size: .6875rem; font-weight: 600; letter-spacing: .08em; text-transform: uppercase; }
  .group button { display: flex; width: 100%; align-items: center; gap: .5rem; padding: .5rem .625rem; border: 0; border-radius: var(--tint-radius-sm); background: transparent; color: inherit; font: inherit; font-size: var(--tint-font-size-sm); text-align: left; cursor: pointer; }
  .group button:hover, .group button[data-active='true'] { background: color-mix(in srgb, var(--tint-chrome-ink) 12%, transparent); }
  .group button:focus-visible { outline: 2px solid var(--tint-chrome-ink); }
  .item-label { min-width: 0; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  kbd { border-radius: var(--tint-radius-sm); padding: .125rem .375rem; background: color-mix(in srgb, var(--tint-chrome-ink) 10%, transparent); font-size: .6875rem; }
  .empty { padding: 1.5rem .75rem; color: color-mix(in srgb, var(--tint-chrome-ink) 55%, transparent); text-align: center; }
  .footer { border-top: 1px solid var(--tint-chrome-border); padding: .5rem .75rem; color: color-mix(in srgb, var(--tint-chrome-ink) 55%, transparent); font-size: .6875rem; }
</style>

// src/components/settings-popout/SettingsPopout.tsx
import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
  type ReactNode,
} from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { Check, Search } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Icon } from '@/components/icon'

export type SettingsPopoutItem = {
  id: string
  label: string
  group?: string
  shortcut?: string
  description?: string
}

export type SettingsPopoutProps = {
  /** Whether the popout is visible */
  isOpen: boolean
  /** Called when open state should change */
  onOpenChange: (isOpen: boolean) => void
  /** Selectable settings items */
  items: SettingsPopoutItem[]
  /** Currently selected item id (picker mode) */
  value?: string
  /** Called when an item is chosen */
  onSelect?: (id: string) => void
  /** Accessible label for the dialog */
  label?: string
  /** Search input placeholder */
  placeholder?: string
  /** Optional footer content; defaults to keyboard hints */
  footer?: ReactNode
  /** Empty search results text */
  emptySearchText?: ReactNode
  /** Additional class names for the panel */
  className?: string
}

type GroupedItems = {
  heading?: string
  items: SettingsPopoutItem[]
}

function groupItems(items: SettingsPopoutItem[]): GroupedItems[] {
  const order: string[] = []
  const groups = new Map<string, SettingsPopoutItem[]>()
  const ungrouped: SettingsPopoutItem[] = []

  for (const item of items) {
    if (!item.group) {
      ungrouped.push(item)
      continue
    }
    if (!groups.has(item.group)) {
      order.push(item.group)
      groups.set(item.group, [])
    }
    groups.get(item.group)!.push(item)
  }

  return [
    ...order.map((heading) => ({ heading, items: groups.get(heading)! })),
    ...(ungrouped.length ? [{ items: ungrouped }] : []),
  ]
}

function filterItems(items: SettingsPopoutItem[], query: string) {
  const normalized = query.trim().toLowerCase()
  if (!normalized) return items
  return items.filter((item) => {
    const haystack = `${item.label} ${item.group ?? ''} ${item.description ?? ''}`.toLowerCase()
    return haystack.includes(normalized)
  })
}

export function SettingsPopout({
  isOpen,
  onOpenChange,
  items,
  value,
  onSelect,
  label = 'Settings',
  placeholder = 'Search settings…',
  footer,
  emptySearchText = 'No results',
  className,
}: SettingsPopoutProps) {
  const listId = useId()
  const inputRef = useRef<HTMLInputElement>(null)
  const panelRef = useRef<HTMLDivElement>(null)
  const [query, setQuery] = useState('')
  const [activeIndex, setActiveIndex] = useState(0)

  const filtered = useMemo(() => filterItems(items, query), [items, query])
  const grouped = useMemo(() => groupItems(filtered), [filtered])
  const flat = useMemo(() => grouped.flatMap((group) => group.items), [grouped])

  useEffect(() => {
    if (!isOpen) {
      setQuery('')
      setActiveIndex(0)
      return
    }

    const selectedIndex = items.findIndex((item) => item.id === value)
    setActiveIndex(selectedIndex >= 0 ? selectedIndex : 0)

    const frame = window.requestAnimationFrame(() => {
      inputRef.current?.focus()
    })
    return () => window.cancelAnimationFrame(frame)
  }, [isOpen, value, items])

  useEffect(() => {
    if (!isOpen) return

    const onPointerDown = (event: MouseEvent) => {
      if (!panelRef.current?.contains(event.target as Node)) {
        onOpenChange(false)
      }
    }

    const onKeyDown = (event: globalThis.KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.preventDefault()
        onOpenChange(false)
      }
    }

    document.addEventListener('mousedown', onPointerDown)
    document.addEventListener('keydown', onKeyDown)
    return () => {
      document.removeEventListener('mousedown', onPointerDown)
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [isOpen, onOpenChange])

  useEffect(() => {
    if (activeIndex > flat.length - 1) {
      setActiveIndex(Math.max(flat.length - 1, 0))
    }
  }, [activeIndex, flat.length])

  const selectItem = (id: string) => {
    onSelect?.(id)
    onOpenChange(false)
  }

  const onInputKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      setActiveIndex((index) => (flat.length ? (index + 1) % flat.length : 0))
    }
    if (event.key === 'ArrowUp') {
      event.preventDefault()
      setActiveIndex((index) =>
        flat.length ? (index - 1 + flat.length) % flat.length : 0,
      )
    }
    if (event.key === 'Home') {
      event.preventDefault()
      setActiveIndex(0)
    }
    if (event.key === 'End') {
      event.preventDefault()
      setActiveIndex(Math.max(flat.length - 1, 0))
    }
    if (event.key === 'Enter') {
      event.preventDefault()
      const item = flat[activeIndex]
      if (item) selectItem(item.id)
    }
  }

  const itemIndexById = useMemo(() => {
    const map = new Map<string, number>()
    flat.forEach((item, index) => map.set(item.id, index))
    return map
  }, [flat])

  return (
    <AnimatePresence>
      {isOpen ? (
        <motion.div
          ref={panelRef}
          role="dialog"
          aria-label={label}
          aria-modal="true"
          initial={{ opacity: 0, y: 8, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 8, scale: 0.98 }}
          transition={{ duration: 0.18, ease: 'easeOut' }}
          className={cn(
            'absolute right-0 bottom-[calc(100%+0.5rem)] z-30 w-72 overflow-hidden rounded-xl border border-tint-chrome-border bg-tint-chrome text-tint-chrome-ink shadow-[0_16px_48px_var(--tint-shadow-color)] backdrop-blur-xl sm:w-80',
            className,
          )}
          onMouseDown={(event) => event.stopPropagation()}
        >
          <div className="flex items-center gap-2 border-b border-tint-chrome-border px-3 py-2.5">
            <Icon icon={Search} className="shrink-0 text-tint-chrome-ink/55" />
            <input
              ref={inputRef}
              value={query}
              onChange={(event) => {
                setQuery(event.target.value)
                setActiveIndex(0)
              }}
              onKeyDown={onInputKeyDown}
              placeholder={placeholder}
              aria-controls={listId}
              aria-autocomplete="list"
              aria-activedescendant={
                flat[activeIndex] ? `${listId}-${flat[activeIndex].id}` : undefined
              }
              className="w-full bg-transparent text-sm text-tint-chrome-ink outline-none placeholder:text-tint-chrome-ink/40"
            />
          </div>

          <div
            id={listId}
            role="listbox"
            aria-label={label}
            className="max-h-64 overflow-y-auto p-1.5"
          >
            {flat.length === 0 ? (
              <div className="px-3 py-6 text-center text-sm text-tint-chrome-ink/55">
                {emptySearchText}
              </div>
            ) : (
              grouped.map((group) => (
                <div key={group.heading ?? 'ungrouped'} className="mb-1 last:mb-0">
                  {group.heading ? (
                    <div className="px-2.5 pt-1.5 pb-1 text-[11px] font-medium tracking-[0.08em] text-tint-chrome-ink/45 uppercase">
                      {group.heading}
                    </div>
                  ) : null}
                  <div className="space-y-0.5">
                    {group.items.map((item) => {
                      const index = itemIndexById.get(item.id) ?? 0
                      const isActive = index === activeIndex
                      const isSelected = item.id === value

                      return (
                        <button
                          key={item.id}
                          id={`${listId}-${item.id}`}
                          type="button"
                          role="option"
                          aria-selected={isSelected}
                          className={cn(
                            'flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-sm transition-colors',
                            isActive ? 'bg-tint-chrome-ink/12' : 'hover:bg-tint-chrome-ink/8',
                            isSelected && 'font-medium',
                          )}
                          onMouseEnter={() => setActiveIndex(index)}
                          onClick={() => selectItem(item.id)}
                        >
                          <span className="min-w-0 flex-1 truncate">{item.label}</span>
                          {item.shortcut ? (
                            <kbd className="rounded-md bg-tint-chrome-ink/10 px-1.5 py-0.5 font-mono text-[11px] text-tint-chrome-ink/60">
                              {item.shortcut}
                            </kbd>
                          ) : null}
                          {isSelected ? (
                            <Icon icon={Check} className="shrink-0 text-tint-chrome-ink" />
                          ) : (
                            <span className="size-4 shrink-0" aria-hidden="true" />
                          )}
                        </button>
                      )
                    })}
                  </div>
                </div>
              ))
            )}
          </div>

          <div className="flex items-center justify-between gap-3 border-t border-tint-chrome-border px-3 py-2 text-[11px] text-tint-chrome-ink/45">
            {footer ?? (
              <>
                <span>
                  <kbd className="rounded bg-tint-chrome-ink/10 px-1 py-0.5">↑</kbd>{' '}
                  <kbd className="rounded bg-tint-chrome-ink/10 px-1 py-0.5">↓</kbd> navigate
                </span>
                <span>
                  <kbd className="rounded bg-tint-chrome-ink/10 px-1 py-0.5">↵</kbd> select
                  <span className="mx-2 text-tint-chrome-ink/25">·</span>
                  <kbd className="rounded bg-tint-chrome-ink/10 px-1 py-0.5">esc</kbd> close
                </span>
              </>
            )}
          </div>
        </motion.div>
      ) : null}
    </AnimatePresence>
  )
}

export default SettingsPopout
