// src/svelte/components/identity/Avatar.svelte
<script lang="ts">
  import { identityInitials } from '../../../core/identity'
  import type { AvatarProps } from './types'

  let {
    identity, name, src, alt, size = 'md', presence, badge, decorative = false,
    class: className, ...rest
  }: AvatarProps = $props()
  let resolvedName = $derived(name ?? identity?.name ?? '')
  let resolvedSrc = $derived(src ?? identity?.avatarUrl)
  let resolvedPresence = $derived(presence ?? identity?.presence)
  let failedSource = $state<string | null>(null)
  let showImage = $derived(Boolean(resolvedSrc) && failedSource !== resolvedSrc)
  let accessibleName = $derived([
    (alt ?? resolvedName) || 'Unknown identity',
    resolvedPresence && resolvedPresence !== 'unknown' ? resolvedPresence : null,
  ].filter(Boolean).join(', '))

  $effect(() => {
    void resolvedSrc
    failedSource = null
  })
</script>

<span
  {...rest} data-tint-avatar="" data-size={size} data-presence={resolvedPresence}
  role={decorative ? undefined : 'img'}
  aria-label={decorative ? undefined : accessibleName}
  aria-hidden={decorative || undefined}
  class={['avatar', className].filter(Boolean).join(' ')}
>
  {#if showImage}
    <img src={resolvedSrc} alt="" onerror={() => failedSource = resolvedSrc ?? null} />
  {:else}
    <span aria-hidden="true">{identityInitials(resolvedName)}</span>
  {/if}
  {#if resolvedPresence && resolvedPresence !== 'unknown'}
    <span data-avatar-presence="" data-presence={resolvedPresence} title={resolvedPresence} aria-hidden="true" class="presence"></span>
  {/if}
  {#if badge}<span class="badge">{@render badge()}</span>{/if}
</span>

<style>
  .avatar { position: relative; display: inline-flex; flex: none; align-items: center; justify-content: center; overflow: visible; border-radius: 50%; background: var(--tint-accent-soft); color: var(--tint-accent); font-weight: 600; }
  .avatar[data-size='xs'] { width: 1.25rem; height: 1.25rem; font-size: 0.5625rem; }
  .avatar[data-size='sm'] { width: 1.75rem; height: 1.75rem; font-size: 0.625rem; }
  .avatar[data-size='md'] { width: 2.25rem; height: 2.25rem; font-size: var(--tint-font-size-xs); }
  .avatar[data-size='lg'] { width: 3rem; height: 3rem; font-size: var(--tint-font-size-sm); }
  .avatar[data-size='xl'] { width: 4rem; height: 4rem; font-size: var(--tint-font-size-lg); }
  img { width: 100%; height: 100%; border-radius: inherit; object-fit: cover; }
  .presence { position: absolute; right: 0; bottom: 0; width: max(28%, 0.5rem); height: max(28%, 0.5rem); border: 2px solid var(--tint-panel); border-radius: 50%; background: var(--tint-muted); }
  .presence[data-presence='online'] { background: var(--tint-success); }
  .presence[data-presence='away'] { border-radius: 2px; background: var(--tint-warning); }
  .presence[data-presence='busy'] { transform: rotate(45deg); border-radius: 1px; background: var(--tint-danger); }
  .badge { position: absolute; top: -0.25rem; right: -0.25rem; }
</style>

// src/components/identity/Avatar.tsx
import { useEffect, useState, type HTMLAttributes, type ReactNode } from 'react'
import { cn } from '../../lib/utils'
import type { Identity, Presence } from './types'

export type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'

export type AvatarProps = Omit<HTMLAttributes<HTMLSpanElement>, 'children'> & {
  identity?: Identity
  name?: string
  src?: string
  alt?: string
  size?: AvatarSize
  presence?: Presence
  badge?: ReactNode
  decorative?: boolean
}

const SIZE_CLASS: Record<AvatarSize, string> = {
  xs: 'size-5 text-[0.5625rem]',
  sm: 'size-7 text-[0.625rem]',
  md: 'size-9 text-xs',
  lg: 'size-12 text-sm',
  xl: 'size-16 text-lg',
}

function initialsFor(name: string): string {
  const words = name.trim().split(/\s+/).filter(Boolean)
  if (words.length === 0) return '?'
  const first = words[0]?.[0] ?? ''
  const last = words.length > 1 ? words[words.length - 1]?.[0] ?? '' : words[0]?.[1] ?? ''
  return `${first}${last}`.toLocaleUpperCase()
}

export function Avatar({
  identity,
  name = identity?.name ?? '',
  src = identity?.avatarUrl,
  alt,
  size = 'md',
  presence = identity?.presence,
  badge,
  decorative = false,
  className,
  ...props
}: AvatarProps) {
  const [failedSource, setFailedSource] = useState<string | null>(null)
  useEffect(() => setFailedSource(null), [src])
  const showImage = Boolean(src) && failedSource !== src
  const imageAlt = decorative ? '' : (alt ?? name)

  return (
    <span
      data-tint-avatar=""
      data-size={size}
      data-presence={presence}
      aria-label={!showImage && !decorative ? name || 'Unknown identity' : undefined}
      aria-hidden={decorative || undefined}
      className={cn(
        'relative inline-flex shrink-0 items-center justify-center rounded-full bg-tint-accent-soft font-semibold text-tint-accent',
        SIZE_CLASS[size],
        className,
      )}
      {...props}
    >
      {showImage ? (
        <img
          src={src}
          alt={imageAlt}
          className="size-full rounded-[inherit] object-cover"
          onError={() => setFailedSource(src ?? null)}
        />
      ) : (
        <span aria-hidden="true">{initialsFor(name)}</span>
      )}
      {presence && presence !== 'unknown' ? (
        <span
          data-avatar-presence=""
          data-presence={presence}
          title={presence}
          className={cn(
            'absolute right-0 bottom-0 size-[28%] min-h-2 min-w-2 rounded-full border-2 border-tint-panel',
            presence === 'online' && 'bg-tint-success',
            presence === 'away' && 'bg-tint-warning',
            presence === 'busy' && 'bg-tint-danger',
            presence === 'offline' && 'bg-tint-muted',
          )}
        />
      ) : null}
      {badge ? <span className="absolute -top-1 -right-1">{badge}</span> : null}
    </span>
  )
}

export type AvatarGroupProps = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
  identities: readonly Identity[]
  max?: number
  size?: AvatarSize
  renderLink?: (identity: Identity, avatar: ReactNode) => ReactNode
}

export function AvatarGroup({ identities, max = 4, size = 'md', renderLink, className, ...props }: AvatarGroupProps) {
  const visible = identities.slice(0, Math.max(0, max))
  const overflow = Math.max(0, identities.length - visible.length)
  return (
    <div
      data-tint-avatar-group=""
      className={cn('flex -space-x-2 [&>*]:ring-2 [&>*]:ring-tint-panel', className)}
      {...props}
    >
      {visible.map((identity) => {
        const avatar = <Avatar identity={identity} size={size} />
        return <span key={identity.id}>{renderLink ? renderLink(identity, avatar) : avatar}</span>
      })}
      {overflow > 0 ? (
        <span className={cn('inline-flex items-center justify-center rounded-full bg-tint-surface font-medium text-tint-muted', SIZE_CLASS[size])}>
          +{overflow}
        </span>
      ) : null}
    </div>
  )
}
