// src/svelte/components/annotation/AnnotationCanvas.svelte
<script lang="ts">
  import { boxFromPoints, drawMaskStroke, loadMask, movedGeometry, normalizedPoint,
    type AnnotationImage, type AnnotationRegion, type AnnotationTool,
    type Point, type RegionGeometry, type VectorGeometry } from '../../../core/annotation'

  type Props = {
    image: AnnotationImage
    regions: readonly AnnotationRegion[]
    selectedId?: string | null
    tool: AnnotationTool
    zoom?: number
    brushSize?: number
    disabled?: boolean
    onSelect: (id: string | null) => void
    onCreate: (geometry: VectorGeometry) => void
    onGeometryChange: (id: string, geometry: VectorGeometry) => void
    onMaskChange?: (blob: Blob) => void
    onDelete?: (id: string) => void
    class?: string
  }

  let {
    image, regions, selectedId = null, tool, zoom = 1, brushSize = 20,
    disabled = false, onSelect, onCreate, onGeometryChange, onMaskChange,
    onDelete, class: className,
  }: Props = $props()
  const maskPrefix = $props.id()
  let svg = $state<SVGSVGElement | null>(null)
  let stage = $state<HTMLDivElement | null>(null)
  let canvas = $state<HTMLCanvasElement | null>(null)
  let box = $state<VectorGeometry | null>(null)
  let points = $state<Point[]>([])
  let preview = $state<{ id: string; geometry: VectorGeometry } | null>(null)
  let gesture: { start: Point; region?: AnnotationRegion; vertex?: number; corner?: boolean } | null = null
  let selected = $derived(regions.find((region) => region.id === selectedId))
  let maskUrl = $derived(selected?.geometry.kind === 'mask' ? selected.geometry.url : undefined)
  let painting = $derived(tool === 'brush' || tool === 'erase')
  let rendered = $derived(regions.filter((region) => !region.hidden))
  let lastGestureKey = ''

  $effect(() => {
    const key = `${image.id}:${tool}`
    if (key === lastGestureKey) return
    lastGestureKey = key
    points = []; box = null; preview = null; gesture = null
  })
  $effect(() => {
    if (canvas) return loadMask(canvas, image, maskUrl)
  })

  function position(event: PointerEvent): Point {
    return normalizedPoint(event.clientX, event.clientY, svg!.getBoundingClientRect())
  }
  function draw(from: Point, to: Point) {
    if (canvas) drawMaskStroke(canvas, image, from, to, brushSize, tool === 'erase')
  }
  function down(event: PointerEvent) {
    if (disabled || event.button !== 0 || !svg || !stage) return
    stage.focus()
    const point = position(event)
    if (tool === 'polygon') { points = [...points, point]; return }
    const target = event.target instanceof Element ? event.target : null
    const id = target?.closest('[data-region-id]')?.getAttribute('data-region-id')
    const region = regions.find((item) => item.id === id)
    if (tool === 'select') onSelect(region?.id ?? null)
    const vertex = target?.getAttribute('data-vertex')
    gesture = { start: point, region, vertex: vertex == null ? undefined : Number(vertex), corner: target?.hasAttribute('data-corner') }
    stage.setPointerCapture?.(event.pointerId)
    if (painting) draw(point, { x: point.x + .00001, y: point.y + .00001 })
  }
  function move(event: PointerEvent) {
    if (!gesture || disabled) return
    const point = position(event)
    if (painting) { draw(gesture.start, point); gesture.start = point; return }
    if (tool === 'box') box = boxFromPoints(gesture.start, point)
    else if (tool === 'select' && gesture.region && gesture.region.geometry.kind !== 'mask') {
      preview = { id: gesture.region.id, geometry: movedGeometry(gesture.region.geometry, gesture.start, point, gesture.vertex, gesture.corner) }
    }
  }
  function up(event: PointerEvent) {
    if (!gesture) return
    if (painting && onMaskChange && canvas) canvas.toBlob((blob) => { if (blob) onMaskChange?.(blob) }, 'image/png')
    if (box?.kind === 'box' && box.width > .0001 && box.height > .0001) onCreate(box)
    if (preview) onGeometryChange(preview.id, preview.geometry)
    gesture = null; box = null; preview = null
    if (stage?.hasPointerCapture?.(event.pointerId)) stage.releasePointerCapture(event.pointerId)
  }
  function cancel() { gesture = null; box = null; preview = null }
  function key(event: KeyboardEvent) {
    if (disabled) return
    if (event.key === 'Escape') { points = []; cancel() }
    if (event.key === 'Enter' && points.length >= 3) {
      onCreate({ kind: 'polygon', points }); points = []; event.preventDefault()
    }
    if ((event.key === 'Delete' || event.key === 'Backspace') && selectedId && tool === 'select') {
      onDelete?.(selectedId); event.preventDefault()
    }
  }
</script>

{#snippet shape(geometry: RegionGeometry, id: string)}
  {#if geometry.kind === 'box'}
    <rect x={geometry.x * image.width} y={geometry.y * image.height} width={geometry.width * image.width} height={geometry.height * image.height} />
  {:else if geometry.kind === 'polygon'}
    <polygon points={geometry.points.map((point) => `${point.x * image.width},${point.y * image.height}`).join(' ')} />
  {:else}
    <defs><mask id={`${maskPrefix}-${id}`}><image href={geometry.url} width={image.width} height={image.height} /></mask></defs>
    <rect width={image.width} height={image.height} fill="var(--tint-accent)" stroke="none" opacity="0.45" mask={`url(#${maskPrefix}-${id})`} />
  {/if}
{/snippet}

<div data-tint-annotation-canvas="" class={['annotation-canvas', className].filter(Boolean).join(' ')}>
  <!-- The drawing surface is one keyboard-operated application, with focus on its stage. -->
  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <div bind:this={stage} class="stage" style:width={`${image.width * zoom}px`} style:height={`${image.height * zoom}px`}
    role="application" aria-label="Annotation editor. Draw regions; Enter completes a polygon; Escape cancels." tabindex="0"
    onpointerdown={down} onpointermove={move} onpointerup={up} onpointercancel={cancel} onkeydown={key}>
    <img src={image.url} alt="Annotation source frame" draggable="false" />
    <canvas bind:this={canvas} width={image.width} height={image.height} aria-hidden="true" class:painting></canvas>
    <svg bind:this={svg} viewBox={`0 0 ${image.width} ${image.height}`} width="100%" height="100%" aria-hidden="true"
      style:cursor={tool === 'select' ? 'default' : 'crosshair'}>
      {#each rendered as region (region.id)}
        <g data-region-id={region.id} aria-label={region.label}
          stroke={region.id === selectedId ? 'var(--tint-accent)' : region.tone === 'accepted' ? 'var(--tint-success)' : 'var(--tint-info)'}
          stroke-width={2 / zoom} fill="transparent" stroke-dasharray={region.tone === 'proposal' ? `${6 / zoom} ${4 / zoom}` : undefined}>
          {@render shape(preview?.id === region.id ? preview.geometry : region.geometry, region.id)}
          {#if region.id === selectedId && tool === 'select' && region.geometry.kind === 'polygon'}
            {#each region.geometry.points as point, index (index)}<circle data-vertex={index} cx={point.x * image.width} cy={point.y * image.height} r={5 / zoom} fill="var(--tint-accent)" />{/each}
          {:else if region.id === selectedId && tool === 'select' && region.geometry.kind === 'box'}
            <rect data-corner="" x={(region.geometry.x + region.geometry.width) * image.width - 5 / zoom} y={(region.geometry.y + region.geometry.height) * image.height - 5 / zoom} width={10 / zoom} height={10 / zoom} fill="var(--tint-accent)" />
          {/if}
        </g>
      {/each}
      {#if box}<g stroke="var(--tint-accent)" fill="transparent" stroke-width={2 / zoom}>{@render shape(box, 'preview')}</g>{/if}
      {#if points.length}<polyline points={points.map((point) => `${point.x * image.width},${point.y * image.height}`).join(' ')} stroke="var(--tint-accent)" fill="transparent" stroke-width={2 / zoom} />{/if}
    </svg>
  </div>
  {#if rendered.length > 0}
    <ul class="region-list" aria-label="Annotation regions">
      {#each rendered as region (region.id)}
        <li><button type="button" aria-pressed={region.id === selectedId} {disabled}
          onclick={() => onSelect(region.id)}>{region.label}{region.tone ? ` · ${region.tone}` : ''}</button></li>
      {/each}
    </ul>
  {/if}
</div>

<style>
  .annotation-canvas { max-width: 100%; overflow: auto; }
  .stage { position: relative; margin: auto; }
  img, canvas { position: absolute; width: 100%; height: 100%; }
  canvas { opacity: 0; mix-blend-mode: screen; pointer-events: none; }
  canvas.painting { opacity: .5; }
  svg { position: relative; touch-action: none; }
  .stage:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .region-list { display: flex; flex-wrap: wrap; gap: var(--tint-space-2); margin: var(--tint-space-2) 0 0; padding: 0; list-style: none; }
  .region-list button { border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); padding: var(--tint-space-1) var(--tint-space-2); background: var(--tint-panel); color: var(--tint-ink); cursor: pointer; }
  .region-list button[aria-pressed='true'] { border-color: var(--tint-accent); background: var(--tint-accent-soft); }
  .region-list button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .region-list button:disabled { opacity: .55; cursor: not-allowed; }
</style>

// src/components/annotation/AnnotationCanvas.tsx
import { useEffect, useId, useRef, useState, type PointerEvent, type KeyboardEvent } from 'react'
import type { Point, VectorGeometry } from './geometry'

export type RegionGeometry = VectorGeometry | { kind: 'mask'; url: string }
export type AnnotationRegion = { id: string; label: string; geometry: RegionGeometry; tone?: 'proposal' | 'accepted' | 'draft'; hidden?: boolean }
export type AnnotationTool = 'select' | 'box' | 'polygon' | 'brush' | 'erase'
export type AnnotationCanvasProps = {
  image: { id: string; url: string; width: number; height: number }
  regions: readonly AnnotationRegion[]
  selectedId?: string | null
  tool: AnnotationTool
  zoom?: number
  brushSize?: number
  disabled?: boolean
  onSelect(id: string | null): void
  onCreate(geometry: VectorGeometry): void
  onGeometryChange(id: string, geometry: VectorGeometry): void
  onMaskChange?(blob: Blob): void
  onDelete?(id: string): void
  className?: string
}

const clamp = (n: number) => Math.max(0, Math.min(1,n))

/** Controlled annotation interaction. The host owns frames, labels, review and artifact storage. */
export function AnnotationCanvas({ image, regions, selectedId, tool, zoom = 1, brushSize = 20, disabled,
  onSelect, onCreate, onGeometryChange, onMaskChange, onDelete, className }: AnnotationCanvasProps) {
  const maskPrefix = useId()
  const pendingBox = useRef<VectorGeometry | null>(null)
  const pendingPreview = useRef<{id:string;geometry:VectorGeometry}|null>(null)
  const svg = useRef<SVGSVGElement>(null)
  const canvas = useRef<HTMLCanvasElement>(null)
  const gesture = useRef<{ start: Point; region?: AnnotationRegion; vertex?: number; corner?: boolean } | null>(null)
  const [box, setBox] = useState<VectorGeometry | null>(null)
  const [points, setPoints] = useState<Point[]>([])
  const [preview, setPreview] = useState<{ id: string; geometry: VectorGeometry } | null>(null)
  const selected = regions.find(r => r.id === selectedId)
  const maskUrl = selected?.geometry.kind === 'mask' ? selected.geometry.url : undefined
  const painting = tool === 'brush' || tool === 'erase'
  useEffect(() => { setPoints([]); setBox(null); setPreview(null); gesture.current = null }, [image.id, tool])
  useEffect(() => {
    const target = canvas.current
    const context = target?.getContext('2d')
    if (!target || !context) return
    let active = true
    context.clearRect(0,0,image.width,image.height)
    if (maskUrl) {
      const bitmap = new Image()
      bitmap.crossOrigin = 'anonymous'
      bitmap.onload = () => { if (active) context.drawImage(bitmap,0,0,image.width,image.height) }
      bitmap.src = maskUrl
    }
    return () => { active = false }
  }, [image.id, image.width, image.height, maskUrl, selectedId])

  const position = (e: PointerEvent) => {
    const rect = svg.current!.getBoundingClientRect()
    return { x: clamp((e.clientX-rect.left)/rect.width), y: clamp((e.clientY-rect.top)/rect.height) }
  }
  const draw = (from: Point, to: Point) => {
    const ctx = canvas.current?.getContext('2d')
    if (!ctx) return
    ctx.globalCompositeOperation = tool === 'erase' ? 'destination-out' : 'source-over'
    ctx.strokeStyle = 'white'; ctx.lineWidth = brushSize; ctx.lineCap = 'round'
    ctx.beginPath(); ctx.moveTo(from.x*image.width,from.y*image.height)
    ctx.lineTo(to.x*image.width,to.y*image.height); ctx.stroke()
  }
  const down = (e: PointerEvent<SVGSVGElement>) => {
    if (disabled || e.button !== 0) return
    e.currentTarget.focus()
    const p = position(e)
    if (tool === 'polygon') { setPoints(current => [...current,p]); return }
    const element = e.target as SVGElement
    const id = element.closest('[data-region-id]')?.getAttribute('data-region-id')
    const region = regions.find(r => r.id === id)
    if (tool === 'select') onSelect(region?.id ?? null)
    const vertex = element.getAttribute('data-vertex')
    gesture.current = { start: p, region, vertex: vertex == null ? undefined : Number(vertex), corner: element.hasAttribute('data-corner') }
    e.currentTarget.setPointerCapture(e.pointerId)
    if (painting) draw(p, { x:p.x+.00001,y:p.y+.00001 })
  }
  const move = (e: PointerEvent<SVGSVGElement>) => {
    const current = gesture.current
    if (!current || disabled) return
    const p = position(e), start = current.start
    if (painting) { draw(start,p); current.start=p; return }
    if (tool === 'box') {
      const next:VectorGeometry={ kind:'box',x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),width:Math.abs(p.x-start.x),height:Math.abs(p.y-start.y) }
      pendingBox.current=next;setBox(next)
    } else if (tool === 'select' && current.region && current.region.geometry.kind !== 'mask') {
      const g=current.region.geometry
      let next: VectorGeometry
      if (g.kind === 'polygon') {
        const dx=Math.max(-Math.min(...g.points.map(v=>v.x)),Math.min(1-Math.max(...g.points.map(v=>v.x)),p.x-start.x))
        const dy=Math.max(-Math.min(...g.points.map(v=>v.y)),Math.min(1-Math.max(...g.points.map(v=>v.y)),p.y-start.y))
        next={ kind:'polygon',points:g.points.map((v,i)=>current.vertex == null ? {x:v.x+dx,y:v.y+dy} : i===current.vertex ? p : v) }
      } else if (current.corner) next={...g,width:Math.max(.0001,p.x-g.x),height:Math.max(.0001,p.y-g.y)}
      else next={...g,x:Math.max(0,Math.min(1-g.width,g.x+p.x-start.x)),y:Math.max(0,Math.min(1-g.height,g.y+p.y-start.y))}
      pendingPreview.current={id:current.region.id,geometry:next};setPreview(pendingPreview.current)
    }
  }
  const up = (e: PointerEvent<SVGSVGElement>) => {
    if (!gesture.current) return
    if (painting && onMaskChange) canvas.current?.toBlob(blob => { if (blob) onMaskChange(blob) },'image/png')
    const box=pendingBox.current,preview=pendingPreview.current
    if (box?.kind === 'box' && box.width>.0001 && box.height>.0001) onCreate(box)
    if (preview) onGeometryChange(preview.id,preview.geometry)
    gesture.current=null; pendingBox.current=null;pendingPreview.current=null;setBox(null); setPreview(null)
    if (e.currentTarget.hasPointerCapture(e.pointerId)) e.currentTarget.releasePointerCapture(e.pointerId)
  }
  const key = (e: KeyboardEvent) => {
    if (disabled) return
    if (e.key === 'Escape') { setPoints([]); gesture.current=null; pendingBox.current=null;pendingPreview.current=null;setBox(null); setPreview(null) }
    if (e.key === 'Enter' && points.length>=3) { onCreate({kind:'polygon',points}); setPoints([]); e.preventDefault() }
    if ((e.key === 'Delete' || e.key === 'Backspace') && selectedId && tool==='select') { onDelete?.(selectedId); e.preventDefault() }
  }
  const shape = (g: RegionGeometry, id = "preview") => g.kind==='box'
    ? <rect x={g.x*image.width} y={g.y*image.height} width={g.width*image.width} height={g.height*image.height}/>
    : g.kind==='polygon' ? <polygon points={g.points.map(p=>`${p.x*image.width},${p.y*image.height}`).join(' ')}/>
    : <><defs><mask id={`${maskPrefix}-${id}`}><image href={g.url} width={image.width} height={image.height}/></mask></defs><rect width={image.width} height={image.height} fill="var(--tint-accent)" stroke="none" opacity={.45} mask={`url(#${maskPrefix}-${id})`}/></>
  const rendered = regions.filter(r=>!r.hidden)
  return <div className={className} data-annotation-canvas="">
    <div style={{position:'relative',width:image.width*zoom,height:image.height*zoom,margin:'auto'}}>
      <img src={image.url} alt="Annotation source frame" draggable={false} style={{position:'absolute',width:'100%',height:'100%'}}/>
      <canvas ref={canvas} width={image.width} height={image.height} aria-hidden="true" style={{position:'absolute',width:'100%',height:'100%',opacity: painting ? .5 : 0,mixBlendMode:'screen',pointerEvents:'none'}}/>
      <svg ref={svg} viewBox={`0 0 ${image.width} ${image.height}`} width="100%" height="100%" tabIndex={0}
        role="application" aria-label="Annotation editor. Draw regions; Enter completes a polygon; Escape cancels."
        onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current=null;setBox(null);setPreview(null)}} onKeyDown={key}
        style={{position:'relative',touchAction:'none',cursor:tool==='select'?'default':'crosshair'}}>
        {rendered.map(region => <g key={region.id} data-region-id={region.id} aria-label={region.label}
          stroke={region.id===selectedId?'var(--tint-accent)':region.tone==='accepted'?'var(--tint-success)':'var(--tint-info)'} strokeWidth={2/zoom}
          fill="transparent" strokeDasharray={region.tone==='proposal'?`${6/zoom} ${4/zoom}`:undefined}>
          {shape(preview?.id===region.id?preview.geometry:region.geometry,region.id)}
          {region.id===selectedId && tool==='select' && region.geometry.kind==='polygon' ? region.geometry.points.map((p,i)=><circle key={i} data-vertex={i} cx={p.x*image.width} cy={p.y*image.height} r={5/zoom} fill="var(--tint-accent)"/>) : null}
          {region.id===selectedId && tool==='select' && region.geometry.kind==='box' ? <rect data-corner="" x={(region.geometry.x+region.geometry.width)*image.width-5/zoom} y={(region.geometry.y+region.geometry.height)*image.height-5/zoom} width={10/zoom} height={10/zoom} fill="var(--tint-accent)"/> : null}
        </g>)}
        {box ? <g stroke="var(--tint-accent)" fill="transparent" strokeWidth={2/zoom}>{shape(box)}</g>:null}
        {points.length ? <polyline points={points.map(p=>`${p.x*image.width},${p.y*image.height}`).join(' ')} stroke="var(--tint-accent)" fill="transparent" strokeWidth={2/zoom}/>:null}
      </svg>
    </div>
  </div>
}
