// src/svelte/components/media/VolumeControl.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Volume1, Volume2, VolumeX } from '@lucide/svelte'
  import { clampPercent } from '../../../core/media/model'
  import Icon from '../icon/Icon.svelte'
  import Slider from './Slider.svelte'

  type Props = {
    /** Unit interval, 0–1. */
    volume: number
    isMuted: boolean
    onVolumeChange: (percentage: number) => void
    onToggleMute: () => void
    /** Optional controlled drawer state. */
    open?: boolean
    onOpenChange?: (open: boolean) => void
    tone?: 'chrome' | 'surface'
    class?: string
  }

  let {
    volume, isMuted, onVolumeChange, onToggleMute, open: controlledOpen,
    onOpenChange, tone = 'chrome', class: className,
  }: Props = $props()
  const drawerId = $props.id()
  let root = $state<HTMLDivElement>(null!)
  let input = $state<HTMLInputElement>()
  let localOpen = $state(false)
  let editing = $state(false)
  let inputValue = $state('100')
  let closeTimer: ReturnType<typeof setTimeout> | undefined
  let isOpen = $derived(controlledOpen ?? localOpen)
  let displayVolume = $derived(isMuted ? 0 : clampPercent(volume * 100))
  let volumeGlyph = $derived(isMuted || volume === 0 ? VolumeX : volume > .5 ? Volume2 : Volume1)

  $effect(() => { if (!editing) inputValue = String(Math.round(displayVolume)) })

  function setOpen(next: boolean) {
    if (controlledOpen === undefined) localOpen = next
    onOpenChange?.(next)
    if (!next) editing = false
  }

  function openDrawer() {
    clearTimeout(closeTimer)
    if (!isOpen) setOpen(true)
  }

  function scheduleClose() {
    if (editing) return
    clearTimeout(closeTimer)
    closeTimer = setTimeout(() => setOpen(false), 160)
  }

  function commitInput() {
    const next = Math.round(clampPercent(Number(inputValue)))
    inputValue = String(next)
    onVolumeChange(next)
    editing = false
  }

  function onInputKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      event.preventDefault()
      commitInput()
      input?.blur()
    } else if (event.key === 'ArrowUp' || event.key === 'ArrowDown') {
      event.preventDefault()
      const next = Math.round(clampPercent(Number(inputValue || displayVolume) + (event.key === 'ArrowUp' ? 1 : -1)))
      inputValue = String(next)
      onVolumeChange(next)
    }
  }

  onMount(() => {
    const onPointerDown = (event: PointerEvent) => {
      if (isOpen && event.target instanceof Node && !root.contains(event.target)) {
        if (editing) commitInput()
        setOpen(false)
      }
    }
    const onKeydown = (event: KeyboardEvent) => {
      if (!isOpen || event.key !== 'Escape') return
      event.preventDefault()
      if (editing) {
        inputValue = String(Math.round(displayVolume))
        editing = false
        input?.blur()
      } else setOpen(false)
    }
    document.addEventListener('pointerdown', onPointerDown)
    document.addEventListener('keydown', onKeydown)
    return () => {
      clearTimeout(closeTimer)
      document.removeEventListener('pointerdown', onPointerDown)
      document.removeEventListener('keydown', onKeydown)
    }
  })
</script>

<div
  bind:this={root}
  role="group"
  aria-label="Volume controls"
  class={['tint-volume', className].filter(Boolean).join(' ')}
  data-tone={tone}
  onpointerenter={openDrawer}
  onpointerleave={scheduleClose}
  onfocusin={openDrawer}
  onfocusout={(event) => { if (!root.contains(event.relatedTarget as Node | null)) scheduleClose() }}
>
  <button
    type="button"
    class="mute-button"
    aria-label={isMuted ? 'Unmute' : 'Mute'}
    aria-expanded={isOpen}
    aria-controls={drawerId}
    onclick={onToggleMute}
  ><Icon icon={volumeGlyph} /></button>

  {#if isOpen}
    <div id={drawerId} role="dialog" aria-label="Volume" class="drawer">
      <form onsubmit={(event) => { event.preventDefault(); commitInput() }}>
        <input
          bind:this={input}
          type="text"
          inputmode="numeric"
          pattern="[0-9]*"
          aria-label="Volume percentage"
          value={inputValue}
          onfocus={() => { editing = true; openDrawer() }}
          onblur={() => { if (editing) commitInput() }}
          oninput={(event) => { editing = true; inputValue = event.currentTarget.value.replace(/[^\d]/g, '').slice(0, 3) }}
          onkeydown={onInputKeydown}
        />
      </form>
      <div class="range"><Slider orientation="vertical" value={displayVolume} onChange={(value) => { editing = false; onVolumeChange(value) }} aria-label="Volume" /></div>
    </div>
  {/if}
</div>

<style>
  .tint-volume { position: relative; color: var(--tint-chrome-ink); }
  .tint-volume[data-tone='surface'] { color: var(--tint-ink); }
  .mute-button { display: inline-grid; width: 2rem; height: 2rem; place-items: center; border: 0; border-radius: var(--tint-radius-sm); background: transparent; color: inherit; cursor: pointer; }
  .mute-button:hover, .mute-button[aria-expanded='true'] { background: color-mix(in srgb, currentColor 12%, transparent); }
  .mute-button:focus-visible { outline: 2px solid var(--tint-accent); outline-offset: 2px; }
  .drawer { position: absolute; bottom: calc(100% + .5rem); left: 50%; z-index: 30; display: flex; width: 3.5rem; height: 9rem; flex-direction: column; align-items: center; padding: .5rem .5rem .75rem; border: 1px solid var(--tint-chrome-border); border-radius: var(--tint-radius-lg); background: var(--tint-chrome); box-shadow: 0 12px 32px var(--tint-shadow-color); transform: translateX(-50%); }
  [data-tone='surface'] .drawer { border-color: var(--tint-border); background: var(--tint-panel); }
  form { width: 100%; margin-bottom: .625rem; }
  input { width: 100%; border: 0; border-bottom: 1px solid currentColor; background: transparent; color: inherit; font: inherit; font-size: .6875rem; font-variant-numeric: tabular-nums; text-align: center; outline: none; }
  input:focus-visible { border-color: var(--tint-accent); }
  .range { display: flex; min-height: 0; width: 100%; flex: 1; justify-content: center; }
</style>

// src/components/video-player/VolumeControl.tsx
import { useEffect, useRef, useState, type FormEvent, type KeyboardEvent } from 'react'
import { Volume1, Volume2, VolumeX } from 'lucide-react'
import { AnimatePresence, motion } from 'motion/react'
import { cn } from '@/lib/utils'
import { Icon } from '@/components/icon'
import { Slider } from './Slider'

export type VolumeControlProps = {
  volume: number
  isMuted: boolean
  onVolumeChange: (value: number) => void
  onToggleMute: () => void
  onOpenChange?: (open: boolean) => void
  className?: string
}

function clampVolume(value: number) {
  if (!Number.isFinite(value)) return 0
  return Math.min(Math.max(Math.round(value), 0), 100)
}

export function VolumeControl({
  volume,
  isMuted,
  onVolumeChange,
  onToggleMute,
  onOpenChange,
  className,
}: VolumeControlProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)
  const closeTimerRef = useRef<number | null>(null)
  const onOpenChangeRef = useRef(onOpenChange)
  const onVolumeChangeRef = useRef(onVolumeChange)
  const inputValueRef = useRef('100')
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState(false)
  const [inputValue, setInputValue] = useState('100')
  const displayVolume = isMuted ? 0 : volume * 100
  const VolumeIcon = isMuted || volume === 0 ? VolumeX : volume > 0.5 ? Volume2 : Volume1

  useEffect(() => {
    onOpenChangeRef.current = onOpenChange
  }, [onOpenChange])

  useEffect(() => {
    onVolumeChangeRef.current = onVolumeChange
  }, [onVolumeChange])

  useEffect(() => {
    inputValueRef.current = inputValue
  }, [inputValue])

  useEffect(() => {
    if (!editing) {
      setInputValue(String(Math.round(displayVolume)))
    }
  }, [displayVolume, editing])

  const clearCloseTimer = () => {
    if (closeTimerRef.current != null) {
      window.clearTimeout(closeTimerRef.current)
      closeTimerRef.current = null
    }
  }

  const setDrawerOpen = (next: boolean) => {
    setOpen(next)
    onOpenChangeRef.current?.(next)
    if (!next) {
      setEditing(false)
    }
  }

  const openDrawer = () => {
    clearCloseTimer()
    setDrawerOpen(true)
  }

  const scheduleClose = () => {
    if (editing) return
    clearCloseTimer()
    closeTimerRef.current = window.setTimeout(() => setDrawerOpen(false), 160)
  }

  const commitInputValue = () => {
    const parsed = clampVolume(Number(inputValueRef.current))
    setInputValue(String(parsed))
    onVolumeChangeRef.current(parsed)
    setEditing(false)
  }

  useEffect(() => () => clearCloseTimer(), [])

  useEffect(() => {
    if (!open) return

    const onPointerDown = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) {
        if (editing) {
          const parsed = clampVolume(Number(inputValueRef.current))
          setInputValue(String(parsed))
          onVolumeChangeRef.current(parsed)
        }
        setOpen(false)
        onOpenChangeRef.current?.(false)
        setEditing(false)
      }
    }

    const onKeyDown = (event: globalThis.KeyboardEvent) => {
      if (event.key === 'Escape') {
        if (editing) {
          setInputValue(String(Math.round(displayVolume)))
          setEditing(false)
          inputRef.current?.blur()
          return
        }
        setOpen(false)
        onOpenChangeRef.current?.(false)
      }
    }

    document.addEventListener('mousedown', onPointerDown)
    document.addEventListener('keydown', onKeyDown)
    return () => {
      document.removeEventListener('mousedown', onPointerDown)
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [open, editing, displayVolume])

  const onInputKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      event.preventDefault()
      commitInputValue()
      inputRef.current?.blur()
    }
    if (event.key === 'ArrowUp') {
      event.preventDefault()
      const next = clampVolume(Number(inputValue || displayVolume) + 1)
      setInputValue(String(next))
      onVolumeChange(next)
    }
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      const next = clampVolume(Number(inputValue || displayVolume) - 1)
      setInputValue(String(next))
      onVolumeChange(next)
    }
  }

  const onInputSubmit = (event: FormEvent) => {
    event.preventDefault()
    commitInputValue()
  }

  return (
    <div
      ref={rootRef}
      className={cn('relative', className)}
      onMouseEnter={openDrawer}
      onMouseLeave={scheduleClose}
      onFocusCapture={openDrawer}
      onBlurCapture={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget as Node | null)) {
          scheduleClose()
        }
      }}
    >
      <motion.button
        type="button"
        whileHover={{ scale: 1.08 }}
        whileTap={{ scale: 0.94 }}
        onClick={onToggleMute}
        aria-label={isMuted ? 'Unmute' : 'Mute'}
        aria-expanded={open}
        aria-controls="tint-volume-drawer"
        className={cn(
          'inline-flex size-8 items-center justify-center rounded-md text-tint-chrome-ink transition-colors hover:bg-tint-chrome-ink/12',
          open && 'bg-tint-chrome-ink/12',
        )}
      >
        <Icon icon={VolumeIcon} />
      </motion.button>

      <AnimatePresence>
        {open ? (
          <motion.div
            id="tint-volume-drawer"
            role="dialog"
            aria-label="Volume"
            initial={{ opacity: 0, y: 8, scale: 0.96 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 8, scale: 0.96 }}
            transition={{ duration: 0.18, ease: 'easeOut' }}
            className="absolute bottom-[calc(100%+0.5rem)] left-1/2 z-30 flex h-36 w-14 -translate-x-1/2 flex-col items-center rounded-xl border border-tint-chrome-border bg-tint-chrome px-2 pt-2 pb-3 shadow-[0_12px_32px_var(--tint-shadow-color)] backdrop-blur-xl"
            onMouseDown={(event) => event.stopPropagation()}
          >
            <form onSubmit={onInputSubmit} className="mb-2.5 w-full">
              <input
                ref={inputRef}
                type="text"
                inputMode="numeric"
                pattern="[0-9]*"
                value={inputValue}
                aria-label="Volume percentage"
                onFocus={() => {
                  setEditing(true)
                  openDrawer()
                }}
                onBlur={commitInputValue}
                onChange={(event) => {
                  const next = event.target.value.replace(/[^\d]/g, '').slice(0, 3)
                  setEditing(true)
                  setInputValue(next)
                }}
                onKeyDown={onInputKeyDown}
                className="w-full border-0 border-b border-tint-chrome-ink/35 bg-transparent px-0.5 py-0.5 text-center text-[11px] font-medium text-tint-chrome-ink tabular-nums outline-none placeholder:text-tint-chrome-ink/35 focus:border-tint-chrome-ink/70"
              />
            </form>
            <div className="flex min-h-0 w-full flex-1 justify-center">
              <Slider
                orientation="vertical"
                value={displayVolume}
                onChange={(value) => {
                  setEditing(false)
                  onVolumeChange(value)
                }}
                aria-label="Volume"
                className="h-full"
              />
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  )
}
