// src/components/feed/NarrationTransport.tsx
import {
  useEffect,
  useId,
  useRef,
  useState,
  type HTMLAttributes,
} from 'react'
import { Pause, Play, SkipBack, SkipForward } from 'lucide-react'
import { Button } from '../button'
import { Icon } from '../icon'
import { ProgressBar } from '../progress'
import { cn } from '../../lib/utils'

export type NarrationTransportProps = Omit<HTMLAttributes<HTMLDivElement>, 'onRateChange'> & {
  /** Host-owned audio URL (cached clip). Same seam as chat enableSpeak / MAYA_TTS_SRC. */
  src: string
  label?: string
  /** Playback rates offered in the speed control. */
  rates?: readonly number[]
  onEnded?: () => void
}

const DEFAULT_RATES = [0.75, 1, 1.25, 1.5, 2] as const

/**
 * Play / pause / skip / speed / progress over a host-supplied `src`.
 *
 * Tint never fetches TTS — the host passes a URL the way chat demos pass
 * `MAYA_TTS_SRC`, so the transport works offline against cached fixtures.
 */
export function NarrationTransport({
  src,
  label = 'Narration',
  rates = DEFAULT_RATES,
  onEnded,
  className,
  ...props
}: NarrationTransportProps) {
  const audioRef = useRef<HTMLAudioElement | null>(null)
  const labelId = useId()
  const [playing, setPlaying] = useState(false)
  const [current, setCurrent] = useState(0)
  const [duration, setDuration] = useState(0)
  const [rate, setRate] = useState(1)

  useEffect(() => {
    const audio = audioRef.current
    if (!audio) return
    audio.pause()
    audio.load()
    setPlaying(false)
    setCurrent(0)
    setDuration(0)
  }, [src])

  useEffect(() => {
    const audio = audioRef.current
    if (!audio) return
    audio.playbackRate = rate
  }, [rate])

  const toggle = () => {
    const audio = audioRef.current
    if (!audio) return
    if (audio.paused) {
      void audio.play().then(() => setPlaying(true))
    } else {
      audio.pause()
      setPlaying(false)
    }
  }

  const skip = (delta: number) => {
    const audio = audioRef.current
    if (!audio) return
    audio.currentTime = Math.max(0, Math.min(audio.duration || 0, audio.currentTime + delta))
    setCurrent(audio.currentTime)
  }

  const progress = duration > 0 ? (current / duration) * 100 : 0

  return (
    <div
      data-tint-narration-transport=""
      className={cn('flex flex-col gap-2', className)}
      {...props}
    >
      <audio
        ref={audioRef}
        src={src}
        preload="metadata"
        onTimeUpdate={(event) => setCurrent(event.currentTarget.currentTime)}
        onLoadedMetadata={(event) => setDuration(event.currentTarget.duration || 0)}
        onPlay={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        onEnded={() => {
          setPlaying(false)
          onEnded?.()
        }}
      />
      <div className="flex items-center gap-2">
        <p id={labelId} className="m-0 min-w-0 flex-1 truncate text-xs font-medium text-tint-muted">
          {label}
        </p>
        <Button
          size="sm"
          variant="ghost"
          aria-label="Skip back 10 seconds"
          onClick={() => skip(-10)}
          leading={<Icon icon={SkipBack} size="sm" />}
        />
        <Button
          size="sm"
          variant="secondary"
          aria-labelledby={labelId}
          aria-pressed={playing}
          onClick={toggle}
          leading={<Icon icon={playing ? Pause : Play} size="sm" />}
        >
          {playing ? 'Pause' : 'Play'}
        </Button>
        <Button
          size="sm"
          variant="ghost"
          aria-label="Skip forward 10 seconds"
          onClick={() => skip(10)}
          leading={<Icon icon={SkipForward} size="sm" />}
        />
        <label className="flex items-center gap-1 text-xs text-tint-muted">
          <span className="sr-only">Playback speed</span>
          <select
            className="rounded-md border border-tint-border bg-tint-surface px-1.5 py-1 text-xs text-tint-ink"
            value={rate}
            onChange={(event) => setRate(Number(event.target.value))}
          >
            {rates.map((value) => (
              <option key={value} value={value}>
                {value}×
              </option>
            ))}
          </select>
        </label>
      </div>
      <ProgressBar value={progress} label={`${label} progress`} showValue={false} />
    </div>
  )
}

// src/svelte/components/feed/NarrationTransport.svelte
<script lang="ts">
  import { DEFAULT_NARRATION_RATES, narrationProgress, narrationTimeAfterSkip } from '../../../core/feed'
  import ProgressBar from '../progress/ProgressBar.svelte'
  import type { NarrationTransportProps } from './types'

  let {
    src, label = 'Narration', rates = DEFAULT_NARRATION_RATES, onEnded,
    class: className, ...rest
  }: NarrationTransportProps = $props()

  let audio = $state<HTMLAudioElement>()
  let playing = $state(false)
  let current = $state(0)
  let duration = $state(0)
  let rate = $state(1)
  let progress = $derived(narrationProgress(current, duration))

  $effect(() => {
    const node = audio
    void src
    if (!node) return
    node.pause()
    node.load()
    playing = false
    current = 0
    duration = 0
  })

  $effect(() => {
    const node = audio
    if (node) node.playbackRate = rate
  })

  function toggle() {
    const node = audio
    if (!node) return
    if (node.paused) {
      void Promise.resolve(node.play()).then(() => { playing = true }).catch(() => { playing = false })
    } else {
      node.pause()
      playing = false
    }
  }

  function skip(delta: number) {
    const node = audio
    if (!node) return
    node.currentTime = narrationTimeAfterSkip(node.currentTime, delta, node.duration)
    current = node.currentTime
  }
</script>

<div {...rest} data-tint-narration-transport="" class={['narration-transport', className].filter(Boolean).join(' ')}>
  <audio
    bind:this={audio} {src} preload="metadata"
    ontimeupdate={(event) => { current = event.currentTarget.currentTime }}
    onloadedmetadata={(event) => { duration = event.currentTarget.duration || 0 }}
    onplay={() => { playing = true }}
    onpause={() => { playing = false }}
    onended={() => { playing = false; onEnded?.() }}
  ></audio>
  <div class="controls">
    <p class="label">{label}</p>
    <button type="button" aria-label="Skip back 10 seconds" onclick={() => skip(-10)}><span aria-hidden="true">↶</span></button>
    <button type="button" class="toggle" aria-label={`${playing ? 'Pause' : 'Play'} ${label}`} aria-pressed={playing} onclick={toggle}>
      <span aria-hidden="true">{playing ? 'Ⅱ' : '▶'}</span><span>{playing ? 'Pause' : 'Play'}</span>
    </button>
    <button type="button" aria-label="Skip forward 10 seconds" onclick={() => skip(10)}><span aria-hidden="true">↷</span></button>
    <label class="speed"><span class="sr-only">Playback speed</span><select class="tint-select" aria-label="Playback speed" value={rate} onchange={(event) => { rate = Number(event.currentTarget.value) }}>
      {#each rates as value (value)}<option value={value}>{value}×</option>{/each}
    </select></label>
  </div>
  <ProgressBar value={progress} label={`${label} progress`} showValue={false} />
</div>

<style>
  .narration-transport { container-type: inline-size; display: flex; min-width: 0; flex-direction: column; gap: var(--tint-space-2); }
  .controls { display: flex; align-items: center; gap: var(--tint-space-2); }
  .label { min-width: 0; flex: 1; overflow: hidden; margin: 0; color: var(--tint-muted); font-size: var(--tint-font-size-xs); font-weight: 500; text-overflow: ellipsis; white-space: nowrap; }
  button { display: inline-flex; min-width: 2.25rem; min-height: 2.25rem; flex: none; align-items: center; justify-content: center; gap: var(--tint-space-1); border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-panel); padding: 0 var(--tint-space-2); color: var(--tint-ink); cursor: pointer; font: inherit; font-size: var(--tint-font-size-sm); }
  button:hover { background: var(--tint-accent-soft); }
  button:focus-visible, select:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .speed { display: flex; align-items: center; color: var(--tint-muted); font-size: var(--tint-font-size-xs); }
  select { border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-surface); padding: var(--tint-space-1); color: var(--tint-ink); font: inherit; }
  .sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip-path: inset(50%); white-space: nowrap; }
  @container (max-width: 400px) { .controls { flex-wrap: wrap; } .label { flex-basis: 100%; } }
</style>
