// src/docs/policy/PolicyDoc.tsx
import { useMemo, useState, useSyncExternalStore } from 'react'
import {
  applyPolicyCommand,
  PolicyDryRun,
  PolicyEditor,
  PolicyTable,
  type PolicyRule,
} from '../../components/policy'
import { InteractiveGraphView } from '../../components/graph'
import '../../components/graph/graph.css'
import { CodeBlock } from '../components/CodeBlock'
import { DocsPage, DocsPreview, DocsSection } from '../components/DocsPage'
import { PropsTable } from '../components/PropsTable'
import {
  dispatchPolicyCommand,
  getDemoFeedStore,
  subscribeDemoFeedStore,
  upsertPolicyRule,
} from '../feed/demoStore'
import { Button } from '../../components/button'
import { createWorkflowNodeRegistry } from './workflowDefinitions'
import { workflowForName } from './workflowFixtures'

const usage = `import { PolicyTable, PolicyEditor, PolicyDryRun, applyPolicyCommand } from '@nebula/tint/policy'`

function PolicyWorkbench() {
  const { feed, policy } = useSyncExternalStore(
    subscribeDemoFeedStore,
    getDemoFeedStore,
    getDemoFeedStore,
  )
  const [selectedId, setSelectedId] = useState(policy.rules[0]?.id ?? null)
  const [draft, setDraft] = useState<PolicyRule | null>(policy.rules[0] ?? null)

  const sourceLabels = useMemo(
    () => Object.fromEntries(feed.sources.map((source) => [source.id, source.handle])),
    [feed.sources],
  )
  const sources = useMemo(
    () => feed.sources.map((source) => ({ id: source.id, label: source.handle })),
    [feed.sources],
  )

  const selectedRule =
    draft && draft.id === selectedId
      ? draft
      : (policy.rules.find((rule) => rule.id === selectedId) ?? policy.rules[0])

  const source = feed.sources.find((item) => item.id === selectedRule?.sourceId)
  const workflow = workflowForName(source?.workflowName ?? 'youtube-poll')
  const registry = useMemo(() => createWorkflowNodeRegistry(), [])

  return (
    <div className="flex flex-col gap-6">
      <PolicyTable
        rules={policy.rules}
        selectedId={selectedRule?.id ?? null}
        sourceLabels={sourceLabels}
        onSelect={(ruleId) => {
          setSelectedId(ruleId)
          setDraft(policy.rules.find((rule) => rule.id === ruleId) ?? null)
        }}
        onToggle={(ruleId, enabled) => {
          dispatchPolicyCommand({ type: 'policy.toggle', ruleId, enabled })
          setSelectedId(ruleId)
          const next = applyPolicyCommand(policy, {
            type: 'policy.toggle',
            ruleId,
            enabled,
          })
          setDraft(next.rules.find((item) => item.id === ruleId) ?? null)
        }}
      />

      {selectedRule ? (
        <>
          <PolicyEditor
            rule={selectedRule}
            sources={sources}
            onChange={(rule) => setDraft(rule)}
          />
          <div className="flex justify-end">
            <Button
              size="sm"
              variant="primary"
              onClick={() => {
                if (draft) upsertPolicyRule(draft)
              }}
            >
              Save rule
            </Button>
          </div>
          <PolicyDryRun rule={selectedRule} entries={feed.entries} />
          <div>
            <h3 className="mt-0 mb-2 text-sm font-semibold text-tint-ink">
              Workflow · {source?.workflowName ?? 'youtube-poll'}
            </h3>
            <p className="mt-0 mb-3 text-xs text-tint-muted">
              Read-only docs composition. Disposition conditions live on edge metadata, not in React
              branches.
            </p>
            <div className="h-[22rem] overflow-hidden rounded-xl border border-tint-border">
              <InteractiveGraphView
                document={workflow}
                registry={registry}
                readonly
                showInspector={false}
              />
            </div>
          </div>
        </>
      ) : null}
    </div>
  )
}

export function PolicyDoc() {
  return (
    <DocsPage
      route="components/policy"
      title="Policy"
      intro="Rule table, builder/Lua editor, mocked dry-run, and a read-only workflow graph for the selected source. Lua is highlighted here; execution stays on the host."
      note="Maya’s Subscriptions chat scenario writes into the docs demo store — new sources and rules appear here after confirmation."
    >
      <DocsSection id="preview" title="Workbench">
        <DocsPreview>
          <PolicyWorkbench />
        </DocsPreview>
      </DocsSection>

      <DocsSection id="usage" title="Usage">
        <CodeBlock code={usage} />
      </DocsSection>

      <DocsSection id="api" title="API">
        <PropsTable
          rows={[
            {
              name: 'rules',
              type: 'readonly PolicyRule[]',
              required: true,
              description: 'PolicyTable rows.',
            },
            {
              name: 'selectedId',
              type: 'string | null',
              description: 'Highlighted rule id.',
            },
            {
              name: 'onSelect',
              type: '(ruleId: string) => void',
              description: 'Row selection intent.',
            },
            {
              name: 'onToggle',
              type: '(ruleId: string, enabled: boolean) => void',
              description: 'Enabled checkbox intent; host runs applyPolicyCommand.',
            },
            {
              name: 'sourceLabels',
              type: 'Record<string, string>',
              description: 'sourceId → handle for the Source column.',
            },
            {
              name: 'density',
              type: 'TableDensity',
              description: 'DataTable density passthrough.',
            },
            {
              name: 'rule',
              type: 'PolicyRule',
              required: true,
              description: 'PolicyEditor / dry-run rule document.',
            },
            {
              name: 'onChange',
              type: '(rule: PolicyRule) => void',
              required: true,
              description: 'Editor reports the next rule; host stores it.',
            },
            {
              name: 'sources',
              type: '{ id: string; label: string }[]',
              required: true,
              description: 'Source picker options.',
            },
            {
              name: 'disabled',
              type: 'boolean',
              description: 'Locks PolicyEditor controls.',
            },
            {
              name: 'entries',
              type: 'readonly FeedEntry[]',
              required: true,
              description: 'PolicyDryRun fixture entries.',
            },
            { name: 'className', type: 'string', description: 'Appended to the root element.' },
          ]}
        />
      </DocsSection>
    </DocsPage>
  )
}

// src/docs/policy/PolicyDoc.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Button, InteractiveGraphView, PolicyDryRun, PolicyEditor, PolicyTable,
    type PolicyRule } from '../../svelte'
  import { dispatchPolicyCommand, getDemoFeedStore, subscribeDemoFeedStore, upsertPolicyRule } from '../feed/demoStore'
  import { workflowForName } from './workflowFixtures'
  import DocPage from '../svelte/DocPage.svelte'
  import type { ApiRow } from '../svelte/types'

  const initialSnapshot = getDemoFeedStore()
  let snapshot = $state(initialSnapshot)
  let selectedId = $state<string | null>(initialSnapshot.policy.rules[0]?.id ?? null)
  let draft = $state<PolicyRule | null>(null)
  let sources = $derived(snapshot.feed.sources.map((source) => ({ id: source.id, label: source.handle })))
  let sourceLabels = $derived(Object.fromEntries(snapshot.feed.sources.map((source) => [source.id, source.handle])))
  let selectedRule = $derived(draft?.id === selectedId ? draft : snapshot.policy.rules.find((rule) => rule.id === selectedId) ?? snapshot.policy.rules[0] ?? null)
  let source = $derived(snapshot.feed.sources.find((item) => item.id === selectedRule?.sourceId))
  let workflow = $derived(workflowForName(source?.workflowName ?? 'youtube-poll'))

  onMount(() => subscribeDemoFeedStore(() => snapshot = getDemoFeedStore()))

  function select(ruleId: string) { selectedId = ruleId; draft = null }
  function toggle(ruleId: string, enabled: boolean) {
    dispatchPolicyCommand({ type: 'policy.toggle', ruleId, enabled })
    selectedId = ruleId
    draft = null
  }
  function save() { if (draft) { upsertPolicyRule(draft); draft = null } }

  const api: ApiRow[] = [
    { prop: 'PolicyTable rules / selectedId / onSelect', type: 'PolicyRule[] / string | null / callback', description: 'Host-owned policy rows and controlled selection.' },
    { prop: 'PolicyTable onToggle / sourceLabels / density', type: 'callback / Record / TableDensity', description: 'Enabled intent, source names, and table density.' },
    { prop: 'PolicyEditor rule / onChange / sources', type: 'PolicyRule / callback / options[]', description: 'Controlled builder or Lua source editing.' },
    { prop: 'PolicyDryRun rule / entries', type: 'PolicyRule / FeedEntry[]', description: 'Fixture-only evaluation; Lua is never executed in the browser.' },
    { prop: 'applyPolicyCommand', type: 'pure TypeScript reducer', description: 'Applies host-approved policy commands and advances the revision.' },
  ]
  const usage = `import { PolicyTable, PolicyEditor, PolicyDryRun, applyPolicyCommand } from '@nebula/tint/policy'

let policy = $state(initialPolicy)
let selectedId = $state<string | null>(policy.rules[0]?.id ?? null)
<PolicyTable rules={policy.rules} {selectedId} onSelect={(id) => selectedId = id}
  onToggle={(id, enabled) => policy = applyPolicyCommand(policy, { type: 'policy.toggle', ruleId: id, enabled })} />
<PolicyEditor rule={selectedRule} {sources} onChange={(rule) => draft = rule} />
<PolicyDryRun rule={selectedRule} entries={feed.entries} />`
</script>

<DocPage title="Policy" description="Rule table, builder and Lua editor, fixture dry-run, and a read-only workflow graph. The docs demo store owns all changes; Lua is highlighted as text and runs only in a host service." importPath="@nebula/tint/policy" {usage} {api} accessibility="The table supports row selection, sorting, and labeled enabled toggles. Builder controls use native labels and visible focus. The dry-run result has text badges and a live status region; workflow nodes remain named and inspectable without color alone.">
  <div class="policy-demo">
    <PolicyTable rules={snapshot.policy.rules} selectedId={selectedRule?.id ?? null} {sourceLabels} onSelect={select} onToggle={toggle} />
    {#if selectedRule}
      <PolicyEditor rule={selectedRule} {sources} onChange={(rule) => draft = rule} />
      <div class="save"><Button size="sm" variant="primary" disabled={!draft} onclick={save}>Save rule</Button></div>
      <PolicyDryRun rule={selectedRule} entries={snapshot.feed.entries} />
      <section><h3>Workflow · {source?.workflowName ?? 'youtube-poll'}</h3><p>Read-only workflow composition. Disposition conditions live on graph edges.</p><div class="workflow"><InteractiveGraphView document={workflow} readonly showInspector={false} showFullscreenControl={false} /></div></section>
    {/if}
  </div>
</DocPage>

<style>
  .policy-demo { display: grid; gap: 1.25rem; }
  .save { display: flex; justify-content: flex-end; }
  h3 { margin: 0 0 .5rem; color: var(--tint-ink); font-size: .9rem; }
  p { margin: 0 0 .75rem; color: var(--tint-muted); font-size: .78rem; }
  .workflow { height: 22rem; overflow: hidden; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); }
</style>
