// src/docs/character-card/CharacterCardDoc.tsx
import { useRef, useState } from 'react'
import {
  CHARACTER_CARD_FORM_SCHEMA,
  CharacterCardEditorForm,
  bytesFromObjectUrl,
  embedTavernCard,
  emptyTavernCard,
  extractTavernCard,
  parseTavernCardJson,
  serializeTavernCard,
  type TavernCardV2,
} from '../../components/character-card'
import type { FormFileValue } from '../../components/form'
import '../../components/form/styles.css'
import { CodeBlock } from '../components/CodeBlock'
import { DocsPage, DocsPreview, DocsSection } from '../components/DocsPage'
import { PropsTable } from '../components/PropsTable'

const usage = `import { useState } from 'react'
import {
  CharacterCardEditorForm,
  emptyTavernCard,
  serializeTavernCard,
} from '@nebula/tint/character-card'
import '@nebula/tint/form/styles.css'

const [card, setCard] = useState(() => emptyTavernCard())

<CharacterCardEditorForm
  value={card}
  onValueChange={setCard}
  onSubmit={(envelope) => save(envelope.values)}
/>`

const props = [
  { name: 'value', type: 'TavernCardV2', required: true, description: 'The character card. Unknown extensions survive a round-trip.' },
  { name: 'onValueChange', type: '(card: TavernCardV2) => void', required: true, description: 'Receives the next card after any field edit.' },
  { name: 'avatar', type: 'FormFileValue | null', description: 'Portrait used for PNG export. Not part of the V2 JSON.' },
  { name: 'onAvatarChange', type: '(file: FormFileValue | null) => void', description: 'Fires when the avatar file field changes.' },
  { name: 'busy', type: 'boolean', description: 'Disables the form while a host persist is in flight.' },
  { name: 'error', type: 'ReactNode', description: 'Form-level alert.' },
  { name: 'className', type: 'string', description: 'Appended to the FormLayout root.' },
  { name: 'submitLabel', type: 'string', defaultValue: "'Save character'", description: 'Idle submit copy.' },
  { name: 'submittingLabel', type: 'string', defaultValue: "'Saving…'", description: 'Busy submit copy.' },
  { name: 'hideSubmit', type: 'boolean', description: 'Hide the submit button when a parent toolbar owns save.' },
  { name: 'transport', type: 'FormTransport', description: 'Optional persist seam. Same Promise rules as FormLayout.' },
  { name: 'onSubmit', type: '(envelope: FormSubmitEnvelope) => void | Promise<void>', description: 'Called after validation with the form envelope.' },
]

function download(filename: string, bytes: string | Uint8Array, type: string) {
  const blob =
    typeof bytes === 'string'
      ? new Blob([bytes], { type })
      : new Blob([Uint8Array.from(bytes).buffer as ArrayBuffer], { type })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

export function CharacterCardDoc() {
  const [card, setCard] = useState<TavernCardV2>(() => {
    const next = emptyTavernCard()
    next.data.name = 'Aiko'
    next.data.description = 'A late-night barista with a pen tucked behind one ear.'
    next.data.personality = 'Sarcastic, quietly protective of regulars.'
    next.data.scenario = '{{user}} arrives just before closing.'
    next.data.first_mes = '"We\'re closed in ten. Sit down before you fall down."'
    next.data.tags = ['original', 'slice-of-life']
    next.data.creator = 'tint'
    next.data.character_version = '1.0'
    return next
  })
  const [avatar, setAvatar] = useState<FormFileValue | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  const jsonInput = useRef<HTMLInputElement>(null)
  const pngInput = useRef<HTMLInputElement>(null)

  async function onExportPng() {
    const png = avatar?.objectUrl
      ? embedTavernCard(card, await bytesFromObjectUrl(avatar.objectUrl))
      : embedTavernCard(card)
    download(`${card.data.name || 'character'}.png`, png, 'image/png')
  }

  return (
    <DocsPage
      route="components/character-card"
      title="Character Card"
      intro="A SillyTavern-shaped Character Card V2 editor, composed on FormLayout. Identity, greetings, personality, prompt overrides, creator metadata, and embedded lore — plus JSON and PNG round-trips."
      note="Group chats, HotSwap, live tokenizer counts, and World Info file linking stay host-app features. This kit edits the card."
    >
      <DocsSection id="editor" title="Editor">
        <DocsPreview>
          <div className="mb-4 flex flex-wrap gap-2">
            <button
              type="button"
              className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
              onClick={() => jsonInput.current?.click()}
            >
              Import JSON
            </button>
            <button
              type="button"
              className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
              onClick={() =>
                download(`${card.data.name || 'character'}.json`, serializeTavernCard(card), 'application/json')
              }
            >
              Export JSON
            </button>
            <button
              type="button"
              className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
              onClick={() => pngInput.current?.click()}
            >
              Import PNG
            </button>
            <button
              type="button"
              className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
              onClick={() => void onExportPng()}
            >
              Export PNG
            </button>
            <button
              type="button"
              className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
              onClick={() => {
                setCard(emptyTavernCard())
                setAvatar((current) => {
                  if (current?.objectUrl) URL.revokeObjectURL(current.objectUrl)
                  return null
                })
                setMessage(null)
              }}
            >
              Reset
            </button>
            <input
              ref={jsonInput}
              className="sr-only"
              type="file"
              accept="application/json,.json"
              aria-label="Import character JSON"
              onChange={(event) => {
                const file = event.target.files?.[0]
                event.target.value = ''
                if (!file) return
                void file.text().then((text) => {
                  try {
                    setCard(parseTavernCardJson(text))
                    setMessage(`Imported ${file.name}`)
                  } catch (cause) {
                    setMessage(cause instanceof Error ? cause.message : 'Could not parse JSON.')
                  }
                })
              }}
            />
            <input
              ref={pngInput}
              className="sr-only"
              type="file"
              accept="image/png,.png"
              aria-label="Import character PNG"
              onChange={(event) => {
                const file = event.target.files?.[0]
                event.target.value = ''
                if (!file) return
                void file.arrayBuffer().then((buffer) => {
                  try {
                    setCard(extractTavernCard(new Uint8Array(buffer)))
                    setAvatar((current) => {
                      if (current?.objectUrl) URL.revokeObjectURL(current.objectUrl)
                      return {
                        name: file.name,
                        mimeType: file.type || 'image/png',
                        objectUrl: URL.createObjectURL(file),
                      }
                    })
                    setMessage(`Imported ${file.name}`)
                  } catch (cause) {
                    setMessage(cause instanceof Error ? cause.message : 'Could not read PNG.')
                  }
                })
              }}
            />
          </div>
          {message ? <p className="mt-0 mb-4 text-sm text-tint-muted">{message}</p> : null}
          <CharacterCardEditorForm
            value={card}
            onValueChange={setCard}
            avatar={avatar}
            onAvatarChange={setAvatar}
            onSubmit={() => setMessage('Saved in memory. Export JSON or PNG to take it with you.')}
          />
        </DocsPreview>
      </DocsSection>

      <DocsSection
        id="schema"
        title="Schema"
        description="The FormSchema the editor renders. Viewing it here is the same document FormLayout consumes."
      >
        <CodeBlock code={JSON.stringify(CHARACTER_CARD_FORM_SCHEMA, null, 2)} language="json" title="json" />
      </DocsSection>

      <DocsSection id="usage" title="Usage">
        <CodeBlock code={usage} />
      </DocsSection>

      <DocsSection id="api" title="API">
        <PropsTable rows={props} />
      </DocsSection>
    </DocsPage>
  )
}

// src/docs/character-card/CharacterCardDoc.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'
  import {
    bytesFromObjectUrl, embedTavernCard, emptyTavernCard, extractTavernCard,
    parseTavernCardJson, serializeTavernCard, type TavernCardV2,
  } from '../../components/character-card'
  import type { FormFileValue } from '../../components/form/contracts/values'
  import CharacterCardEditorForm from '../../svelte/components/character-card/CharacterCardEditorForm.svelte'
  import DocPage from '../svelte/DocPage.svelte'
  import type { ApiRow } from '../svelte/types'

  function exampleCard(): TavernCardV2 {
    const next = emptyTavernCard()
    next.data.name = 'Aiko'
    next.data.description = 'A late-night barista with a pen tucked behind one ear.'
    next.data.personality = 'Sarcastic, quietly protective of regulars.'
    next.data.scenario = '{{user}} arrives just before closing.'
    next.data.first_mes = 'We close in ten. Sit down before you fall down.'
    next.data.tags = ['original', 'slice-of-life']
    next.data.creator = 'tint'
    next.data.character_version = '1.0'
    return next
  }

  let card = $state<TavernCardV2>(exampleCard())
  let avatar = $state<FormFileValue | null>(null)
  let message = $state('')
  let jsonInput = $state<HTMLInputElement>()
  let pngInput = $state<HTMLInputElement>()

  onDestroy(() => { if (avatar?.objectUrl) URL.revokeObjectURL(avatar.objectUrl) })

  function download(filename: string, bytes: string | Uint8Array, type: string) {
    const data = typeof bytes === 'string' ? bytes : Uint8Array.from(bytes).buffer as ArrayBuffer
    const url = URL.createObjectURL(new Blob([data], { type }))
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    link.click()
    setTimeout(() => URL.revokeObjectURL(url), 0)
  }

  async function importJson(event: Event) {
    const input = event.currentTarget as HTMLInputElement
    const file = input.files?.[0]
    if (!file) return
    try {
      card = parseTavernCardJson(await file.text())
      message = `Imported ${file.name}`
    } catch (cause) {
      message = cause instanceof Error ? cause.message : 'Could not read JSON.'
    }
    input.value = ''
  }

  async function importPng(event: Event) {
    const input = event.currentTarget as HTMLInputElement
    const file = input.files?.[0]
    if (!file) return
    try {
      const bytes = new Uint8Array(await file.arrayBuffer())
      card = extractTavernCard(bytes)
      if (avatar?.objectUrl) URL.revokeObjectURL(avatar.objectUrl)
      avatar = { name: file.name, mimeType: file.type || 'image/png', objectUrl: URL.createObjectURL(file) }
      message = `Imported ${file.name}`
    } catch (cause) {
      message = cause instanceof Error ? cause.message : 'Could not read PNG.'
    }
    input.value = ''
  }

  async function exportPng() {
    try {
      const bytes = avatar?.objectUrl
        ? embedTavernCard(card, await bytesFromObjectUrl(avatar.objectUrl))
        : embedTavernCard(card)
      download(`${card.data.name || 'character'}.png`, bytes, 'image/png')
    } catch (cause) {
      message = cause instanceof Error ? cause.message : 'Could not export PNG.'
    }
  }

  const api: ApiRow[] = [
    { prop: 'value / onValueChange', type: 'TavernCardV2 / (card) => void', description: 'Controlled card value; unknown extension keys survive edits and round trips.' },
    { prop: 'avatar / onAvatarChange', type: 'FormFileValue | null / (file) => void', description: 'Optional portrait for PNG export, separate from V2 JSON.' },
    { prop: 'busy / error', type: 'boolean / string | Snippet', description: 'Host-controlled submit state and form-level alert.' },
    { prop: 'submitLabel / submittingLabel / hideSubmit', type: 'string / string / boolean', description: 'Save action copy or toolbar-owned save.' },
    { prop: 'transport / onSubmit', type: 'FormTransport / (envelope) => void', description: 'Optional persistence seam and validated submission envelope.' },
    { prop: 'parseTavernCardJson / serializeTavernCard', type: 'string ↔ TavernCardV2', description: 'Framework-neutral JSON import and export.' },
    { prop: 'extractTavernCard / embedTavernCard', type: 'PNG bytes ↔ TavernCardV2', description: 'Framework-neutral PNG metadata round trip.' },
  ]
  const usage = `import { CharacterCardEditorForm } from '@nebula/tint/character-card'
import { emptyTavernCard, serializeTavernCard } from '@nebula/tint/character-card'

let card = $state(emptyTavernCard())

<CharacterCardEditorForm value={card}
  onValueChange={(next) => card = next}
  onSubmit={(envelope) => save(envelope.values)} />

const json = serializeTavernCard(card)`
</script>

<DocPage title="Character Card" description="Edit a Character Card V2 with the shared form schema, then import or export JSON and PNG. Unknown extension data survives the round trip." importPath="@nebula/tint/character-card" {usage} {api} accessibility="The editor uses labelled fields and announces validation and import errors. All actions are keyboard accessible. Import controls have accessible file input labels, and the host owns the card and avatar values.">
  <div class="toolbar">
    <button type="button" onclick={() => jsonInput?.click()}>Import JSON</button>
    <button type="button" onclick={() => download(`${card.data.name || 'character'}.json`, serializeTavernCard(card), 'application/json')}>Export JSON</button>
    <button type="button" onclick={() => pngInput?.click()}>Import PNG</button>
    <button type="button" onclick={() => void exportPng()}>Export PNG</button>
    <input bind:this={jsonInput} class="visually-hidden" type="file" accept=".json,application/json" aria-label="Choose character JSON" onchange={importJson} />
    <input bind:this={pngInput} class="visually-hidden" type="file" accept=".png,image/png" aria-label="Choose character PNG" onchange={importPng} />
  </div>
  {#if message}<p class="message" role="status">{message}</p>{/if}
  <CharacterCardEditorForm value={card} onValueChange={(next) => card = next} {avatar} onAvatarChange={(next) => avatar = next} onSubmit={() => { message = 'Saved in memory. Export JSON or PNG to take it with you.' }} />
</DocPage>

<style>
  .toolbar { display: flex; flex-wrap: wrap; gap: .5rem; margin-bottom: 1rem; }
  button { min-height: 2.5rem; border: 1px solid var(--tint-border-strong); border-radius: var(--tint-radius-sm); padding: .5rem .8rem; background: var(--tint-panel); color: var(--tint-ink); cursor: pointer; font: inherit; font-size: .84rem; }
  button:hover { background: var(--tint-surface); }
  button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .visually-hidden { position: absolute; width: 1px; height: 1px; overflow: hidden; clip-path: inset(50%); white-space: nowrap; }
  .message { color: var(--tint-muted); font-size: .84rem; }
</style>
