// src/components/dice/DiceRoller.tsx
import { useEffect, useState } from 'react'
import { Dice1, Dice2, Dice3, Dice4, Dice5, Dice6, Shuffle } from 'lucide-react'
import { motion, useReducedMotion } from 'motion/react'
import { cn } from '../../lib/utils'
import { Icon, type IconGlyph } from '../icon'
import { D10, D20 } from './glyphs'
import type { DiceKind, DiceRollerProps } from './types'

const D6_FACES = [Dice1, Dice2, Dice3, Dice4, Dice5, Dice6]

const FACE_COUNT: Record<DiceKind, number> = { d6: 6, d10: 10, d20: 20 }

const CUSTOM_GLYPH: Record<'d10' | 'd20', IconGlyph> = { d10: D10, d20: D20 }

function randomFace(kind: DiceKind) {
  return 1 + Math.floor(Math.random() * FACE_COUNT[kind])
}

/**
 * A worked example of extending `Icon` past lucide's catalog: lucide ships
 * `Dice1`–`Dice6` but no d10/d20, so those two faces render the hand-authored
 * `D10`/`D20` glyphs from `./glyphs` through the same `Icon` seam as every
 * other icon in the library.
 *
 * Controlled like the rest of tint: `value` is the settled face and `onRoll`
 * only reports intent — the app owns the randomness (and can make it
 * server-authoritative, seeded, loaded, whatever) and answers by setting
 * `rolling` and, once resolved, the new `value`.
 */
export function DiceRoller({
  kind = 'd6',
  value,
  rolling = false,
  onRoll,
  label = 'Roll',
  className,
  ...props
}: DiceRollerProps) {
  const [displayFace, setDisplayFace] = useState(value)
  const reduceMotion = useReducedMotion()

  useEffect(() => {
    if (!rolling) {
      setDisplayFace(value)
      return
    }
    // Reduced motion still needs the result to change — it just skips the
    // flicker-through-random-faces spectacle on the way there.
    if (reduceMotion) return
    const id = window.setInterval(() => setDisplayFace(randomFace(kind)), 80)
    return () => window.clearInterval(id)
  }, [rolling, kind, value, reduceMotion])

  const custom = kind !== 'd6' ? CUSTOM_GLYPH[kind] : undefined

  return (
    <div
      data-dice-roller=""
      data-kind={kind}
      className={cn('inline-flex flex-col items-center gap-3', className)}
      {...props}
    >
      <motion.div
        role="status"
        aria-label={rolling ? 'Rolling' : `Rolled ${value}`}
        animate={
          rolling && !reduceMotion
            ? { rotate: [0, 16, -14, 10, -8, 0], scale: [1, 1.08, 0.96, 1.04, 1] }
            : { rotate: 0, scale: 1 }
        }
        transition={
          rolling && !reduceMotion
            ? { duration: 0.5, repeat: Infinity, ease: 'easeInOut' }
            : { type: 'spring', stiffness: 300, damping: 16 }
        }
        className="relative grid size-16 place-items-center rounded-2xl border border-tint-border bg-tint-panel text-tint-accent"
      >
        {custom ? (
          <>
            <Icon icon={custom} size="xl" className="text-tint-border" />
            <span className="absolute text-sm font-semibold tabular-nums text-tint-ink">
              {rolling ? displayFace : value}
            </span>
          </>
        ) : (
          <Icon icon={D6_FACES[(rolling ? displayFace : value) - 1] ?? Dice1} size="xl" />
        )}
      </motion.div>

      <button
        type="button"
        onClick={onRoll}
        disabled={rolling}
        className="inline-flex items-center gap-1.5 rounded-lg border border-tint-border bg-tint-panel px-3 py-1.5 text-xs font-medium text-tint-ink transition hover:bg-tint-surface disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
      >
        <Icon
          icon={Shuffle}
          size="sm"
          className={rolling ? 'animate-spin motion-reduce:animate-none' : undefined}
        />
        {label}
      </button>
    </div>
  )
}

// src/svelte/components/dice/DiceRoller.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'
  import Dice1 from '@lucide/svelte/icons/dice-1'
  import Dice2 from '@lucide/svelte/icons/dice-2'
  import Dice3 from '@lucide/svelte/icons/dice-3'
  import Dice4 from '@lucide/svelte/icons/dice-4'
  import Dice5 from '@lucide/svelte/icons/dice-5'
  import Dice6 from '@lucide/svelte/icons/dice-6'
  import Shuffle from '@lucide/svelte/icons/shuffle'
  import { animationFace, type DiceKind } from '../../../core/dice/model'
  import Icon from '../icon/Icon.svelte'
  import D10 from './D10.svelte'
  import D20 from './D20.svelte'

  type Props = Omit<HTMLAttributes<HTMLDivElement>, 'children'> & {
    kind?: DiceKind
    /** Settled result supplied by the host. */
    value: number
    rolling?: boolean
    /** Reports intent; the host produces the next result. */
    onRoll?: () => void
    label?: string
  }

  let { kind = 'd6', value, rolling = false, onRoll, label = 'Roll', class: className, ...rest }: Props = $props()
  const d6Faces = [Dice1, Dice2, Dice3, Dice4, Dice5, Dice6]
  let displayFace = $state<number | undefined>()
  let reduceMotion = $state(false)
  let faceIcon = $derived(d6Faces[(rolling ? displayFace ?? value : value) - 1] ?? Dice1)

  onMount(() => {
    if (typeof window.matchMedia !== 'function') return
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    reduceMotion = query.matches
    const changed = () => { reduceMotion = query.matches }
    query.addEventListener('change', changed)
    return () => query.removeEventListener('change', changed)
  })

  $effect(() => {
    if (!rolling) {
      displayFace = value
      return
    }
    if (reduceMotion) return
    const timer = window.setInterval(() => { displayFace = animationFace(kind) }, 80)
    return () => window.clearInterval(timer)
  })
</script>

<div {...rest} data-dice-roller="" data-kind={kind} class={['tint-dice-roller', className]}>
  <div class="die" data-rolling={rolling || undefined} role="status" aria-label={rolling ? 'Rolling' : `Rolled ${value}`}>
    {#if kind === 'd6'}
      <Icon icon={faceIcon} size="xl" />
    {:else}
      {#if kind === 'd10'}<Icon icon={D10} size="xl" />{:else}<Icon icon={D20} size="xl" />{/if}
      <span class="face" aria-hidden="true">{rolling && !reduceMotion ? displayFace ?? value : value}</span>
    {/if}
  </div>
  <button type="button" disabled={rolling} onclick={() => onRoll?.()}>
    <Icon icon={Shuffle} size="sm" />
    {label}
  </button>
</div>

<style>
  .tint-dice-roller { display: inline-flex; flex-direction: column; align-items: center; gap: var(--tint-space-3); }
  .die { position: relative; display: grid; width: 4rem; height: 4rem; place-items: center; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-panel); color: var(--tint-accent); }
  .die[data-rolling] { animation: tumble .5s ease-in-out infinite; }
  .face { position: absolute; color: var(--tint-ink); font-size: var(--tint-font-size-sm); font-weight: 700; font-variant-numeric: tabular-nums; }
  button { display: inline-flex; align-items: center; gap: var(--tint-space-1); border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); padding: var(--tint-space-2) var(--tint-space-3); background: var(--tint-panel); color: var(--tint-ink); font: inherit; font-size: var(--tint-font-size-xs); font-weight: 600; cursor: pointer; }
  button:hover:not(:disabled) { background: var(--tint-surface); }
  button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  button:disabled { cursor: not-allowed; opacity: .5; }
  @keyframes tumble { 25% { transform: rotate(16deg) scale(1.08); } 50% { transform: rotate(-14deg) scale(.96); } 75% { transform: rotate(10deg) scale(1.04); } }
  @media (prefers-reduced-motion: reduce) { .die[data-rolling] { animation: none; } }
</style>
