// src/docs/auth/AuthDoc.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { createAuthClient } from '../../auth/client'
  import {
    CredentialRecoveryForm, IdentifierSignInForm, OAuthButtons,
    type IdentifierSignInFormLabels, type OAuthOption,
  } from '../../svelte/components/auth'
  import { createDemoTransport, DEMO_CREDENTIALS, DEMO_TOTP_CODE } from './demoTransport'
  import DocPage from '../svelte/DocPage.svelte'
  import type { ApiRow } from '../svelte/types'

  const auth = createAuthClient({ transport: createDemoTransport(), broadcastChannel: false })
  const labels: IdentifierSignInFormLabels = {
    identifier: 'Email or username', password: 'Password', submit: 'Sign in',
    submitting: 'Signing in…', showPassword: 'Show password', hidePassword: 'Hide password',
  }
  let snapshot = $state(auth.getSnapshot())
  let identifier = $state('operator@example.test')
  let password = $state('tint-demo')
  let code = $state('')
  let recoveryIdentifier = $state('operator@example.test')
  let recoveryMessage = $state('')
  let providers = $derived<OAuthOption[]>((snapshot.config?.providers ?? []).map((provider) => ({
    id: provider.id, label: provider.label, href: auth.oauth.url(provider.id),
  })))

  onMount(() => {
    const unsubscribe = auth.subscribe(() => { snapshot = auth.getSnapshot() })
    void auth.initialize().catch(() => { /* The snapshot displays the error. */ })
    return () => { unsubscribe(); auth.destroy() }
  })

  async function attempt(operation: () => Promise<unknown>) {
    try { await operation() } catch { /* The snapshot displays the error. */ }
  }

  const api: ApiRow[] = [
    { prop: 'IdentifierSignInForm', type: 'identifier / password / labels / onChange / onSubmit', description: 'Controlled sign-in fields with busy and error states.' },
    { prop: 'CredentialRecoveryForm', type: 'identifier / label / onIdentifierChange / onSubmit', description: 'Controlled recovery request form.' },
    { prop: 'OAuthButtons', type: 'providers / ariaLabel', description: 'Named navigation landmark with provider links.' },
    { prop: 'AuthClient', type: 'AuthTransport → AuthSnapshot', description: 'Framework-neutral auth state machine and transport contract.' },
    { prop: 'useAuth / useSession', type: 'Svelte reactive snapshot helpers', description: 'Read the shared TintClient auth capability from Svelte context.' },
  ]
  const usage = `import { IdentifierSignInForm } from '@nebula/tint/svelte'
import { useAuth, useSession } from '@nebula/tint/client/svelte'

const auth = useAuth()
const session = useSession()
let identifier = $state('')
let password = $state('')

{#if session.isSignedIn}
  <p>Signed in as {session.user?.email}</p>
{:else}
  <IdentifierSignInForm {identifier} {password} {labels}
    onIdentifierChange={(next) => identifier = next}
    onPasswordChange={(next) => password = next}
    onSubmit={() => auth.client.signIn.password({ identifier, password })}
    busy={auth.snapshot.busy} error={auth.snapshot.error?.message} />
{/if}`
</script>

<DocPage title="Auth" description="Transport-neutral authentication with controlled Svelte forms and reactive snapshots. The live transport stays in this page's memory." importPath="@nebula/tint/svelte" {usage} {api} accessibility="Each field has an associated label. Validation errors use a live alert, busy states disable submission, OAuth choices are links inside a named navigation landmark, and the six-digit challenge uses a labelled input.">
  <div class="auth-demo">
    <div class="auth-panel">
      {#if snapshot.status === 'loading'}
        <p role="status">Loading the demo session…</p>
      {:else if snapshot.status === 'signed_in'}
        <div class="signed-in">
          <strong>Signed in as {snapshot.session?.user.name}</strong>
          <span>{snapshot.session?.user.email}</span>
          <button type="button" disabled={snapshot.busy} onclick={() => void attempt(() => auth.signOut())}>Sign out</button>
        </div>
      {:else if snapshot.task === 'mfa'}
        <form class="challenge" onsubmit={(event) => { event.preventDefault(); void attempt(() => auth.mfa.verifyTotp({ code })) }}>
          <label for="auth-demo-code">Six-digit code ({DEMO_TOTP_CODE})</label>
          <input id="auth-demo-code" inputmode="numeric" autocomplete="one-time-code" value={code} oninput={(event) => code = event.currentTarget.value} />
          {#if snapshot.error}<p role="alert">{snapshot.error.message}</p>{/if}
          <button type="submit" disabled={snapshot.busy}>Verify code</button>
        </form>
      {:else}
        <IdentifierSignInForm {identifier} {password} {labels}
          onIdentifierChange={(next) => identifier = next}
          onPasswordChange={(next) => password = next}
          onSubmit={() => attempt(() => auth.signIn.password({ identifier, password }))}
          busy={snapshot.busy} error={snapshot.error?.message} />
        <OAuthButtons {providers} ariaLabel="Other sign-in methods" />
      {/if}
    </div>
    <div class="auth-aside">
      <h3>Try the demo</h3>
      <ul>{#each DEMO_CREDENTIALS as credential}<li><code>{credential.email}</code> / <code>{credential.password}</code><br />{credential.outcome}</li>{/each}</ul>
      <h3>Recovery form</h3>
      <CredentialRecoveryForm identifier={recoveryIdentifier} label="Account email" onIdentifierChange={(next) => recoveryIdentifier = next} onSubmit={() => { recoveryMessage = 'Recovery is disabled in this demo transport.' }} />
      {#if recoveryMessage}<p role="status">{recoveryMessage}</p>{/if}
      <p>The demo transport intentionally has no recovery operation. Production hosts provide the operations they support.</p>
      <p>Full login and registration layouts with Discord, GitHub and Google live on <a href="#/components/auth-forms">Sign-in &amp; Registration</a>.</p>
    </div>
  </div>
</DocPage>

<style>
  .auth-demo { display: grid; grid-template-columns: minmax(0, 1fr) minmax(13rem, .75fr); gap: 1.5rem; }
  .auth-panel, .auth-aside { min-width: 0; padding: 1.25rem; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-surface); }
  .auth-panel { display: grid; align-content: start; gap: 1rem; }
  .auth-aside h3 { margin: .25rem 0 .65rem; color: var(--tint-ink); font-size: .9rem; }
  .auth-aside ul { margin: 0 0 1.5rem; padding-left: 1.1rem; color: var(--tint-muted); font-size: .8rem; line-height: 1.7; }
  .auth-aside li + li { margin-top: .55rem; }
  .auth-aside p { font-size: .8rem; }
  .signed-in, .challenge { display: grid; gap: .75rem; }
  .signed-in span { color: var(--tint-muted); }
  button, input { min-height: 2.5rem; border: 1px solid var(--tint-border-strong); border-radius: var(--tint-radius-sm); padding: .45rem .7rem; background: var(--tint-panel); color: var(--tint-ink); font: inherit; }
  button { cursor: pointer; }
  button:disabled { opacity: .5; cursor: not-allowed; }
  button:focus-visible, input:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .challenge label { color: var(--tint-ink); font-size: .85rem; }
  @container (max-width: 760px) { .auth-demo { grid-template-columns: 1fr; } }
</style>

// src/docs/auth/AuthDoc.tsx
import { useMemo, useState } from 'react'
import { createAuthClient } from '../../auth/client'
import { createTintClient, TintClientProvider, useAuth, useSession } from '../../client'
import {
  IdentifierSignInForm,
  OAuthButtons,
  type IdentifierSignInFormLabels,
  type OAuthOption,
} from '../../components/auth'
import '../../components/auth/styles.css'
import { CodeBlock } from '../components/CodeBlock'
import { DocsCallout, DocsDemo, DocsFooter, DocsPage, DocsSection } from '../components/DocsPage'
import { PropsTable } from '../components/PropsTable'
import { createDemoTransport, DEMO_CREDENTIALS, DEMO_TOTP_CODE } from './demoTransport'

const previewDemoCode = `const client = createAuthClient({ transport })

function SignInScreen() {
  const { client, snapshot } = useAuth()
  const { isSignedIn, user, task } = useSession()

  if (isSignedIn) return <p>Signed in as {user?.email}</p>
  if (task === 'mfa') return <TotpForm onSubmit={client.mfa.verifyTotp} />

  return (
    <IdentifierSignInForm
      identifier={email}
      password={password}
      onIdentifierChange={setEmail}
      onPasswordChange={setPassword}
      onSubmit={() => client.signIn.password({ identifier: email, password })}
      busy={snapshot.busy}
      error={snapshot.error?.message}
      labels={labels}
    />
  )
}`

const LABELS: IdentifierSignInFormLabels = {
  identifier: 'Email or username',
  password: 'Password',
  submit: 'Sign in',
  submitting: 'Signing in…',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
}

const usageCode = `import { createAuthClient, IdentifierSignInForm } from '@nebula/tint/auth'
import { createTintClient, TintClientProvider, useAuth, useSession } from '@nebula/tint/client'
import '@nebula/tint/auth/styles.css'

// The client is transport-agnostic: implement AuthTransport against your backend.
const auth = createAuthClient({ transport: httpTransport })
const client = createTintClient({ request, auth })

export function App() {
  return (
    <TintClientProvider client={client}>
      <SignInScreen />
    </TintClientProvider>
  )
}

function SignInScreen() {
  const { client, snapshot } = useAuth()
  const { isSignedIn, user } = useSession()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  if (isSignedIn) return <p>Signed in as {user?.email}</p>

  return (
    <IdentifierSignInForm
      identifier={email}
      password={password}
      onIdentifierChange={setEmail}
      onPasswordChange={setPassword}
      onSubmit={() => client.signIn.password({ identifier: email, password })}
      busy={snapshot.busy}
      error={snapshot.error?.message}
      labels={labels}
    />
  )
}`

const transportCode = `import { authErrorFromResponse, type AuthTransport } from '@nebula/tint/auth'

export const httpTransport: AuthTransport = {
  // Required — everything else is optional, and a missing method makes the
  // matching flow throw UnsupportedAuthOperationError. That is how a deployment
  // declares which flows it offers.
  getConfig: () => get('/auth/config'),
  getSession: () => get('/auth/session'),
  signOut: () => post('/auth/sign-out'),
  oauthStartUrl: (provider, returnTo) =>
    \`/auth/oauth/\${provider}?return_to=\${encodeURIComponent(returnTo ?? '/')}\`,

  signInPassword: (input) => post('/auth/sign-in', input),
  verifyTotp: (input) => post('/auth/mfa/totp', input),
}

async function post(path: string, body?: unknown) {
  const response = await fetch(path, {
    method: 'POST',
    credentials: 'include',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body ?? {}),
  })
  if (!response.ok) throw await authErrorFromResponse(response)
  return response.json()
}`

const signInFormSignature = `export type IdentifierSignInFormProps = {
  identifier: string
  password: string
  busy?: boolean
  error?: ReactNode
  labels: IdentifierSignInFormLabels
  identifierPlaceholder?: string
  passwordPlaceholder?: string
  onIdentifierChange(value: string): void
  onPasswordChange(value: string): void
  onSubmit(): void | Promise<void>
  className?: string
}`

const oauthSignature = `export type OAuthOption = { id: string; label: string; href: string; icon?: ReactNode }

export type OAuthButtonsProps = {
  providers: readonly OAuthOption[]
  ariaLabel: string
  className?: string
}`

const sessionSignature = `// The object useSession() derives from the snapshot:
{
  session: AuthSession | null
  user: AuthUser | null
  status: AuthStatus
  task: AuthTask | null
  isLoaded: boolean
  isSignedIn: boolean
}`

const transportSignature = `export type AuthTransport = {
  getConfig(): Promise<AuthConfig>
  getSession(): Promise<AuthSession | null>
  signInPassword?(input: PasswordSignInInput): Promise<AuthFlowResult>
  signUpPassword?(input: PasswordSignUpInput): Promise<AuthFlowResult>
  requestCredentialRecovery?(input: CredentialRecoveryRequestInput): Promise<AuthFlowResult>
  verifyTotp?(input: TotpVerifyInput): Promise<AuthFlowResult>
  selectOrganization?(input: OrganizationSelectInput): Promise<AuthFlowResult>
  signOut(): Promise<void>
  oauthStartUrl(provider: OAuthProviderId, returnTo?: string): string
}`

const signInFormProps = [
  { name: 'identifier', type: 'string', required: true, description: 'Controlled username or email value.' },
  { name: 'password', type: 'string', required: true, description: 'Controlled password value.' },
  { name: 'labels', type: 'IdentifierSignInFormLabels', required: true, description: 'All six strings; the component ships no default copy.' },
  { name: 'onIdentifierChange', type: '(value: string) => void', required: true, description: 'Receives each identifier keystroke.' },
  { name: 'onPasswordChange', type: '(value: string) => void', required: true, description: 'Receives each password keystroke.' },
  { name: 'onSubmit', type: '() => void | Promise<void>', required: true, description: 'Fires on submit unless busy; the form calls preventDefault for you.' },
  { name: 'busy', type: 'boolean', defaultValue: 'false', description: 'Disables submit and swaps in the submitting label.' },
  { name: 'error', type: 'ReactNode', description: 'Rendered in a role="alert" region above the fields.' },
  { name: 'identifierPlaceholder', type: 'string', description: 'Placeholder for the identifier input.' },
  { name: 'passwordPlaceholder', type: 'string', description: 'Placeholder for the password input.' },
  { name: 'className', type: 'string', description: 'Appended to the tint-auth-form class.' },
]

const oauthProps = [
  { name: 'providers', type: 'readonly OAuthOption[]', required: true, description: 'Rendered as real anchors; an empty list renders nothing.' },
  { name: 'ariaLabel', type: 'string', required: true, description: 'Accessible name for the surrounding nav landmark.' },
  { name: 'className', type: 'string', description: 'Appended to the tint-auth-oauth class.' },
]

const sessionProps = [
  { name: 'session', type: 'AuthSession | null', description: 'The full session, including memberships and capabilities.' },
  { name: 'user', type: 'AuthUser | null', description: 'Shorthand for session.user.' },
  { name: 'status', type: "'loading' | 'signed_out' | 'pending' | 'signed_in' | 'error'", description: 'The state machine position.' },
  { name: 'task', type: 'AuthTask | null', description: 'A required next step, e.g. mfa or verify_email.' },
  { name: 'isLoaded', type: 'boolean', description: 'False only while the initial session fetch is in flight.' },
  { name: 'isSignedIn', type: 'boolean', description: 'True when status is signed_in.' },
]

const transportProps = [
  { name: 'getConfig', type: '() => Promise<AuthConfig>', required: true, description: 'Enabled methods and OAuth providers.' },
  { name: 'getSession', type: '() => Promise<AuthSession | null>', required: true, description: 'Called on initialize and refresh.' },
  { name: 'signOut', type: '() => Promise<void>', required: true, description: 'Clears the server session.' },
  { name: 'oauthStartUrl', type: '(provider, returnTo?) => string', required: true, description: 'returnTo is sanitised by safeReturnTo first.' },
  { name: 'signInPassword', type: '(input) => Promise<AuthFlowResult>', description: 'Omit to disable password sign-in.' },
  { name: 'signUpPassword', type: '(input) => Promise<AuthFlowResult>', description: 'Omit to disable registration.' },
  { name: 'verifyTotp', type: '(input) => Promise<AuthFlowResult>', description: 'Resolves a pending mfa task.' },
  { name: 'requestCredentialRecovery', type: '(input) => Promise<AuthFlowResult>', description: 'Omit to disable recovery.' },
  { name: 'selectOrganization', type: '(input) => Promise<AuthFlowResult>', description: 'Resolves a choose_organization task.' },
]

function SnapshotRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-4 border-b border-tint-border py-1.5 last:border-b-0">
      <span className="text-tint-muted">{label}</span>
      <span className="font-mono text-[13px] text-tint-ink">{value}</span>
    </div>
  )
}

function AuthDemo() {
  const { client, snapshot } = useAuth()
  const { user, status, task, isSignedIn } = useSession()
  const [email, setEmail] = useState('operator@example.test')
  const [password, setPassword] = useState('tint-demo')
  const [code, setCode] = useState('')
  const [unsupported, setUnsupported] = useState<string>()

  const providers: OAuthOption[] = (snapshot.config?.providers ?? []).map((provider) => ({
    id: provider.id,
    label: provider.label,
    href: client.oauth.url(provider.id),
  }))

  async function attempt(run: () => Promise<unknown>) {
    setUnsupported(undefined)
    try {
      await run()
    } catch {
      // The snapshot already carries the error; nothing more to do here.
    }
  }

  return (
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,20rem)]">
      <div className="rounded-xl border border-tint-border bg-tint-panel p-5">
        {isSignedIn ? (
          <div className="flex flex-col gap-4">
            <div>
              <p className="m-0 text-sm text-tint-muted">Signed in as</p>
              <p className="m-0 text-lg font-semibold text-tint-ink">{user?.name}</p>
              <p className="m-0 text-sm text-tint-muted">{user?.email}</p>
            </div>
            <button
              type="button"
              onClick={() => void attempt(() => client.signOut())}
              className="self-start rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
            >
              Sign out
            </button>
          </div>
        ) : task === 'mfa' ? (
          <form
            className="flex flex-col gap-3"
            onSubmit={(event) => {
              event.preventDefault()
              void attempt(() => client.mfa.verifyTotp({ code }))
            }}
          >
            <label className="text-sm text-tint-muted" htmlFor="demo-totp">
              Enter the six-digit code ({DEMO_TOTP_CODE})
            </label>
            <input
              id="demo-totp"
              value={code}
              inputMode="numeric"
              onChange={(event) => setCode(event.target.value)}
              className="rounded-md border border-tint-border bg-tint-surface px-3 py-2 font-mono text-tint-ink"
            />
            {snapshot.error ? (
              <p role="alert" className="m-0 text-sm text-tint-danger">
                {snapshot.error.message}
              </p>
            ) : null}
            <button
              type="submit"
              disabled={snapshot.busy}
              className="self-start rounded-md bg-tint-accent px-3 py-1.5 text-sm text-tint-on-accent disabled:opacity-50"
            >
              {snapshot.busy ? 'Verifying…' : 'Verify'}
            </button>
          </form>
        ) : (
          <div className="flex flex-col gap-4">
            <IdentifierSignInForm
              identifier={email}
              password={password}
              onIdentifierChange={setEmail}
              onPasswordChange={setPassword}
              onSubmit={() => attempt(() => client.signIn.password({ identifier: email, password }))}
              busy={snapshot.busy}
              error={snapshot.error?.message}
              labels={LABELS}
            />
            <OAuthButtons providers={providers} ariaLabel="Continue with a provider" />
          </div>
        )}
      </div>

      <div className="flex flex-col gap-4">
        <div className="rounded-xl border border-tint-border bg-tint-panel p-5 text-sm">
          <p className="mt-0 mb-3 font-semibold text-tint-ink">AuthSnapshot</p>
          <SnapshotRow label="status" value={status} />
          <SnapshotRow label="busy" value={String(snapshot.busy)} />
          <SnapshotRow label="task" value={task ?? 'null'} />
          <SnapshotRow label="error.code" value={snapshot.error?.code ?? 'null'} />
          <SnapshotRow label="providers" value={String(snapshot.config?.providers.length ?? 0)} />
        </div>

        <div className="rounded-xl border border-tint-border bg-tint-panel p-5 text-sm">
          <p className="mt-0 mb-2 font-semibold text-tint-ink">Unsupported flows</p>
          <p className="mt-0 mb-3 text-tint-muted">
            The demo transport omits <code>signUpPassword</code>, so the client refuses the call.
          </p>
          <button
            type="button"
            onClick={() => {
              try {
                void client.signUp.password({ identifier: email, password })
              } catch (error) {
                setUnsupported(error instanceof Error ? error.message : String(error))
              }
            }}
            className="rounded-md border border-tint-border px-3 py-1.5 text-sm text-tint-ink hover:bg-tint-surface"
          >
            Try to sign up
          </button>
          {unsupported ? (
            <p role="alert" className="mt-3 mb-0 text-tint-danger">
              {unsupported}
            </p>
          ) : null}
        </div>
      </div>
    </div>
  )
}

export function AuthDoc() {
  // One client for the life of the page; the demo transport holds its state in a closure.
  const client = useMemo(
    () => createTintClient({
      request: { async send() { throw new Error('The auth demo uses its injected transport.') } },
      auth: createAuthClient({ transport: createDemoTransport(), broadcastChannel: false }),
    }),
    [],
  )

  return (
    <DocsPage
      route="components/auth"
      title="Auth"
      intro="Controlled sign-in primitives over a transport-agnostic session client. Your application owns the network; Tint owns the state machine and the markup."
    >
      <DocsSection
        id="preview"
        title="Preview"
        description="Sign in, pass MFA, sign out — every step runs through the client state machine, and the AuthSnapshot panel tracks it live."
      >
        <DocsDemo code={previewDemoCode}>
          <TintClientProvider client={client}>
            <AuthDemo />
          </TintClientProvider>
        </DocsDemo>

        <div className="mt-4">
          <DocsCallout variant="note" title="Demo transport — no network">
            The page talks to an in-memory transport, so nothing leaves the browser. The credential
            table below is the full fixture; the transport also omits <code>signUpPassword</code>{' '}
            to show how unsupported flows fail.
          </DocsCallout>
        </div>

        <div className="mt-6 overflow-x-auto rounded-xl border border-tint-border bg-tint-panel">
          <table className="min-w-full border-collapse text-left text-sm">
            <thead className="bg-tint-surface text-tint-muted">
              <tr>
                <th className="px-4 py-3 font-medium">Email</th>
                <th className="px-4 py-3 font-medium">Password</th>
                <th className="px-4 py-3 font-medium">Result</th>
              </tr>
            </thead>
            <tbody>
              {DEMO_CREDENTIALS.map((row) => (
                <tr key={row.email} className="border-t border-tint-border align-top">
                  <td className="px-4 py-3 font-mono text-[13px] text-tint-accent">{row.email}</td>
                  <td className="px-4 py-3 font-mono text-[13px] text-tint-ink">{row.password}</td>
                  <td className="px-4 py-3 text-tint-muted">{row.outcome}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </DocsSection>

      <DocsSection
        id="usage"
        title="Usage"
        description="Wire auth into TintClientProvider, then drive IdentifierSignInForm from controlled state. The snapshot carries busy and error back to the form."
      >
        <CodeBlock code={usageCode} language="tsx" />
        <p className="mt-6 mb-3 max-w-3xl text-sm leading-6 text-tint-muted">
          The client talks to your backend through one interface. Which optional methods you
          implement is what decides which flows exist.
        </p>
        <CodeBlock code={transportCode} language="ts" />
      </DocsSection>

      <DocsSection id="api" title="API" description="Required props are marked with an asterisk.">
        <div className="space-y-10">
          <div>
            <h3 className="mb-3 text-lg font-semibold tracking-tight text-tint-ink">IdentifierSignInForm</h3>
            <p className="mt-0 mb-3 text-sm leading-6 text-tint-muted">
              The full prop signature, from the source:
            </p>
            <div className="mb-4">
              <CodeBlock code={signInFormSignature} language="tsx" />
            </div>
            <PropsTable rows={signInFormProps} />
          </div>
          <div>
            <h3 className="mb-3 text-lg font-semibold tracking-tight text-tint-ink">OAuthButtons</h3>
            <p className="mt-0 mb-3 text-sm leading-6 text-tint-muted">
              The full prop signature, from the source:
            </p>
            <div className="mb-4">
              <CodeBlock code={oauthSignature} language="tsx" />
            </div>
            <PropsTable rows={oauthProps} />
          </div>
          <div>
            <h3 className="mb-3 text-lg font-semibold tracking-tight text-tint-ink">useSession()</h3>
            <p className="mt-0 mb-3 text-sm leading-6 text-tint-muted">
              The derived session shape, from the source:
            </p>
            <div className="mb-4">
              <CodeBlock code={sessionSignature} language="tsx" />
            </div>
            <PropsTable rows={sessionProps} />
          </div>
          <div>
            <h3 className="mb-3 text-lg font-semibold tracking-tight text-tint-ink">AuthTransport</h3>
            <p className="mt-0 mb-3 text-sm leading-6 text-tint-muted">
              The full transport signature, from the source:
            </p>
            <div className="mb-4">
              <CodeBlock code={transportSignature} language="tsx" />
            </div>
            <PropsTable rows={transportProps} />
          </div>
        </div>
      </DocsSection>

      <DocsFooter>
        <span>Demo transport: in-memory fixture, no network</span>
      </DocsFooter>
    </DocsPage>
  )
}
