// src/svelte/components/theme/ThemeToggle.svelte
<script lang="ts">
  import { SCHEME_OPTIONS, nextColorSchemePreference, type ColorSchemePreference } from '../../../core/theme'
  import Icon from '../icon/Icon.svelte'
  import { THEME_GLYPHS } from '../icon/glyphs'
  import type { ThemeToggleProps } from './types'

  let {
    value, onChange, label = 'Color scheme', showLabels = false, disabled = false,
    class: className, onkeydown: externalKeydown, ...rest
  }: ThemeToggleProps = $props()
  let group = $state<HTMLDivElement | null>(null)

  function choose(next: ColorSchemePreference) {
    if (disabled) return
    onChange(next)
    group?.querySelector<HTMLButtonElement>(`[data-scheme-option="${next}"]`)?.focus()
  }

  function keydown(event: KeyboardEvent) {
    if (disabled) return
    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      event.preventDefault(); choose(nextColorSchemePreference(value, 1))
    } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      event.preventDefault(); choose(nextColorSchemePreference(value, -1))
    } else if (event.key === 'Home') {
      event.preventDefault(); choose(SCHEME_OPTIONS[0].value)
    } else if (event.key === 'End') {
      event.preventDefault(); choose(SCHEME_OPTIONS[SCHEME_OPTIONS.length - 1].value)
    }
    externalKeydown?.(event as KeyboardEvent & { currentTarget: HTMLDivElement })
  }
</script>

<div {...rest} bind:this={group} role="radiogroup" aria-label={label} data-tint-theme-toggle="" class={['theme-toggle', className].filter(Boolean).join(' ')} onkeydown={keydown}>
  {#each SCHEME_OPTIONS as option (option.value)}
    {@const selected = option.value === value}
    <button type="button" role="radio" aria-checked={selected} aria-label={showLabels ? undefined : option.label} data-scheme-option={option.value} tabindex={selected ? 0 : -1} {disabled} onclick={() => choose(option.value)}>
      <Icon icon={THEME_GLYPHS[option.value]} size="sm" />
      {#if showLabels}<span>{option.label}</span>{/if}
    </button>
  {/each}
</div>

<style>
  .theme-toggle { display: inline-flex; max-width: 100%; flex-wrap: wrap; align-items: center; gap: 2px; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-surface); padding: 2px; }
  button { display: inline-flex; min-width: 2rem; min-height: 2rem; align-items: center; justify-content: center; gap: var(--tint-space-1); border: 0; border-radius: var(--tint-radius-md); background: transparent; padding: var(--tint-space-1) var(--tint-space-2); color: var(--tint-muted); cursor: pointer; font: inherit; font-size: var(--tint-font-size-xs); font-weight: 500; }
  button:hover:not(:disabled) { color: var(--tint-ink); }
  button[aria-checked='true'] { background: var(--tint-panel); color: var(--tint-ink); box-shadow: 0 1px 3px var(--tint-shadow-color); }
  button:disabled { cursor: not-allowed; opacity: .5; }
  button:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
</style>

// src/components/theme/ThemeToggle.tsx
import { Monitor, Moon, Sun } from 'lucide-react'
import { useRef, type KeyboardEvent } from 'react'
import { cn } from '../../lib/utils'
import { Icon } from '../icon'
import type { ColorSchemePreference, ThemeToggleProps } from './types'

const OPTIONS = [
  { value: 'light', label: 'Light', icon: Sun },
  { value: 'system', label: 'System', icon: Monitor },
  { value: 'dark', label: 'Dark', icon: Moon },
] as const satisfies readonly {
  value: ColorSchemePreference
  label: string
  icon: typeof Sun
}[]

/**
 * A three-state light / system / dark control.
 *
 * Controlled, like the rest of the library — `useColorScheme` owns the state and
 * this renders it, so an app with its own preference store can drop its values
 * in without inheriting a second source of truth.
 *
 * Implemented as a radiogroup: one tab stop, arrows move between options, and
 * moving selects. That is the WAI-ARIA pattern for an exclusive choice, and it
 * is why this is not three `aria-pressed` buttons.
 */
export function ThemeToggle({
  value,
  onChange,
  label = 'Color scheme',
  showLabels = false,
  className,
  onKeyDown,
  ...props
}: ThemeToggleProps) {
  const groupRef = useRef<HTMLDivElement>(null)

  const move = (delta: number) => {
    const index = OPTIONS.findIndex((option) => option.value === value)
    const next = OPTIONS[(index + delta + OPTIONS.length) % OPTIONS.length]
    if (!next) return
    onChange(next.value)
    // Selection follows focus, so focus has to follow selection too.
    groupRef.current
      ?.querySelector<HTMLButtonElement>(`[data-scheme-option="${next.value}"]`)
      ?.focus()
  }

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      event.preventDefault()
      move(1)
    } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      event.preventDefault()
      move(-1)
    } else if (event.key === 'Home') {
      event.preventDefault()
      onChange(OPTIONS[0].value)
    } else if (event.key === 'End') {
      event.preventDefault()
      onChange(OPTIONS[OPTIONS.length - 1].value)
    }
    onKeyDown?.(event)
  }

  return (
    <div
      ref={groupRef}
      role="radiogroup"
      aria-label={label}
      data-tint-theme-toggle=""
      onKeyDown={handleKeyDown}
      className={cn(
        'inline-flex items-center gap-0.5 rounded-lg border border-tint-border bg-tint-surface p-0.5',
        className,
      )}
      {...props}
    >
      {OPTIONS.map(({ value: option, label: optionLabel, icon: OptionIcon }) => {
        const selected = option === value
        return (
          <button
            key={option}
            type="button"
            role="radio"
            aria-checked={selected}
            aria-label={showLabels ? undefined : optionLabel}
            data-scheme-option={option}
            // Roving tab stop: the group is a single stop, arrows do the rest.
            tabIndex={selected ? 0 : -1}
            onClick={() => onChange(option)}
            className={cn(
              'inline-flex items-center gap-1.5 rounded-md px-2 py-1.5 text-xs font-medium transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent',
              selected
                ? 'bg-tint-panel text-tint-ink shadow-sm'
                : 'text-tint-muted hover:text-tint-ink',
            )}
          >
            <Icon icon={OptionIcon} size="sm" />
            {showLabels ? optionLabel : null}
          </button>
        )
      })}
    </div>
  )
}
