// src/components/chat/ChatMessageList.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type FocusEvent,
  type KeyboardEvent,
  type UIEvent,
} from 'react'
import { cn } from '../../lib/utils'
import { Spinner } from '../icon'
import { ChatMessage } from './ChatMessage'
import { ChatPlaybackContext, type ChatPlaybackSlot } from './ChatPlaybackContext'
import { ChatEmptyState, ChatScrollToBottom } from './ChatPrimitives'
import { stripBidi } from './sanitize'
import type {
  ChatCustomPart,
  ChatId,
  ChatMessageData,
  ChatMessageGroupPosition,
  ChatMessageListProps,
} from './types'

const FOLLOW_THRESHOLD = 72

const INTERACTIVE = 'button, a, textarea, input, summary, audio'

/**
 * Where each message sits in its run of consecutive messages from one actor.
 * Computed once per render for the whole list — the alignment, avatar, and
 * header decisions all read the same answer.
 */
function groupPositions<TCustomPart extends ChatCustomPart>(
  messages: readonly ChatMessageData<TCustomPart>[],
): ChatMessageGroupPosition[] {
  return messages.map((current, index) => {
    const sameBefore = messages[index - 1]?.actor.id === current.actor.id
    const sameAfter = messages[index + 1]?.actor.id === current.actor.id
    if (sameBefore && sameAfter) return 'middle'
    if (sameBefore) return 'last'
    if (sameAfter) return 'first'
    return 'solo'
  })
}

/**
 * A one-line summary for the status region.
 *
 * The reader's own messages are skipped: they know what they just sent, and
 * "you finished responding" is noise on every turn.
 */
function statusAnnouncement<TCustomPart extends ChatCustomPart>(
  messages: readonly ChatMessageData<TCustomPart>[],
  currentActorId?: ChatId,
) {
  const message = messages.at(-1)
  if (!message) return ''
  if (message.actor.id === currentActorId || message.actor.kind === 'human') return ''

  const name = stripBidi(message.actor.name)
  if (message.status === 'streaming') return `${name} is responding`
  if (message.status === 'complete') return `${name} finished responding`
  if (message.status === 'error') return `${name}'s response failed`
  if (message.status === 'stopped') return `${name}'s response was stopped`
  return ''
}

export function ChatMessageList<TCustomPart extends ChatCustomPart = never>({
  messages,
  currentActorId,
  label = 'Messages',
  loading = false,
  hasEarlier = false,
  followOutput,
  enableRovingFocus = true,
  emptyState,
  renderPart,
  renderMessageFooter,
  onFollowOutputChange,
  onLoadEarlier,
  onMessageAction,
  onToolApproval,
  onRenderError,
  enableSpeak = false,
  speakingMessageId,
  onSpeakingMessageIdChange,
  className,
  onScroll,
  onKeyDown,
  onFocus,
  ref,
  ...props
}: ChatMessageListProps<TCustomPart>) {
  const viewportRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const previousLayout = useRef({
    firstId: messages[0]?.id,
    scrollHeight: 0,
  })
  const [internalFollowing, setInternalFollowing] = useState(true)
  const [activeIndex, setActiveIndex] = useState(Math.max(messages.length - 1, 0))
  const [hasUnseen, setHasUnseen] = useState(false)
  const seenLastId = useRef(messages.at(-1)?.id)
  // Until the reader moves the tab stop themselves, it tracks the newest message
  // so tabbing in lands on what just arrived rather than wherever the tail
  // happened to be when the list mounted.
  const tabStopMoved = useRef(false)
  const following = followOutput ?? internalFollowing
  const announcement = useMemo(
    () => statusAnnouncement(messages, currentActorId),
    [messages, currentActorId],
  )
  const positions = useMemo(() => groupPositions(messages), [messages])
  const messagesById = useMemo(
    () => new Map(messages.map((message) => [message.id, message])),
    [messages],
  )
  const isEmpty = messages.length === 0
  const [internalSpeaking, setInternalSpeaking] = useState<ChatId | null>(null)
  const [speakGeneration, setSpeakGeneration] = useState(0)
  const speaking = speakingMessageId !== undefined ? speakingMessageId : internalSpeaking
  const speakingRef = useRef(speaking)
  speakingRef.current = speaking

  const requestSpeak = useCallback(
    (messageId: ChatId) => {
      setSpeakGeneration((generation) =>
        speakingRef.current === messageId ? generation + 1 : 1,
      )
      if (speakingMessageId === undefined) setInternalSpeaking(messageId)
      onSpeakingMessageIdChange?.(messageId)
    },
    [onSpeakingMessageIdChange, speakingMessageId],
  )

  const clearSpeak = useCallback(
    (messageId: ChatId) => {
      if (speakingRef.current !== messageId) return
      if (speakingMessageId === undefined) setInternalSpeaking(null)
      onSpeakingMessageIdChange?.(null)
    },
    [onSpeakingMessageIdChange, speakingMessageId],
  )

  useEffect(() => {
    if (!speaking) return
    if (messages.some((message) => message.id === speaking)) return
    if (speakingMessageId === undefined) setInternalSpeaking(null)
    onSpeakingMessageIdChange?.(null)
  }, [messages, onSpeakingMessageIdChange, speaking, speakingMessageId])

  const playback = useMemo<ChatPlaybackSlot>(
    () => ({
      speakingMessageId: speaking,
      speakGeneration,
      requestSpeak,
      clearSpeak,
    }),
    [clearSpeak, requestSpeak, speakGeneration, speaking],
  )

  const setFollowing = useCallback(
    (next: boolean) => {
      if (followOutput === undefined) setInternalFollowing(next)
      onFollowOutputChange?.(next)
    },
    [followOutput, onFollowOutputChange],
  )

  const scrollToBottom = useCallback(
    (behavior: ScrollBehavior = 'smooth') => {
      const viewport = viewportRef.current
      if (!viewport) return
      viewport.scrollTo({ top: viewport.scrollHeight, behavior })
      setFollowing(true)
    },
    [setFollowing],
  )

  useLayoutEffect(() => {
    const viewport = viewportRef.current
    if (!viewport) return

    const firstId = messages[0]?.id
    const previous = previousLayout.current
    const prepended =
      previous.firstId !== undefined &&
      firstId !== previous.firstId &&
      messages.some((message) => message.id === previous.firstId)

    if (prepended) {
      viewport.scrollTop += viewport.scrollHeight - previous.scrollHeight
    } else if (following) {
      viewport.scrollTop = viewport.scrollHeight
    }

    previousLayout.current = {
      firstId,
      scrollHeight: viewport.scrollHeight,
    }
  }, [following, messages])

  // Content grows without the message array changing: an image finishes loading,
  // a disclosure opens, markdown settles. Without this the newest text drifts
  // below the fold while the list still believes it is pinned to the bottom.
  useEffect(() => {
    const viewport = viewportRef.current
    const content = contentRef.current
    if (!viewport || !content || typeof ResizeObserver === 'undefined') return

    const observer = new ResizeObserver(() => {
      if (!following) return
      viewport.scrollTop = viewport.scrollHeight
      previousLayout.current.scrollHeight = viewport.scrollHeight
    })
    observer.observe(content)
    return () => observer.disconnect()
    // Keyed on emptiness, not on `messages`: the content element only exists once
    // there is something to show, so the observer must re-attach across that
    // transition — but not on every arriving message.
  }, [following, isEmpty])

  useLayoutEffect(() => {
    const last = Math.max(messages.length - 1, 0)
    setActiveIndex((index) => (tabStopMoved.current ? Math.min(index, last) : last))
  }, [messages.length])

  // The affordance only claims "New messages" when something actually arrived
  // while the reader was scrolled away; otherwise it just offers a way back.
  useEffect(() => {
    const lastId = messages.at(-1)?.id
    if (following) {
      seenLastId.current = lastId
      setHasUnseen(false)
    } else if (lastId !== seenLastId.current) {
      setHasUnseen(true)
    }
  }, [following, messages])

  const handleScroll = (event: UIEvent<HTMLDivElement>) => {
    const viewport = event.currentTarget
    const nearBottom =
      viewport.scrollHeight - viewport.scrollTop - viewport.clientHeight <=
      FOLLOW_THRESHOLD
    if (nearBottom !== following) setFollowing(nearBottom)
    previousLayout.current.scrollHeight = viewport.scrollHeight
    onScroll?.(event)
  }

  const focusMessage = (index: number) => {
    const viewport = viewportRef.current
    const items = viewport?.querySelectorAll<HTMLElement>('[data-chat-message]')
    if (!items?.length) return
    const next = Math.max(0, Math.min(index, items.length - 1))
    tabStopMoved.current = true
    setActiveIndex(next)
    items[next]?.focus()
  }

  // One delegated handler instead of a closure per message — a fresh `onFocus`
  // on every render would make memoizing `ChatMessage` pointless.
  const handleFocus = (event: FocusEvent<HTMLDivElement>) => {
    const messageElement = (event.target as HTMLElement).closest<HTMLElement>(
      '[data-chat-message]',
    )
    if (messageElement) {
      const items = viewportRef.current?.querySelectorAll<HTMLElement>(
        '[data-chat-message]',
      )
      const index = items ? Array.prototype.indexOf.call(items, messageElement) : -1
      if (index >= 0) {
        tabStopMoved.current = true
        setActiveIndex(index)
      }
    }
    onFocus?.(event)
  }

  const handleKeyDown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (enableRovingFocus) {
      const messageElement = (event.target as HTMLElement).closest<HTMLElement>(
        '[data-chat-message]',
      )
      const interactive = (event.target as HTMLElement).closest(INTERACTIVE)

      if (messageElement && !interactive) {
        if (event.key === 'ArrowDown') {
          event.preventDefault()
          focusMessage(activeIndex + 1)
        } else if (event.key === 'ArrowUp') {
          event.preventDefault()
          focusMessage(activeIndex - 1)
        } else if (event.key === 'Home') {
          event.preventDefault()
          focusMessage(0)
        } else if (event.key === 'End') {
          event.preventDefault()
          focusMessage(messages.length - 1)
        } else if (event.key === 'Enter') {
          const target = messageElement.querySelector<HTMLElement>(INTERACTIVE)
          if (target) {
            event.preventDefault()
            target.focus()
          }
        }
      } else if (interactive && event.key === 'Escape' && messageElement) {
        event.preventDefault()
        messageElement.focus()
      }
    }

    onKeyDown?.(event)
  }

  return (
    <div className="relative min-h-0 flex-1">
      {/* Scroll, roving focus, and key handling are delegated from the viewport
          on purpose — see the roving-focus notes above. */}
      {/* oxlint-disable-next-line jsx-a11y/no-noninteractive-element-interactions */}
      <div
        ref={(node) => {
          viewportRef.current = node
          if (typeof ref === 'function') ref(node)
          else if (ref) ref.current = node
        }}
        role="log"
        aria-label={label}
        // Deliberately silent. `role="log"` implies `polite`, which would read
        // every streamed token aloud; the curated status region at the bottom of
        // this component announces turn boundaries instead.
        aria-live="off"
        data-chat-message-list=""
        data-following={following}
        className={cn(
          'h-full min-h-0 overflow-y-auto overscroll-contain px-4 py-5 sm:px-6',
          className,
        )}
        onScroll={handleScroll}
        onKeyDown={handleKeyDown}
        onFocus={handleFocus}
        {...props}
      >
        {hasEarlier ? (
          <div className="mb-6 flex justify-center">
            <button
              type="button"
              onClick={onLoadEarlier}
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-full border border-tint-border bg-tint-panel px-3 py-1.5 text-xs font-medium text-tint-muted hover:bg-tint-surface disabled:cursor-wait disabled:opacity-60 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
            >
              {loading ? <Spinner size="sm" /> : null}
              {loading ? 'Loading…' : 'Load earlier messages'}
            </button>
          </div>
        ) : null}

        {messages.length === 0 ? (
          emptyState ?? <ChatEmptyState />
        ) : (
          <ChatPlaybackContext.Provider value={enableSpeak ? playback : null}>
            <div
              ref={contentRef}
              className="mx-auto flex w-full max-w-3xl flex-col gap-5"
            >
              {messages.map((message, index) => {
                const position = positions[index] ?? 'solo'
                const startsGroup = position === 'solo' || position === 'first'

                return (
                  <ChatMessage
                    key={message.id}
                    message={message}
                    replyToMessage={
                      message.parentMessageId != null
                        ? messagesById.get(message.parentMessageId)
                        : undefined
                    }
                    alignment={
                      message.actor.id === currentActorId
                        ? 'end'
                        : message.actor.kind === 'system'
                          ? 'center'
                          : 'start'
                    }
                    groupPosition={position}
                    showActor={startsGroup}
                    showAvatar={startsGroup}
                    tabIndex={
                      enableRovingFocus ? (index === activeIndex ? 0 : -1) : undefined
                    }
                    renderPart={renderPart}
                    enableSpeak={enableSpeak}
                    speakingMessageId={speaking}
                    onAction={onMessageAction}
                    footer={renderMessageFooter?.(message)}
                    onToolApproval={onToolApproval}
                    onRenderError={onRenderError}
                  />
                )
              })}
            </div>
          </ChatPlaybackContext.Provider>
        )}
      </div>

      {!following ? (
        <div className="pointer-events-none absolute right-0 bottom-4 left-0 flex justify-center">
          <ChatScrollToBottom
            className="pointer-events-auto"
            onClick={() => scrollToBottom()}
          >
            {hasUnseen ? 'New messages' : 'Jump to latest'}
          </ChatScrollToBottom>
        </div>
      ) : null}

      <div className="sr-only" aria-live="polite" aria-atomic="true">
        {announcement}
      </div>
    </div>
  )
}

// src/svelte/components/chat/ChatMessageList.svelte
<script lang="ts">
  import { tick, untrack } from 'svelte'
  import { chatGroupPositions, chatStatusAnnouncement, type ChatCustomPart, type ChatId } from '../../../core/chat'
  import ChatMessage from './ChatMessage.svelte'
  import type { ChatMessageListProps } from './types'

  const FOLLOW_THRESHOLD = 72
  const INTERACTIVE = 'button, a, textarea, input, select, summary, audio, video, [role="button"], [role="radio"], [role="slider"], [contenteditable="true"]'
  let { messages, currentActorId, label = 'Messages', loading = false, hasEarlier = false,
    followOutput, enableRovingFocus = true, emptyState, renderPart, renderMessageFooter, viewportRef,
    onFollowOutputChange, onLoadEarlier, onMessageAction, onToolApproval,
    enableSpeak = false, speakingMessageId, onSpeakingMessageIdChange, onRenderError,
    class: className, className: legacyClassName, ...rest
  }: ChatMessageListProps<ChatCustomPart> = $props()
  let viewport: HTMLDivElement | null = null
  let previousLayout: { firstId?: ChatId; scrollHeight: number } = { firstId: undefined, scrollHeight: 0 }
  let internalFollowing = $state(true)
  let following = $derived(followOutput ?? internalFollowing)
  let activeIndex = $state(untrack(() => Math.max(messages.length - 1, 0)))
  let tabStopMoved = false
  let hasUnseen = $state(false)
  let seenLastId = untrack(() => messages.at(-1)?.id)
  const playbackControlled = untrack(() => speakingMessageId !== undefined)
  let internalSpeaking = $state<ChatId | null>(null)
  let speaking = $derived(playbackControlled ? speakingMessageId ?? null : internalSpeaking)
  let speakGeneration = $state(0)
  let positions = $derived(chatGroupPositions(messages))
  let byId = $derived(new Map(messages.map((message) => [message.id, message])))
  let announcement = $derived(chatStatusAnnouncement(messages, currentActorId))

  function setFollowing(next: boolean) {
    if (followOutput === undefined) internalFollowing = next
    onFollowOutputChange?.(next)
  }

  function scrollToBottom(behavior: ScrollBehavior = 'smooth') {
    if (!viewport) return
    viewport.scrollTo?.({ top: viewport.scrollHeight, behavior })
    viewport.scrollTop = viewport.scrollHeight
    setFollowing(true)
  }

  $effect(() => {
    const firstId = messages[0]?.id
    const currentMessages = messages
    const shouldFollow = following
    let cancelled = false
    void tick().then(() => {
      if (cancelled || !viewport) return
      const old = previousLayout
      const prepended = old.firstId !== undefined && firstId !== old.firstId &&
        currentMessages.some((message) => message.id === old.firstId)
      if (prepended) viewport.scrollTop += viewport.scrollHeight - old.scrollHeight
      else if (shouldFollow) viewport.scrollTop = viewport.scrollHeight
      previousLayout = { firstId, scrollHeight: viewport.scrollHeight }
    })
    return () => { cancelled = true }
  })

  $effect(() => {
    const last = Math.max(messages.length - 1, 0)
    if (!tabStopMoved) activeIndex = last
    else activeIndex = Math.min(activeIndex, last)
  })

  $effect(() => {
    const lastId = messages.at(-1)?.id
    if (following) { seenLastId = lastId; hasUnseen = false }
    else if (lastId !== seenLastId) hasUnseen = true
  })

  function focusMessage(index: number) {
    const items = viewport?.querySelectorAll<HTMLElement>('[data-chat-message]')
    if (!items?.length) return
    const next = Math.max(0, Math.min(index, items.length - 1))
    tabStopMoved = true
    activeIndex = next
    items[next]?.focus()
  }

  function registerViewport(node: HTMLDivElement) {
    viewport = node
    viewportRef?.(node)
    const onScroll = () => {
      const nearBottom = node.scrollHeight - node.scrollTop - node.clientHeight <= FOLLOW_THRESHOLD
      if (nearBottom !== following) setFollowing(nearBottom)
      previousLayout.scrollHeight = node.scrollHeight
    }
    const onFocus = (event: FocusEvent) => {
      const message = (event.target as HTMLElement).closest<HTMLElement>('[data-chat-message]')
      if (!message) return
      const items = node.querySelectorAll<HTMLElement>('[data-chat-message]')
      const index = Array.prototype.indexOf.call(items, message) as number
      if (index >= 0) { tabStopMoved = true; activeIndex = index }
    }
    const onKeydown = (event: KeyboardEvent) => {
      if (!enableRovingFocus) return
      const target = event.target as HTMLElement
      const message = target.closest<HTMLElement>('[data-chat-message]')
      if (!message) return
      const interactive = target.closest(INTERACTIVE)
      if (!interactive) {
        if (event.key === 'ArrowDown') { event.preventDefault(); focusMessage(activeIndex + 1) }
        else if (event.key === 'ArrowUp') { event.preventDefault(); focusMessage(activeIndex - 1) }
        else if (event.key === 'Home') { event.preventDefault(); focusMessage(0) }
        else if (event.key === 'End') { event.preventDefault(); focusMessage(messages.length - 1) }
        else if (event.key === 'Enter') {
          const control = message.querySelector<HTMLElement>(INTERACTIVE)
          if (control) { event.preventDefault(); control.focus() }
        }
      } else if (event.key === 'Escape') { event.preventDefault(); message.focus() }
    }
    node.addEventListener('scroll', onScroll)
    node.addEventListener('focusin', onFocus)
    node.addEventListener('keydown', onKeydown)
    return { destroy: () => {
      node.removeEventListener('scroll', onScroll)
      node.removeEventListener('focusin', onFocus)
      node.removeEventListener('keydown', onKeydown)
      viewport = null
      viewportRef?.(null)
    } }
  }

  function registerContent(node: HTMLDivElement) {
    const observer = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(() => {
      if (!following || !viewport) return
      viewport.scrollTop = viewport.scrollHeight
      previousLayout.scrollHeight = viewport.scrollHeight
    })
    observer?.observe(node)
    return { destroy: () => { observer?.disconnect() } }
  }

  function requestSpeak(messageId: ChatId) {
    speakGeneration += 1
    if (!playbackControlled) internalSpeaking = messageId
    onSpeakingMessageIdChange?.(messageId)
  }

  function clearSpeak(messageId: ChatId) {
    if (speaking !== messageId) return
    if (!playbackControlled) internalSpeaking = null
    onSpeakingMessageIdChange?.(null)
  }
</script>

<div class="relative min-h-0 flex-1">
  <div use:registerViewport {...rest} role="log" aria-label={label} aria-live="off" data-chat-message-list="" data-following={following}
    class={['h-full min-h-0 overflow-y-auto overscroll-contain px-4 py-5 sm:px-6', className, legacyClassName]}>
    {#if hasEarlier}<div class="mb-6 flex justify-center"><button type="button" onclick={onLoadEarlier} disabled={loading}
      class="rounded-full border border-tint-border bg-tint-panel px-3 py-1.5 text-xs font-medium text-tint-muted">{loading ? 'Loading…' : 'Load earlier messages'}</button></div>{/if}
    {#if messages.length === 0}
      {#if emptyState}{@render emptyState()}{:else}<section data-chat-empty-state="" class="m-auto max-w-sm px-6 py-12 text-center text-sm text-tint-muted">Start a conversation</section>{/if}
    {:else}
      <div use:registerContent class="mx-auto flex w-full max-w-3xl flex-col gap-5">
        {#each messages as message, index (message.id)}
          {@const position = positions[index] ?? 'solo'}
          {@const startsGroup = position === 'solo' || position === 'first'}
          <ChatMessage {message} replyToMessage={message.parentMessageId ? byId.get(message.parentMessageId) : undefined}
            alignment={message.actor.id === currentActorId ? 'end' : message.actor.kind === 'system' ? 'center' : 'start'}
            groupPosition={position} showActor={startsGroup} showAvatar={startsGroup}
            tabindex={enableRovingFocus ? index === activeIndex ? 0 : -1 : undefined}
            {renderPart} {renderMessageFooter} enableSpeak={enableSpeak} speakingMessageId={speaking} {speakGeneration}
            onSpeak={requestSpeak} onClearSpeak={clearSpeak}
            onAction={onMessageAction} onToolApproval={onToolApproval} {onRenderError} />
        {/each}
      </div>
    {/if}
  </div>
  {#if !following}<div class="pointer-events-none absolute right-0 bottom-4 left-0 flex justify-center"><button type="button" data-chat-scroll-to-bottom="" onclick={() => scrollToBottom()}
    class="pointer-events-auto rounded-full border border-tint-border bg-tint-panel px-3 py-2 text-xs font-medium shadow-lg">{hasUnseen ? 'New messages' : 'Jump to latest'}</button></div>{/if}
  <div class="sr-only" aria-live="polite" aria-atomic="true">{announcement}</div>
</div>
