// src/demos/discord-mod-panel/ModPanel.svelte
<script lang="ts">
  import { buildCorrelationIndex, bundleFor, runCorrelations } from '../discord-panel/correlation'
  import { createTraffic, NEBULA_GUILD_ID, PANEL_GUILDS, SIGNED_IN_USER, type GeneratedTraffic } from '../discord-panel/fixtures'
  import { EMPTY_FILTERS, filterInteractions, type InteractionFilters } from '../discord-panel/filters'
  import { EMPTY_ACTIVITY, filterActivity, type ActivityFilters } from './model'
  import type { CommandPaletteItem, StatusItem } from '../../svelte/components/shell/types'
  import MetricCard from '../../svelte/components/charts/MetricCard.svelte'
  import PanelTemplate from '../discord-panel/PanelTemplate.svelte'
  import InteractionFilterBar from '../discord-panel/InteractionFilterBar.svelte'
  import InteractionFeed from '../discord-panel/InteractionFeed.svelte'
  import InteractionMetrics from '../discord-panel/InteractionMetrics.svelte'
  import GuildActivityFeed from '../discord-panel/GuildActivityFeed.svelte'
  import CorrelationFindings from '../discord-panel/CorrelationFindings.svelte'
  import CommandRollupTable from '../discord-panel/CommandRollupTable.svelte'
  import ConversationTraceView from '../discord-panel/ConversationTraceView.svelte'
  import LinkedRecords from '../discord-panel/LinkedRecords.svelte'

  let { traffic: injected }: { traffic?: GeneratedTraffic } = $props()
  const nebula = PANEL_GUILDS.find((guild) => guild.id === NEBULA_GUILD_ID)!
  const fixture = createTraffic()[NEBULA_GUILD_ID]!
  let traffic = $derived(injected ?? fixture)
  let activeTab = $state('activity')
  let filters = $state<InteractionFilters>({ ...EMPTY_FILTERS })
  let activityFilters = $state<ActivityFilters>({ ...EMPTY_ACTIVITY })
  let selectedCorrelationId = $state<string | null>(null)
  let hasRun = $state(false)
  let paletteOpen = $state(false)
  let paletteQuery = $state('')
  let bundles = $derived(buildCorrelationIndex(traffic))
  let visible = $derived(filterInteractions(traffic.interactions, filters))
  let selected = $derived(bundleFor(bundles, selectedCorrelationId))
  let activity = $derived([...filterActivity(traffic.moderation, activityFilters)].sort((a, b) => b.tick - a.tick))
  let findings = $derived(hasRun ? runCorrelations(bundles.filter((bundle) => new Set(visible.map((item) => item.correlationId)).has(bundle.correlationId))) : [])
  let automated = $derived(traffic.moderation.filter((event) => event.automated).length)
  let escalations = $derived(traffic.moderation.filter((event) => event.kind === 'agent.escalation').length)
  let settledVisible = $derived(visible.filter((item) => item.status === 'replied' || item.status === 'failed').length)
  let kinds = $derived([...new Set(traffic.moderation.map((event) => event.kind))].sort())
  let statusItems = $derived<StatusItem[]>([
    { id: 'events', label: `${traffic.moderation.length} events`, tone: 'neutral' },
    { id: 'automated', label: `${automated} automated`, tone: automated ? 'info' : 'neutral' },
    { id: 'escalations', label: `${escalations} escalations`, tone: escalations ? 'danger' : 'neutral' },
    { id: 'selected', label: selectedCorrelationId ? `Following ${selectedCorrelationId}` : 'Nothing followed', tone: selectedCorrelationId ? 'accent' : 'neutral' },
  ])
  let paletteItems = $derived<CommandPaletteItem[]>([
    { id: 'view:activity', label: 'Show guild activity', group: 'Views' },
    { id: 'view:commands', label: 'Show the slash command feed', group: 'Views' },
    { id: 'view:correlations', label: 'Run correlations', group: 'Views' },
    { id: 'view:trace', label: 'Follow the selected trace', group: 'Views', disabled: selectedCorrelationId === null },
    { id: 'filter:automated', label: 'Show only automated actions', group: 'Filters' },
    { id: 'filter:failed', label: 'Show only failed interactions', group: 'Filters' },
    { id: 'filter:reset', label: 'Clear every filter', group: 'Filters' },
  ])
  const tabs = [
    { id: 'activity', label: 'Guild activity' }, { id: 'commands', label: 'Slash commands' },
    { id: 'correlations', label: 'Correlations' }, { id: 'trace', label: 'Agent trace' },
  ]
  function follow(id: string) { selectedCorrelationId = id; activeTab = 'trace' }
  function paletteSelect(id: string) {
    paletteOpen = false
    paletteQuery = ''
    if (id.startsWith('view:')) { activeTab = id.slice(5); if (activeTab === 'correlations') hasRun = true }
    else if (id === 'filter:automated') { activeTab = 'activity'; activityFilters = { ...activityFilters, automatedOnly: true } }
    else if (id === 'filter:failed') { activeTab = 'commands'; filters = { ...filters, status: 'failed' } }
    else if (id === 'filter:reset') { filters = { ...EMPTY_FILTERS }; activityFilters = { ...EMPTY_ACTIVITY } }
  }
</script>

<PanelTemplate product="Nebula" productSubtitle="Moderation" signedInAs={SIGNED_IN_USER} guilds={PANEL_GUILDS}
  guildId={NEBULA_GUILD_ID} onGuildChange={() => undefined} guildSwitching={false} {tabs} {activeTab}
  onActiveTabChange={(id) => { activeTab = id }} connection={{ state: 'connected', label: 'Gateway connected' }} {statusItems}
  {paletteItems} onPaletteSelect={paletteSelect} {paletteOpen} onPaletteOpenChange={(open) => { paletteOpen = open }}
  {paletteQuery} onPaletteQueryChange={(query) => { paletteQuery = query }}>
  {#snippet content(tabId)}
    {#if tabId === 'activity'}
      <div class="grid min-w-0 gap-4">
        <div class="grid gap-3 @xl:grid-cols-2 @4xl:grid-cols-4">
          <MetricCard label="Events" value={String(traffic.moderation.length)} hint="In the retained window" tone="accent" />
          <MetricCard label="Automated" value={String(automated)} hint="Taken by an agent" />
          <MetricCard label="Escalations" value={String(escalations)} hint={escalations ? 'Agent asked for a human' : 'None outstanding'} tone={escalations ? 'danger' : 'default'} />
          <MetricCard label="Channels" value={String(nebula.channels.length)} hint={nebula.channels.map((name) => `#${name}`).join(' ')} />
        </div>
        <div data-tint-filter-bar class="flex flex-wrap items-end gap-3 border-b border-tint-border bg-tint-panel p-3 text-xs">
          <label class="field">Channel<select value={activityFilters.channel} onchange={(event) => { activityFilters = { ...activityFilters, channel: event.currentTarget.value } }}><option value="all">Every channel</option>{#each nebula.channels as channel}<option value={channel}>#{channel}</option>{/each}</select></label>
          <label class="field">Event<select value={activityFilters.kind} onchange={(event) => { activityFilters = { ...activityFilters, kind: event.currentTarget.value } }}><option value="all">Every event</option>{#each kinds as kind}<option value={kind}>{kind}</option>{/each}</select></label>
          <label class="field">Automated only<input type="checkbox" checked={activityFilters.automatedOnly} onchange={(event) => { activityFilters = { ...activityFilters, automatedOnly: event.currentTarget.checked } }} /></label>
          <button type="button" disabled={JSON.stringify(activityFilters) === JSON.stringify(EMPTY_ACTIVITY)} onclick={() => { activityFilters = { ...EMPTY_ACTIVITY } }}>Reset</button>
        </div>
        <section class="card"><header><h2>Everything that happened</h2><span>{activity.length} shown</span></header><div class="p-4"><GuildActivityFeed events={activity} selectedId={selectedCorrelationId} onSelect={follow} /></div></section>
      </div>
    {:else if tabId === 'commands'}
      <div class="grid min-w-0 gap-4"><InteractionFilterBar interactions={traffic.interactions} {filters} onFiltersChange={(next) => { filters = next }} /><InteractionMetrics interactions={visible} />
        <section class="card"><header><h2>Interactions</h2><span>{visible.length} shown</span></header><div class="p-4"><InteractionFeed interactions={visible} selectedId={selectedCorrelationId} onSelect={follow} /></div></section></div>
    {:else if tabId === 'correlations'}
      <div class="grid min-w-0 gap-4"><InteractionFilterBar interactions={traffic.interactions} {filters} onFiltersChange={(next) => { filters = next }} />
        <CorrelationFindings {findings} {hasRun} sampleSize={settledVisible} onRun={() => { hasRun = true }} />
        <section class="card"><header><h2>By command</h2></header><div class="p-4"><CommandRollupTable interactions={visible} /></div></section></div>
    {:else if tabId === 'trace'}<ConversationTraceView bundle={selected} />{/if}
  {/snippet}
  {#snippet inspector()}<div class="grid content-start gap-4 p-4"><LinkedRecords bundle={selected} /><section class="card"><header><h2>Agents on duty</h2></header><ul class="m-0 grid list-none gap-2 p-4 text-sm"><li><strong>maya-agent</strong><small>Answers /ask from the guild archive.</small></li><li><strong>archivist</strong><small>Summarises channels and owns the search index.</small></li><li><strong>warden</strong><small>Policy checks, timeouts, and case files.</small></li></ul></section></div>{/snippet}
</PanelTemplate>

<style>
  .card { min-width: 0; overflow: hidden; border: 1px solid var(--tint-border); border-radius: .5rem; background: var(--tint-panel); }
  .card header { display: flex; justify-content: space-between; gap: .5rem; padding: .75rem 1rem; border-bottom: 1px solid var(--tint-border); }
  .card h2 { margin: 0; font-size: .875rem; }
  .card span, .card small { display: block; color: var(--tint-muted); font-size: .75rem; }
  .field { display: grid; gap: .3rem; }
  .field select { min-height: 2rem; border: 1px solid var(--tint-border); border-radius: .4rem; background: var(--tint-panel); color: var(--tint-ink); }
  button:focus-visible, select:focus-visible, input:focus-visible { outline: 2px solid var(--tint-accent); outline-offset: 2px; }
</style>

// src/demos/discord-mod-panel/ModPanel.tsx
/**
 * The system-nebula moderation panel.
 *
 * Same template, same correlation engine, different question. The bot panel
 * asks "what is the player doing"; this one asks "what happened in the guild,
 * and which of it was an agent's doing". Everything on screen is either a
 * moderation event or a slash command, and the two are joined on the same
 * correlation id, so an automated timeout leads straight to the agent turn
 * that decided on it.
 *
 * It is read-only on purpose. Acting on a case is a write that belongs behind
 * the operation seam, and inventing one here would be a button that lies.
 */
import { useCallback, useMemo, useState } from 'react'
import {
  buildCorrelationIndex,
  bundleFor,
  CommandRollupTable,
  ConversationTraceView,
  CorrelationFindings,
  createTraffic,
  EMPTY_FILTERS,
  filterInteractions,
  GuildActivityFeed,
  InteractionFeed,
  InteractionFilterBar,
  InteractionMetrics,
  LinkedRecords,
  NEBULA_GUILD_ID,
  PANEL_GUILDS,
  PanelTemplate,
  runCorrelations,
  SIGNED_IN_USER,
  type GeneratedTraffic,
  type InteractionFilters,
  type ModerationEvent,
} from '../discord-panel'
import type { CommandPaletteItem, WorkspaceTab } from '../../components/shell'
import { Card } from '../../components/surface'
import { MetricCard } from '../../components/charts'
import { FilterBar } from '../../components/shell'
import { FormControl, SelectField, ToggleField } from '../../components/form'
import { Button } from '../../components/button'

const NEBULA = PANEL_GUILDS.find((guild) => guild.id === NEBULA_GUILD_ID)!

export type ModPanelProps = {
  /** Injected by the test so it does not depend on the generated volume. */
  traffic?: GeneratedTraffic
}

type ActivityFilters = { channel: string; kind: string; automatedOnly: boolean }

const EMPTY_ACTIVITY: ActivityFilters = { channel: 'all', kind: 'all', automatedOnly: false }

/** Exported for the test: the activity list is the panel's headline surface. */
export function filterActivity(
  events: readonly ModerationEvent[],
  filters: ActivityFilters,
): readonly ModerationEvent[] {
  return events.filter((event) => {
    if (filters.channel !== 'all' && event.channel !== filters.channel) return false
    if (filters.kind !== 'all' && event.kind !== filters.kind) return false
    if (filters.automatedOnly && !event.automated) return false
    return true
  })
}

export function ModPanel({ traffic: injected }: ModPanelProps = {}) {
  const traffic = useMemo(() => injected ?? createTraffic()[NEBULA_GUILD_ID]!, [injected])

  const [activeTab, setActiveTab] = useState('activity')
  const [filters, setFilters] = useState<InteractionFilters>(EMPTY_FILTERS)
  const [activityFilters, setActivityFilters] = useState<ActivityFilters>(EMPTY_ACTIVITY)
  const [selectedCorrelationId, setSelectedCorrelationId] = useState<string | null>(null)
  const [hasRun, setHasRun] = useState(false)
  const [paletteOpen, setPaletteOpen] = useState(false)
  const [paletteQuery, setPaletteQuery] = useState('')

  const bundles = useMemo(() => buildCorrelationIndex(traffic), [traffic])
  const visible = useMemo(() => filterInteractions(traffic.interactions, filters), [traffic.interactions, filters])
  const selected = bundleFor(bundles, selectedCorrelationId)

  const activity = useMemo(
    () => [...filterActivity(traffic.moderation, activityFilters)].sort((left, right) => right.tick - left.tick),
    [traffic.moderation, activityFilters],
  )

  const findings = useMemo(() => {
    if (!hasRun) return []
    const visibleIds = new Set(visible.map((item) => item.correlationId))
    return runCorrelations(bundles.filter((bundle) => visibleIds.has(bundle.correlationId)))
  }, [hasRun, bundles, visible])

  const follow = useCallback((correlationId: string) => {
    setSelectedCorrelationId(correlationId)
    setActiveTab('trace')
  }, [])

  const automated = traffic.moderation.filter((event) => event.automated).length
  const escalations = traffic.moderation.filter((event) => event.kind === 'agent.escalation').length
  const settledVisible = visible.filter((item) => item.status === 'replied' || item.status === 'failed').length
  const kinds = useMemo(() => [...new Set(traffic.moderation.map((event) => event.kind))].sort(), [traffic.moderation])

  const paletteItems: readonly CommandPaletteItem[] = [
    { id: 'view:activity', label: 'Show guild activity', group: 'Views' },
    { id: 'view:commands', label: 'Show the slash command feed', group: 'Views' },
    { id: 'view:correlations', label: 'Run correlations', group: 'Views' },
    { id: 'view:trace', label: 'Follow the selected trace', group: 'Views', disabled: selectedCorrelationId === null },
    { id: 'filter:automated', label: 'Show only automated actions', group: 'Filters' },
    { id: 'filter:failed', label: 'Show only failed interactions', group: 'Filters' },
    { id: 'filter:reset', label: 'Clear every filter', group: 'Filters' },
  ]

  const onPaletteSelect = useCallback((id: string) => {
    setPaletteOpen(false)
    setPaletteQuery('')
    if (id.startsWith('view:')) {
      const view = id.slice('view:'.length)
      setActiveTab(view)
      if (view === 'correlations') setHasRun(true)
      return
    }
    if (id === 'filter:automated') {
      setActiveTab('activity')
      setActivityFilters((current) => ({ ...current, automatedOnly: true }))
      return
    }
    if (id === 'filter:failed') {
      setActiveTab('commands')
      setFilters((current) => ({ ...current, status: 'failed' }))
      return
    }
    if (id === 'filter:reset') {
      setFilters(EMPTY_FILTERS)
      setActivityFilters(EMPTY_ACTIVITY)
    }
  }, [])

  const tabs: readonly WorkspaceTab[] = [
    {
      id: 'activity',
      label: 'Guild activity',
      content: (
        <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4">
          <div className="grid gap-3 sm:grid-cols-4">
            <MetricCard label="Events" value={String(traffic.moderation.length)} hint="In the retained window" tone="accent" />
            <MetricCard label="Automated" value={String(automated)} hint="Taken by an agent" />
            <MetricCard
              label="Escalations"
              value={String(escalations)}
              hint={escalations > 0 ? 'Agent asked for a human' : 'None outstanding'}
              tone={escalations > 0 ? 'danger' : 'default'}
            />
            <MetricCard label="Channels" value={String(NEBULA.channels.length)} hint={NEBULA.channels.map((name) => `#${name}`).join(' ')} />
          </div>

          <FilterBar
            actions={
              <Button
                size="sm"
                variant="ghost"
                disabled={JSON.stringify(activityFilters) === JSON.stringify(EMPTY_ACTIVITY)}
                onClick={() => setActivityFilters(EMPTY_ACTIVITY)}
              >
                Reset
              </Button>
            }
          >
            <FormControl id="activity-channel" label="Channel">
              <SelectField
                id="activity-channel"
                value={activityFilters.channel}
                onChange={(channel) => setActivityFilters((current) => ({ ...current, channel }))}
                options={[
                  { value: 'all', label: 'Every channel' },
                  ...NEBULA.channels.map((name) => ({ value: name, label: `#${name}` })),
                ]}
              />
            </FormControl>
            <FormControl id="activity-kind" label="Event">
              <SelectField
                id="activity-kind"
                value={activityFilters.kind}
                onChange={(kind) => setActivityFilters((current) => ({ ...current, kind }))}
                options={[{ value: 'all', label: 'Every event' }, ...kinds.map((value) => ({ value, label: value }))]}
              />
            </FormControl>
            <FormControl id="activity-automated" label="Automated only">
              <ToggleField
                id="activity-automated"
                checked={activityFilters.automatedOnly}
                onChange={(automatedOnly) => setActivityFilters((current) => ({ ...current, automatedOnly }))}
              />
            </FormControl>
          </FilterBar>

          <Card header="Everything that happened" actions={<span className="text-xs text-tint-muted">{activity.length} shown</span>}>
            <GuildActivityFeed events={activity} onSelect={follow} selectedId={selectedCorrelationId} />
          </Card>
        </div>
      ),
    },
    {
      id: 'commands',
      label: 'Slash commands',
      content: (
        <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4">
          <InteractionFilterBar interactions={traffic.interactions} filters={filters} onFiltersChange={setFilters} />
          <InteractionMetrics interactions={visible} />
          <Card header="Interactions" actions={<span className="text-xs text-tint-muted">{visible.length} shown</span>}>
            <InteractionFeed interactions={visible} selectedId={selectedCorrelationId} onSelect={follow} />
          </Card>
        </div>
      ),
    },
    {
      id: 'correlations',
      label: 'Correlations',
      content: (
        <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4">
          <InteractionFilterBar interactions={traffic.interactions} filters={filters} onFiltersChange={setFilters} />
          <CorrelationFindings findings={findings} hasRun={hasRun} sampleSize={settledVisible} onRun={() => setHasRun(true)} />
          <Card header="By command">
            <CommandRollupTable interactions={visible} />
          </Card>
        </div>
      ),
    },
    {
      id: 'trace',
      label: 'Agent trace',
      // Mounted only while open — the service map pulls in the graph engine.
      content: activeTab === 'trace' ? <ConversationTraceView bundle={selected} /> : null,
    },
  ]

  return (
    <PanelTemplate
      product="Nebula"
      productSubtitle="Moderation"
      signedInAs={SIGNED_IN_USER}
      guilds={PANEL_GUILDS}
      guildId={NEBULA_GUILD_ID}
      onGuildChange={() => undefined}
      // This panel is the system-nebula view. Offering the other guilds in the
      // rail and then ignoring the click would be worse than disabling them.
      guildSwitching={false}
      tabs={tabs}
      activeTab={activeTab}
      onActiveTabChange={setActiveTab}
      connection={{ state: 'connected', label: 'Gateway connected' }}
      statusItems={[
        { id: 'events', label: `${traffic.moderation.length} events`, tone: 'neutral' },
        { id: 'automated', label: `${automated} automated`, tone: automated > 0 ? 'info' : 'neutral' },
        { id: 'escalations', label: `${escalations} escalations`, tone: escalations > 0 ? 'danger' : 'neutral' },
        {
          id: 'selected',
          label: selectedCorrelationId ? `Following ${selectedCorrelationId}` : 'Nothing followed',
          tone: selectedCorrelationId ? 'accent' : 'neutral',
        },
      ]}
      paletteItems={paletteItems}
      onPaletteSelect={onPaletteSelect}
      paletteOpen={paletteOpen}
      onPaletteOpenChange={setPaletteOpen}
      paletteQuery={paletteQuery}
      onPaletteQueryChange={setPaletteQuery}
      inspector={
        <div className="grid content-start gap-4 p-4">
          <LinkedRecords bundle={selected} />
          <Card header="Agents on duty">
            <ul className="m-0 grid list-none gap-2 p-0 text-sm">
              <li>
                <span className="font-medium">maya-agent</span>
                <span className="block text-xs text-tint-muted">Answers /ask from the guild archive.</span>
              </li>
              <li>
                <span className="font-medium">archivist</span>
                <span className="block text-xs text-tint-muted">Summarises channels and owns the search index.</span>
              </li>
              <li>
                <span className="font-medium">warden</span>
                <span className="block text-xs text-tint-muted">Policy checks, timeouts, and case files.</span>
              </li>
            </ul>
          </Card>
        </div>
      }
    />
  )
}
