// src/svelte/components/policy/PolicyDryRun.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import { countMatches, mockDryRun, type DryRunResult } from '../../../core/policy'
  import Badge from '../badge/Badge.svelte'
  import type { PolicyDryRunProps } from './types'

  let { rule, entries, class: className }: PolicyDryRunProps = $props()
  let entryId = $state(untrack(() => entries[0]?.id ?? ''))
  let entry = $derived(entries.find((item) => item.id === entryId) ?? entries[0])
  let result = $state<DryRunResult>(untrack(() => entries[0] ? mockDryRun(entries[0], rule) : { matched: false, note: 'No entries.' }))
  let matchTotal = $derived(countMatches(entries, rule))

  function run() {
    if (entry) result = mockDryRun(entry, rule)
  }
</script>

<div data-tint-policy-dry-run="" class={['dry-run', className].filter(Boolean).join(' ')}>
  <div class="controls">
    <label><span>Fixture entry</span><select value={entry?.id ?? ''} onchange={(event) => entryId = event.currentTarget.value}>
      {#each entries as item (item.id)}<option value={item.id}>{item.title}</option>{/each}
    </select></label>
    <button type="button" class="run" disabled={!entry} onclick={run}>Run dry-run</button>
  </div>
  <p class="summary">Builder / mocked Lua would match <strong>{matchTotal}</strong> of {entries.length} fixture entries for “{rule.name}”.</p>
  <div class="result" aria-live="polite">
    <div class="badges"><Badge tone={result.matched ? 'success' : 'neutral'}>{result.matched ? 'matched' : 'no match'}</Badge>{#if result.disposition}<Badge tone="accent">{result.disposition}</Badge>{/if}</div>
    {#if result.note}<p>{result.note}</p>{/if}
  </div>
</div>

<style>
  .dry-run { display: flex; min-width: 0; flex-direction: column; gap: var(--tint-space-3); border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-panel); padding: var(--tint-space-4); container-type: inline-size; }
  .controls { display: flex; flex-wrap: wrap; align-items: end; justify-content: space-between; gap: var(--tint-space-3); }
  label { display: flex; min-width: 12rem; flex: 1; flex-direction: column; gap: var(--tint-space-1); font-size: var(--tint-font-size-sm); }
  label span { color: var(--tint-muted); font-size: var(--tint-font-size-xs); font-weight: 500; }
  select { min-width: 0; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-surface); padding: var(--tint-space-1) var(--tint-space-2); color: var(--tint-ink); font: inherit; }
  .run { min-height: 2rem; border: 1px solid var(--tint-accent); border-radius: var(--tint-radius-sm); background: var(--tint-accent); padding: 0 var(--tint-space-3); color: var(--tint-on-accent); cursor: pointer; font: inherit; font-size: var(--tint-font-size-sm); }
  .run:disabled { opacity: 0.5; cursor: not-allowed; }
  .summary { margin: 0; color: var(--tint-muted); font-size: var(--tint-font-size-xs); }
  .summary strong { color: var(--tint-ink); }
  .result { border: 1px solid var(--tint-border); border-radius: var(--tint-radius-md); background: var(--tint-surface); padding: var(--tint-space-3); font-size: var(--tint-font-size-sm); }
  .badges { display: flex; flex-wrap: wrap; align-items: center; gap: var(--tint-space-2); }
  .result p { margin: var(--tint-space-2) 0 0; color: var(--tint-muted); }
  :is(select, button):focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  @container (max-width: 340px) { label { min-width: 0; width: 100%; } .run { width: 100%; } }
</style>

// src/components/policy/PolicyDryRun.tsx
import { useMemo, useState } from 'react'
import { Badge } from '../badge'
import { Button } from '../button'
import { cn } from '../../lib/utils'
import type { FeedEntry } from '../feed/contracts'
import { countMatches, mockDryRun, type PolicyRule } from './contracts'

export type PolicyDryRunProps = {
  rule: Pick<PolicyRule, 'criteria' | 'disposition' | 'enabled' | 'name'>
  entries: readonly FeedEntry[]
  className?: string
}

/**
 * Pick a fixture FeedEntry, run `mockDryRun`, show the result.
 *
 * Builder clauses evaluate for real; Lua returns fixture-scripted results — no
 * Lua VM ships in the browser.
 */
export function PolicyDryRun({ rule, entries, className }: PolicyDryRunProps) {
  const [entryId, setEntryId] = useState(entries[0]?.id ?? '')
  const entry = entries.find((item) => item.id === entryId) ?? entries[0]
  const [result, setResult] = useState(() =>
    entry ? mockDryRun(entry, rule) : { matched: false, note: 'No entries.' },
  )

  const matchTotal = useMemo(() => countMatches(entries, rule), [entries, rule])

  return (
    <div
      data-tint-policy-dry-run=""
      className={cn(
        'flex flex-col gap-3 rounded-xl border border-tint-border bg-tint-panel p-4',
        className,
      )}
    >
      <div className="flex flex-wrap items-end justify-between gap-3">
        <label className="flex min-w-[12rem] flex-1 flex-col gap-1 text-sm">
          <span className="text-xs font-medium text-tint-muted">Fixture entry</span>
          <select
            className="rounded-md border border-tint-border bg-tint-surface px-2 py-1.5 text-sm"
            value={entry?.id ?? ''}
            onChange={(event) => setEntryId(event.target.value)}
          >
            {entries.map((item) => (
              <option key={item.id} value={item.id}>
                {item.title}
              </option>
            ))}
          </select>
        </label>
        <Button
          size="sm"
          variant="primary"
          disabled={!entry}
          onClick={() => {
            if (entry) setResult(mockDryRun(entry, rule))
          }}
        >
          Run dry-run
        </Button>
      </div>

      <p className="m-0 text-xs text-tint-muted">
        Builder / mocked Lua would match <strong className="text-tint-ink">{matchTotal}</strong> of{' '}
        {entries.length} fixture entries for “{rule.name}”.
      </p>

      <div className="rounded-lg border border-tint-border bg-tint-surface p-3 text-sm">
        <div className="mb-2 flex flex-wrap items-center gap-2">
          <Badge tone={result.matched ? 'success' : 'neutral'}>
            {result.matched ? 'matched' : 'no match'}
          </Badge>
          {result.disposition ? <Badge tone="accent">{result.disposition}</Badge> : null}
        </div>
        {result.note ? <p className="m-0 text-tint-muted">{result.note}</p> : null}
      </div>
    </div>
  )
}
