// src/components/table/DataFilterControls.tsx
import { ArrowDown, ArrowUp, Filter, Plus, X } from 'lucide-react'
import { useId, useMemo, useState } from 'react'
import { Icon } from '../icon'
import { cn } from '../../lib/utils'
import type {
  DataFilterField,
  DataFilterItem,
  DataFilterModel,
  DataFilterOperator,
  DataSortingState,
} from './filterTypes'

const TEXT_OPERATORS: readonly DataFilterOperator[] = ['contains', 'equals', 'notEquals']
const NUMBER_OPERATORS: readonly DataFilterOperator[] = ['equals', 'gte', 'lte', 'gt', 'lt']
const OPERATOR_LABELS: Record<DataFilterOperator, string> = {
  contains: 'contains',
  equals: 'is',
  notEquals: 'is not',
  gt: 'greater than',
  gte: 'at least',
  lt: 'less than',
  lte: 'at most',
}

export type DataFilterControlsProps = {
  fields: readonly DataFilterField[]
  filterModel: DataFilterModel
  onFilterModelChange: (model: DataFilterModel) => void
  sorting?: DataSortingState
  onSortingChange?: (sorting: DataSortingState) => void
  allowAdd?: boolean
  className?: string
  addLabel?: string
  sortLabel?: string
}

function operatorsFor(field: DataFilterField): readonly DataFilterOperator[] {
  if (field.operators?.length) return field.operators
  return field.type === 'number' ? NUMBER_OPERATORS : TEXT_OPERATORS
}

function optionLabel(field: DataFilterField, value: string | number): string {
  return field.options?.find((option) => String(option.value) === String(value))?.label ?? String(value)
}

function newFilterId(): string {
  return globalThis.crypto?.randomUUID?.() ?? `filter-${Date.now()}`
}

export function DataFilterControls({
  fields,
  filterModel,
  onFilterModelChange,
  sorting = [],
  onSortingChange,
  allowAdd = true,
  className,
  addLabel = 'Add filter',
  sortLabel = 'Sort results',
}: DataFilterControlsProps) {
  const formId = useId()
  const [adding, setAdding] = useState(false)
  const [fieldId, setFieldId] = useState(fields[0]?.id ?? '')
  const field = fields.find((candidate) => candidate.id === fieldId) ?? fields[0]
  const operators = field ? operatorsFor(field) : []
  const [operator, setOperator] = useState<DataFilterOperator>(operators[0] ?? 'equals')
  const [value, setValue] = useState('')
  const activeSort = sorting[0]
  const sortableFields = useMemo(() => fields.filter((candidate) => candidate.sortable), [fields])

  const chooseField = (nextId: string) => {
    const nextField = fields.find((candidate) => candidate.id === nextId)
    setFieldId(nextId)
    setOperator(nextField ? operatorsFor(nextField)[0]! : 'equals')
    setValue('')
  }

  const addFilter = () => {
    if (!field || value === '') return
    const item: DataFilterItem = {
      id: newFilterId(),
      field: field.id,
      operator,
      value: field.type === 'number' ? Number(value) : value,
      displayValue: field.type === 'select' ? optionLabel(field, value) : undefined,
    }
    onFilterModelChange({ items: [...filterModel.items, item] })
    setValue('')
    setAdding(false)
  }

  const removeFilter = (id: string) => {
    onFilterModelChange({ items: filterModel.items.filter((item) => item.id !== id) })
  }

  return (
    <div
      data-filter-controls=""
      className={cn('flex min-w-0 flex-wrap items-center gap-2', className)}
    >
      {filterModel.items.map((item) => {
        const itemField = fields.find((candidate) => candidate.id === item.field)
        const label = itemField?.label ?? item.field
        const displayValue = item.displayValue ?? (itemField ? optionLabel(itemField, item.value) : String(item.value))
        return (
          <button
            key={item.id}
            type="button"
            onClick={() => removeFilter(item.id)}
            aria-label={`Remove ${label} ${displayValue} filter`}
            className="inline-flex min-h-8 items-center gap-1.5 rounded-full border border-tint-accent/30 bg-tint-accent-soft px-2.5 text-xs text-tint-ink transition hover:border-tint-accent focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
          >
            <span data-filter-label="" className="text-[0.625rem] font-semibold text-tint-muted">
              {label.toLowerCase()}:
            </span>
            <span data-filter-value="" className="font-medium">{displayValue}</span>
            <Icon icon={X} size="sm" aria-hidden="true" />
          </button>
        )
      })}

      {allowAdd && fields.length ? (
        <div className="relative">
          <button
            type="button"
            onClick={() => setAdding((open) => !open)}
            aria-expanded={adding}
            className="inline-flex min-h-8 items-center gap-1.5 rounded-lg border border-tint-border bg-tint-panel px-2.5 text-xs font-medium text-tint-muted hover:text-tint-ink focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent"
          >
            <Icon icon={Plus} size="sm" />
            {addLabel}
          </button>
          {adding ? (
            <div className="absolute top-[calc(100%+0.375rem)] left-0 z-30 grid w-72 gap-2 rounded-xl border border-tint-border bg-tint-panel p-3 shadow-xl">
              <label className="grid gap-1 text-xs text-tint-muted" htmlFor={`${formId}-field`}>
                Property
                <select id={`${formId}-field`} aria-label="Filter property" value={field?.id ?? ''} onChange={(event) => chooseField(event.target.value)} className="min-h-9 rounded-lg border border-tint-border bg-tint-surface px-2 text-tint-ink">
                  {fields.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}
                </select>
              </label>
              <label className="grid gap-1 text-xs text-tint-muted" htmlFor={`${formId}-operator`}>
                Operator
                <select id={`${formId}-operator`} aria-label="Filter operator" value={operator} onChange={(event) => setOperator(event.target.value as DataFilterOperator)} className="min-h-9 rounded-lg border border-tint-border bg-tint-surface px-2 text-tint-ink">
                  {operators.map((candidate) => <option key={candidate} value={candidate}>{OPERATOR_LABELS[candidate]}</option>)}
                </select>
              </label>
              <label className="grid gap-1 text-xs text-tint-muted" htmlFor={`${formId}-value`}>
                Value
                {field?.type === 'select' ? (
                  <select id={`${formId}-value`} aria-label="Filter value" value={value} onChange={(event) => setValue(event.target.value)} className="min-h-9 rounded-lg border border-tint-border bg-tint-surface px-2 text-tint-ink">
                    <option value="">Choose…</option>
                    {field.options?.map((option) => <option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}
                  </select>
                ) : (
                  <input id={`${formId}-value`} aria-label="Filter value" type={field?.type === 'number' ? 'number' : 'text'} value={value} onChange={(event) => setValue(event.target.value)} className="min-h-9 rounded-lg border border-tint-border bg-tint-surface px-2 text-tint-ink" />
                )}
              </label>
              <button type="button" onClick={addFilter} disabled={value === ''} className="min-h-9 rounded-lg bg-tint-accent px-3 text-xs font-semibold text-tint-on-accent disabled:opacity-50">
                Apply filter
              </button>
            </div>
          ) : null}
        </div>
      ) : null}

      {onSortingChange && sortableFields.length ? (
        <div className="ml-auto inline-flex items-center gap-1 rounded-lg border border-tint-border bg-tint-panel p-0.5">
          <Icon icon={Filter} size="sm" className="ml-1.5 text-tint-muted" aria-hidden="true" />
          <select
            aria-label={sortLabel}
            value={activeSort?.id ?? ''}
            onChange={(event) => onSortingChange(event.target.value ? [{ id: event.target.value, desc: false }] : [])}
            className="min-h-8 bg-transparent px-1.5 text-xs text-tint-ink outline-none"
          >
            <option value="">Default order</option>
            {sortableFields.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}
          </select>
          {activeSort ? (
            <button
              type="button"
              aria-label={activeSort.desc ? 'Sort ascending' : 'Sort descending'}
              onClick={() => onSortingChange([{ ...activeSort, desc: !activeSort.desc }])}
              className="grid size-8 place-items-center rounded-md text-tint-muted hover:bg-tint-surface hover:text-tint-ink focus-visible:outline-2 focus-visible:outline-tint-accent"
            >
              <Icon icon={activeSort.desc ? ArrowDown : ArrowUp} size="sm" />
            </button>
          ) : null}
        </div>
      ) : null}
    </div>
  )
}

// src/svelte/components/table/DataFilterControls.svelte
<script lang="ts">
  import type {
    DataFilterField, DataFilterModel, DataFilterOperator, DataSortingState,
  } from '../../../core/table/filterTypes'
  import { buildFilterItem, FILTER_OPERATOR_LABELS, operatorsFor, optionLabel } from '../../../core/table/filterControls'

  type Props = {
    fields: readonly DataFilterField[]
    filterModel: DataFilterModel
    onFilterModelChange: (model: DataFilterModel) => void
    sorting?: DataSortingState
    onSortingChange?: (sorting: DataSortingState) => void
    allowAdd?: boolean
    addLabel?: string
    sortLabel?: string
    class?: string
  }

  let {
    fields, filterModel, onFilterModelChange, sorting = [], onSortingChange,
    allowAdd = true, addLabel = 'Add filter', sortLabel = 'Sort results', class: className,
  }: Props = $props()

  const id = $props.id()
  let adding = $state(false)
  let fieldId = $state('')
  let operator = $state<DataFilterOperator>('equals')
  let value = $state('')
  let field = $derived(fields.find((candidate) => candidate.id === fieldId) ?? fields[0])
  let operators = $derived(field ? operatorsFor(field) : [])
  let sortableFields = $derived(fields.filter((candidate) => candidate.sortable))
  let activeSort = $derived(sorting[0])

  $effect(() => {
    if (fieldId || !fields[0]) return
    fieldId = fields[0].id
    operator = operatorsFor(fields[0])[0] ?? 'equals'
  })

  function chooseField(nextId: string) {
    fieldId = nextId
    const next = fields.find((candidate) => candidate.id === nextId)
    operator = next ? operatorsFor(next)[0] ?? 'equals' : 'equals'
    value = ''
  }

  function addFilter() {
    if (!field || value === '') return
    const filterId = globalThis.crypto?.randomUUID?.() ?? `filter-${Date.now()}`
    onFilterModelChange({ items: [...filterModel.items, buildFilterItem(filterId, field, operator, value)] })
    value = ''
    adding = false
  }

  function removeFilter(filterId: string) {
    onFilterModelChange({ items: filterModel.items.filter((item) => item.id !== filterId) })
  }
</script>

<div data-filter-controls="" class={className}>
  {#each filterModel.items as item (item.id)}
    {@const itemField = fields.find((candidate) => candidate.id === item.field)}
    {@const label = itemField?.label ?? item.field}
    {@const displayValue = item.displayValue ?? (itemField ? optionLabel(itemField, item.value) : String(item.value))}
    <button type="button" class="filter-chip" aria-label={`Remove ${label} ${displayValue} filter`} onclick={() => removeFilter(item.id)}>
      <span data-filter-label="">{label.toLowerCase()}:</span>
      <span data-filter-value="">{displayValue}</span>
      <span aria-hidden="true">×</span>
    </button>
  {/each}

  {#if allowAdd && fields.length}
    <div class="add-wrap">
      <button type="button" class="add-trigger" aria-expanded={adding} aria-controls={`${id}-form`} onclick={() => adding = !adding}><span aria-hidden="true">＋</span> {addLabel}</button>
      {#if adding}
        <div id={`${id}-form`} class="add-form">
          <label for={`${id}-field`}>Property
            <select class="tint-select" id={`${id}-field`} aria-label="Filter property" value={field?.id ?? ''} onchange={(event) => chooseField(event.currentTarget.value)}>
              {#each fields as candidate (candidate.id)}<option value={candidate.id}>{candidate.label}</option>{/each}
            </select>
          </label>
          <label for={`${id}-operator`}>Operator
            <select class="tint-select" id={`${id}-operator`} aria-label="Filter operator" value={operator} onchange={(event) => operator = event.currentTarget.value as DataFilterOperator}>
              {#each operators as candidate (candidate)}<option value={candidate}>{FILTER_OPERATOR_LABELS[candidate]}</option>{/each}
            </select>
          </label>
          <label for={`${id}-value`}>Value
            {#if field?.type === 'select'}
              <select class="tint-select" id={`${id}-value`} aria-label="Filter value" value={value} onchange={(event) => value = event.currentTarget.value}>
                <option value="">Choose…</option>
                {#each field.options ?? [] as option (String(option.value))}<option value={String(option.value)}>{option.label}</option>{/each}
              </select>
            {:else}
              <input id={`${id}-value`} aria-label="Filter value" type={field?.type === 'number' ? 'number' : 'text'} value={value} oninput={(event) => value = event.currentTarget.value} />
            {/if}
          </label>
          <button type="button" class="apply" disabled={value === ''} onclick={addFilter}>Apply filter</button>
        </div>
      {/if}
    </div>
  {/if}

  {#if onSortingChange && sortableFields.length}
    <div class="sort-controls">
      <select class="tint-select" aria-label={sortLabel} value={activeSort?.id ?? ''} onchange={(event) => onSortingChange?.(event.currentTarget.value ? [{ id: event.currentTarget.value, desc: false }] : [])}>
        <option value="">Default order</option>
        {#each sortableFields as candidate (candidate.id)}<option value={candidate.id}>{candidate.label}</option>{/each}
      </select>
      {#if activeSort}
        <button type="button" aria-label={activeSort.desc ? 'Sort ascending' : 'Sort descending'} onclick={() => onSortingChange?.([{ ...activeSort!, desc: !activeSort!.desc }])}>{activeSort.desc ? '↓' : '↑'}</button>
      {/if}
    </div>
  {/if}
</div>

<style>
  [data-filter-controls] { display: flex; min-width: 0; flex-wrap: wrap; align-items: center; gap: var(--tint-space-2); }
  button, select, input { font: inherit; }
  button { cursor: pointer; }
  button:focus-visible, select:focus-visible, input:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: 2px; }
  .filter-chip { display: inline-flex; align-items: center; gap: var(--tint-space-1); min-height: 2rem; border: 1px solid var(--tint-accent); border-radius: 999px; background: var(--tint-accent-soft); padding: 0 var(--tint-space-2); color: var(--tint-ink); font-size: var(--tint-font-size-xs); }
  [data-filter-label] { color: var(--tint-muted); font-size: 0.625rem; font-weight: 600; }
  .add-wrap { position: relative; }
  .add-trigger { min-height: 2rem; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-panel); padding: 0 var(--tint-space-2); color: var(--tint-muted); font-size: var(--tint-font-size-xs); }
  .add-form { position: absolute; top: calc(100% + 0.375rem); left: 0; z-index: 30; display: grid; width: 18rem; gap: var(--tint-space-2); border: 1px solid var(--tint-border); border-radius: var(--tint-radius-md); background: var(--tint-panel); padding: var(--tint-space-3); box-shadow: 0 1rem 3rem var(--tint-shadow-color); }
  .add-form label { display: grid; gap: var(--tint-space-1); color: var(--tint-muted); font-size: var(--tint-font-size-xs); }
  .add-form select, .add-form input { min-height: 2.25rem; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-surface); padding: 0 var(--tint-space-2); color: var(--tint-ink); }
  .apply { min-height: 2.25rem; border: 0; border-radius: var(--tint-radius-sm); background: var(--tint-accent); color: var(--tint-on-accent); font-size: var(--tint-font-size-xs); font-weight: 600; }
  .apply:disabled { cursor: not-allowed; opacity: 0.5; }
  .sort-controls { display: inline-flex; align-items: center; gap: var(--tint-space-1); margin-left: auto; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-sm); background: var(--tint-panel); padding: var(--tint-space-1); }
  .sort-controls select, .sort-controls button { min-height: 2rem; border: 0; background: transparent; color: var(--tint-ink); font-size: var(--tint-font-size-xs); }
</style>
