// src/components/theme/ThemePicker.tsx
import { ChevronDown, Palette } from 'lucide-react'
import { useId } from 'react'
import { cn } from '@/lib/utils'
import type { ThemePickerProps } from './types'

/**
 * Palette family picker.
 *
 * A native `<select>` rather than a custom listbox: the option set is small,
 * static, and this way it inherits platform keyboard behavior, mobile pickers,
 * and `color-scheme`-aware rendering for free.
 *
 * Controlled — pair it with `useThemeName`. The available themes are a property
 * of which theme stylesheets the app imported, so they are passed in.
 */
export function ThemePicker({
  value,
  onChange,
  themes,
  label = 'Theme',
  className,
  ...props
}: ThemePickerProps) {
  const id = useId()

  return (
    <div className="inline-flex items-center gap-2" data-tint-theme-picker="">
      <label htmlFor={id} className="sr-only">
        {label}
      </label>
      <div className="relative inline-flex items-center">
        <Palette
          className="pointer-events-none absolute left-2.5 size-3.5 text-tint-muted"
          aria-hidden="true"
        />
        <select
          id={id}
          value={value}
          onChange={(event) => onChange(event.target.value)}
          className={cn(
            'h-8 appearance-none rounded-lg border border-tint-border bg-tint-surface py-0 pr-7 pl-8 text-xs font-medium text-tint-ink outline-none hover:bg-tint-panel focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-tint-accent',
            className,
          )}
          {...props}
        >
          {themes.map((theme) => (
            <option key={theme.value} value={theme.value}>
              {theme.label}
            </option>
          ))}
        </select>
        <ChevronDown
          className="pointer-events-none absolute right-2 size-3.5 text-tint-muted"
          aria-hidden="true"
        />
      </div>
    </div>
  )
}

// src/svelte/components/theme/ThemePicker.svelte
<script lang="ts">
  import Icon from '../icon/Icon.svelte'
  import { THEME_GLYPHS } from '../icon/glyphs'
  import type { ThemePickerProps } from './types'

  let { value, onChange, themes, label = 'Theme', class: className, ...rest }: ThemePickerProps = $props()
  const generatedId = $props.id()
  let selectId = $derived(rest.id ?? generatedId)
</script>

<div data-tint-theme-picker="" class="picker">
  <label for={selectId} class="sr-only">{label}</label>
  <div class="field">
    <span class="leading" aria-hidden="true"><Icon icon={THEME_GLYPHS.palette} size="sm" /></span>
    <select {...rest} id={selectId} class={['select', className].filter(Boolean).join(' ')} {value} onchange={(event) => onChange(event.currentTarget.value)}>
      {#each themes as theme (theme.value)}<option value={theme.value}>{theme.label}</option>{/each}
    </select>
    <span class="trailing" aria-hidden="true"><Icon icon={THEME_GLYPHS.chevronDown} size="sm" /></span>
  </div>
</div>

<style>
  .picker { display: inline-flex; max-width: 100%; align-items: center; }
  .field { position: relative; display: inline-flex; max-width: 100%; align-items: center; }
  .select { min-height: 2rem; max-width: 100%; appearance: none; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-surface); padding: 0 var(--tint-space-6) 0 var(--tint-space-7); color: var(--tint-ink); font: inherit; font-size: var(--tint-font-size-xs); font-weight: 500; cursor: pointer; }
  .select:hover { background: var(--tint-panel); }
  .select:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  .leading, .trailing { position: absolute; display: inline-flex; pointer-events: none; color: var(--tint-muted); }
  .leading { left: var(--tint-space-2); }
  .trailing { right: var(--tint-space-2); }
  .sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; }
</style>
