// src/components/telemetry/TraceMetrics.tsx
import { Activity, AlertTriangle, Clock3 } from 'lucide-react'
import { Icon } from '../icon'
import { cn } from '../../lib/utils'
import { formatDuration } from './layout'
import { deriveTraceMetrics } from './metrics'
import type { TraceMetricsProps } from './types'

export function TraceMetrics({ trace, className }: TraceMetricsProps) {
  const metrics = deriveTraceMetrics(trace)

  const cards = [
    {
      key: 'rate',
      label: 'Spans',
      value: String(metrics.spanCount),
      hint: `${metrics.services.length} service${metrics.services.length === 1 ? '' : 's'}`,
      icon: Activity,
    },
    {
      key: 'errors',
      label: 'Errors',
      value: String(metrics.errorCount),
      hint: metrics.errorCount === 0 ? 'No failed spans' : 'Failed spans in this trace',
      icon: AlertTriangle,
      danger: metrics.errorCount > 0,
    },
    {
      key: 'duration',
      label: 'Duration',
      value: formatDuration(metrics.durationMs),
      hint: `p50 ${formatDuration(metrics.p50Ms)} · p95 ${formatDuration(metrics.p95Ms)}`,
      icon: Clock3,
    },
  ] as const

  return (
    <div
      data-trace-metrics=""
      className={cn('grid gap-2 sm:grid-cols-3', className)}
    >
      {cards.map((card) => (
        <article
          key={card.key}
          className={cn(
            'rounded-xl border border-tint-border bg-tint-panel px-3 py-2.5',
            'danger' in card && card.danger && 'border-tint-danger/40 bg-tint-danger-soft',
          )}
        >
          <p className="flex items-center gap-1.5 text-[0.6875rem] font-medium tracking-wide text-tint-muted uppercase">
            <Icon icon={card.icon} size="sm" />
            {card.label}
          </p>
          <p
            className={cn(
              'mt-1 text-lg font-semibold text-tint-ink',
              'danger' in card && card.danger && 'text-tint-danger-ink',
            )}
          >
            {card.value}
          </p>
          <p className="mt-0.5 text-[0.6875rem] text-tint-muted">{card.hint}</p>
        </article>
      ))}
    </div>
  )
}

// src/svelte/components/telemetry/TraceMetrics.svelte
<script lang="ts">
  import { Activity, AlertTriangle, Clock3 } from '@lucide/svelte'
  import { formatDuration } from '../../../core/telemetry/layout'
  import { deriveTraceMetrics } from '../../../core/telemetry/metrics'
  import type { TraceMetricsProps } from './types'

  let { trace, class: className, className: legacyClassName }: TraceMetricsProps = $props()
  let metrics = $derived(deriveTraceMetrics(trace))
</script>

<section data-trace-metrics="" aria-label="Trace metrics" class={['tint-trace-metrics', className, legacyClassName].filter(Boolean).join(' ')}>
  <div class="cards">
    <article><div class="card-header"><span>Spans</span><Activity size={16} aria-hidden="true" /></div><strong>{metrics.spanCount}</strong><p>{metrics.services.length} {metrics.services.length === 1 ? 'service' : 'services'}</p></article>
    <article class:danger={metrics.errorCount > 0}><div class="card-header"><span>Errors</span><AlertTriangle size={16} aria-hidden="true" /></div><strong>{metrics.errorCount}</strong><p>{metrics.errorCount === 0 ? 'No failed spans' : 'Failed spans in this trace'}</p></article>
    <article><div class="card-header"><span>Duration</span><Clock3 size={16} aria-hidden="true" /></div><strong>{formatDuration(metrics.durationMs)}</strong><p>p50 {formatDuration(metrics.p50Ms)} · p95 {formatDuration(metrics.p95Ms)}</p></article>
  </div>
</section>

<style>
  .tint-trace-metrics { min-width: 0; container-type: inline-size; }
  .cards { display: grid; grid-template-columns: 1fr; gap: .5rem; }
  article { min-width: 0; padding: .75rem; border: 1px solid var(--tint-border); border-radius: var(--tint-radius-lg); background: var(--tint-panel); color: var(--tint-ink); }
  article.danger { border-color: var(--tint-danger); background: var(--tint-danger-soft); }
  .card-header { display: flex; justify-content: space-between; gap: .5rem; color: var(--tint-muted); font-size: var(--tint-font-size-xs); font-weight: 500; }
  strong { display: block; margin-top: .25rem; font-size: 1.5rem; line-height: 1.2; font-variant-numeric: tabular-nums; }
  p { margin: .25rem 0 0; color: var(--tint-muted); font-size: var(--tint-font-size-xs); }
  @container (min-width: 34rem) { .cards { grid-template-columns: repeat(3, minmax(0, 1fr)); } }
</style>
