// src/components/telemetry/TraceViewer.tsx
import { useRef, useState } from 'react'
import { cn } from '../../lib/utils'
import { spanById } from './layout'
import { TraceMetrics } from './TraceMetrics'
import { TraceSpanDetail } from './TraceSpanDetail'
import { TraceWaterfall } from './TraceWaterfall'
import type { TraceViewerProps } from './types'

/**
 * LangSmith-style inspect layout: RED metrics, a Gantt waterfall, and the
 * selected span. The service map is a separate surface so chat demos do not
 * pull the graph engine.
 */
export function TraceViewer({
  trace,
  selectedSpanId,
  onSelectedSpanIdChange,
  className,
}: TraceViewerProps) {
  const isControlled = useRef(selectedSpanId !== undefined).current
  const [uncontrolled, setUncontrolled] = useState<string | null>(
    () => trace.spans[0]?.spanId ?? null,
  )
  const selected = isControlled ? (selectedSpanId ?? null) : uncontrolled

  const setSelected = (next: string | null) => {
    if (!isControlled) setUncontrolled(next)
    onSelectedSpanIdChange?.(next)
  }

  return (
    <div data-trace-viewer="" className={cn('grid gap-3', className)}>
      <TraceMetrics trace={trace} />
      <div className="grid gap-3 lg:grid-cols-[minmax(0,1.4fr)_minmax(16rem,1fr)]">
        <TraceWaterfall
          trace={trace}
          selectedSpanId={selected}
          onSelectedSpanIdChange={setSelected}
        />
        <TraceSpanDetail span={spanById(trace, selected)} />
      </div>
    </div>
  )
}

// src/svelte/components/telemetry/TraceViewer.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import { spanById } from '../../../core/telemetry/layout'
  import TraceMetrics from './TraceMetrics.svelte'
  import TraceSpanDetail from './TraceSpanDetail.svelte'
  import TraceWaterfall from './TraceWaterfall.svelte'
  import type { TraceViewerProps } from './types'

  let { trace, selectedSpanId, onSelectedSpanIdChange,
    class: className, className: legacyClassName }: TraceViewerProps = $props()
  let uncontrolled = $state<string | null>(untrack(() => trace.spans[0]?.spanId ?? null))
  let selected = $derived(selectedSpanId === undefined ? uncontrolled : selectedSpanId)

  function selectSpan(next: string | null) {
    if (selectedSpanId === undefined) uncontrolled = next
    onSelectedSpanIdChange?.(next)
  }
</script>

<div data-trace-viewer="" class={['tint-trace-viewer', className, legacyClassName].filter(Boolean).join(' ')}>
  <TraceMetrics {trace} />
  <div class="detail-layout">
    <TraceWaterfall {trace} selectedSpanId={selected} onSelectedSpanIdChange={selectSpan} />
    <TraceSpanDetail span={spanById(trace, selected)} />
  </div>
</div>

<style>
  .tint-trace-viewer { display: grid; min-width: 0; gap: .75rem; container-type: inline-size; }
  .detail-layout { display: grid; min-width: 0; gap: .75rem; }
  @container (min-width: 54rem) { .detail-layout { grid-template-columns: minmax(0, 1.4fr) minmax(16rem, 1fr); } }
</style>
