// src/components/policy/PolicyTable.tsx
import { Badge } from '../badge'
import { DataTable } from '../table'
import type { TableColumn } from '../table'
import type { PolicyDisposition, PolicyRule } from './contracts'

export type PolicyTableProps = {
  rules: readonly PolicyRule[]
  selectedId?: string | null
  onSelect?: (ruleId: string) => void
  onToggle?: (ruleId: string, enabled: boolean) => void
  sourceLabels?: Readonly<Record<string, string>>
  className?: string
  density?: 'compact' | 'comfortable' | 'spacious'
}

const DISPOSITION_TONE: Record<PolicyDisposition, 'accent' | 'info' | 'success'> = {
  auto_queue: 'accent',
  notify_only: 'info',
  notify_and_cache: 'success',
}

/**
 * DataTable of policy rules: name, disposition, match count, enabled toggle.
 *
 * Toggle reports via `onToggle` — the host runs `applyPolicyCommand`; the table
 * never mutates the document itself.
 */
export function PolicyTable({
  rules,
  selectedId = null,
  onSelect,
  onToggle,
  sourceLabels,
  className,
  density = 'comfortable',
}: PolicyTableProps) {
  const columns: TableColumn<PolicyRule>[] = [
    {
      id: 'name',
      header: 'Rule',
      sortable: true,
      renderCell: (row) => (
        <button
          type="button"
          className="text-left font-medium text-tint-ink hover:underline"
          onClick={() => onSelect?.(row.id)}
        >
          {row.name}
        </button>
      ),
    },
    {
      id: 'sourceId',
      header: 'Source',
      accessor: (row) => sourceLabels?.[row.sourceId] ?? row.sourceId,
      sortable: true,
    },
    {
      id: 'disposition',
      header: 'Disposition',
      renderCell: (row) => (
        <Badge tone={DISPOSITION_TONE[row.disposition]}>{row.disposition}</Badge>
      ),
    },
    {
      id: 'matchCount',
      header: 'Matches',
      type: 'number',
      sortable: true,
      align: 'end',
    },
    {
      id: 'enabled',
      header: 'On',
      hideable: false,
      renderCell: (row) => (
        <input
          type="checkbox"
          checked={row.enabled}
          aria-label={`Enable ${row.name}`}
          onChange={(event) => onToggle?.(row.id, event.target.checked)}
        />
      ),
    },
  ]

  return (
    <div
      data-tint-policy-table=""
      data-selected={selectedId ?? undefined}
      className={className}
    >
      <DataTable
        rows={rules}
        columns={columns}
        rowId="id"
        density={density}
        label="Policy rules"
        selection={selectedId ? [selectedId] : []}
        onSelectionChange={
          onSelect
            ? (change) => {
                const next = change.selection[0]
                if (next) onSelect(next)
              }
            : undefined
        }
      />
    </div>
  )
}

// src/svelte/components/policy/PolicyTable.svelte
<script lang="ts">
  import { POLICY_DISPOSITION_TONES, type PolicyRule } from '../../../core/policy'
  import type { TableSelectionChange } from '../../../core/table/types'
  import Badge from '../badge/Badge.svelte'
  import DataTable from '../table/DataTable.svelte'
  import type { TableColumn } from '../table/types'
  import type { PolicyTableProps } from './types'

  let {
    rules, selectedId = null, onSelect, onToggle, sourceLabels,
    class: className, density = 'comfortable',
  }: PolicyTableProps = $props()

  function selectionChanged(change: TableSelectionChange) {
    const next = change.selection[0]
    if (next) onSelect?.(next)
  }
</script>

{#snippet ruleCell(row: PolicyRule)}<button type="button" class="rule-name" disabled={!onSelect} onclick={() => onSelect?.(row.id)}>{row.name}</button>{/snippet}
{#snippet dispositionCell(row: PolicyRule)}<Badge tone={POLICY_DISPOSITION_TONES[row.disposition]}>{row.disposition}</Badge>{/snippet}
{#snippet enabledCell(row: PolicyRule)}<input type="checkbox" aria-label={`Enable ${row.name}`} checked={row.enabled} disabled={!onToggle} onchange={(event) => { onToggle?.(row.id, event.currentTarget.checked); event.currentTarget.checked = row.enabled }} />{/snippet}

<div data-tint-policy-table="" data-selected={selectedId ?? undefined} class={['policy-table', className].filter(Boolean).join(' ')}>
  <DataTable
    rows={rules}
    columns={[
      { id: 'name', header: 'Rule', sortable: true, renderCell: ruleCell },
      { id: 'sourceId', header: 'Source', accessor: (row: PolicyRule) => sourceLabels?.[row.sourceId] ?? row.sourceId, sortable: true },
      { id: 'disposition', header: 'Disposition', renderCell: dispositionCell },
      { id: 'matchCount', header: 'Matches', type: 'number', sortable: true, align: 'end' },
      { id: 'enabled', header: 'On', hideable: false, renderCell: enabledCell },
    ] satisfies TableColumn<PolicyRule>[]}
    rowId="id" {density} label="Policy rules"
    selection={selectedId ? [selectedId] : []}
    onSelectionChange={onSelect ? selectionChanged : undefined}
  />
</div>

<style>
  .policy-table { min-width: 0; max-width: 100%; container-type: inline-size; }
  .rule-name { border: 0; background: transparent; padding: 0; color: var(--tint-ink); cursor: pointer; font: inherit; font-weight: 500; text-align: left; }
  .rule-name:hover { text-decoration: underline; }
  .rule-name:disabled { cursor: default; text-decoration: none; }
  .rule-name:focus-visible, input:focus-visible { outline: var(--tint-focus-width) solid var(--tint-focus); outline-offset: var(--tint-focus-offset); }
  input[type='checkbox'] { accent-color: var(--tint-accent); }
</style>
